---
sidebar: sidebar 
permalink: upgrade/task_hcc_upgrade_element_software.html 
summary: 'Dans le cadre d"une mise à niveau d"un système NetApp SolidFire , vous mettez à niveau le logiciel NetApp Element .' 
keywords: netapp, solidfire, cluster, element, H610S upgrade, hcc, upgrade role 
---
= Logiciel Upgrade Element
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Pour mettre à niveau le logiciel NetApp Element , vous pouvez utiliser l'interface utilisateur de NetApp Hybrid Cloud Control ou l'API REST.  Certaines opérations sont désactivées lors d'une mise à niveau du logiciel Element, telles que l'ajout et la suppression de nœuds, l'ajout et la suppression de disques, et les commandes associées aux initiateurs, aux groupes d'accès aux volumes et aux réseaux virtuels, entre autres.

[CAUTION]
====
Le pack de services de gestion 2.27 inclut le plug-in Element pour vCenter Server 5.5, qui est uniquement compatible avec le nœud de gestion 12.8. Lorsque vous effectuez une mise à jour vers les services de gestion 2.27, vous devez modifier la séquence de mise à niveau et mettre à jour le bundle de services de gestion _après_ la mise à niveau vers Element 12.8 pour assurer la compatibilité entre le nœud de gestion et les services de gestion.

Si vous effectuez une mise à jour vers les services de gestion 2.21.61 à 2.26.40, vous devez mettre à jour le bundle de services de gestion _avant_ la mise à niveau vers Element 12.8.

====
.Avant de commencer
* *Privilèges d'administrateur* : Vous disposez des autorisations d'administrateur de cluster de stockage pour effectuer la mise à niveau.
* *Chemin de mise à niveau valide* : Vous avez vérifié les informations relatives au chemin de mise à niveau pour la version d’Element vers laquelle vous effectuez la mise à niveau et vous avez vérifié que le chemin de mise à niveau est valide.https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Element_Software/What_is_the_upgrade_matrix_for_storage_clusters_running_NetApp_Element_software%3F["Base de connaissances NetApp : Matrice de mise à niveau pour les clusters de stockage exécutant le logiciel NetApp Element"^]
+
À compter de la version 12.5 d'Element, NetApp HealthTools n'est plus pris en charge pour les mises à niveau du logiciel Element.  Si vous utilisez Element 11.0 ou 11.1, vous devez d'abord…link:https://docs.netapp.com/us-en/element-software-123/upgrade/task_hcc_upgrade_element_software.html#upgrade-element-software-at-connected-sites-using-healthtools["Mettez à niveau Element vers la version 12.3.x à l'aide de HealthTools."^] puis effectuez une mise à niveau vers Element 12.5 ou une version ultérieure à l'aide de NetApp Hybrid Cloud Control.

* *Synchronisation de l'heure système* : Vous avez vérifié que l'heure système sur tous les nœuds est synchronisée et que le protocole NTP est correctement configuré pour le cluster de stockage et les nœuds.  Chaque nœud doit être configuré avec un serveur de noms DNS dans l'interface web dédiée.(`https://[IP address]:442` ) sans défauts de cluster non résolus liés au décalage temporel.
* *Ports système* : Si vous utilisez NetApp Hybrid Cloud Control pour les mises à niveau, vous avez vérifié que les ports nécessaires sont ouverts. Voirlink:../storage/reference_prereq_network_port_requirements.html["ports réseau"] pour plus d'informations.
* *Nœud de gestion* : Pour l’interface utilisateur et l’API de NetApp Hybrid Cloud Control, le nœud de gestion de votre environnement exécute la version 11.3.
* *État du cluster* : Vous avez vérifié que le cluster est prêt à être mis à niveau. Voirlink:task_hcc_upgrade_element_prechecks.html["Effectuez des contrôles d'intégrité du stockage Element avant de mettre à niveau le stockage."] .
* *Contrôleur de gestion de carte mère (BMC) mis à jour pour les nœuds de stockage H610S* : Vous avez mis à niveau la version du BMC pour vos nœuds H610S. Voir lelink:https://docs.netapp.com/us-en/hci/docs/rn_H610S_BMC_3.84.07.html["notes de version et instructions de mise à niveau"^] .


[[element-upgrade-tim]]
* *Durée du processus de mise à niveau* : Vous avez prévu suffisamment de temps pour effectuer votre mise à niveau.  Lors de la mise à niveau vers le logiciel Element 12.5 ou une version ultérieure, la durée du processus de mise à niveau varie en fonction de votre version actuelle du logiciel Element et des mises à jour du micrologiciel.
+
[cols="20,20,20,20,20"]
|===
| Nœud de stockage | Version actuelle du logiciel Element | Temps d'installation approximatif des logiciels et micrologiciels par nœud^1^ | Temps approximatif de synchronisation des données par nœud^2^ | Durée totale approximative de mise à niveau par nœud 


| Tous les nœuds SolidFire et NetApp série H avec firmware à jour^3^ | 12.x | 15 minutes | 10 à 15 minutes | 20 à 30 minutes 


| H610S et H410S | 12.x et 11.8 | 60 minutes | 30 à 60 minutes | 90 à 120 minutes 


| H610S | 11.7 et versions antérieures | 90 minutes | 40 à 70 minutes | 130 à 160 minutes Vous devez également https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/H_Series/NetApp_H610S_storage_node_power_off_and_on_procedure["effectuer un arrêt complet du nœud et une déconnexion de l'alimentation"^] pour chaque nœud H610S. 
|===
+
^1^Pour obtenir une matrice complète des microprogrammes et des microprogrammes de pilotes pour votre matériel, voirlink:../hardware/fw_storage_nodes.html["Versions de firmware de stockage prises en charge pour les nœuds de stockage SolidFire"] .

+
^2^Si vous combinez un cluster avec une charge d'EOPS d'écriture importante avec un temps de mise à jour du firmware plus long, le temps de synchronisation des données augmentera.

+
^3^ Les nœuds suivants ne sont pas pris en charge.  Si vous tentez de mettre à niveau l'un de ces nœuds vers une version Element non prise en charge, vous verrez une erreur indiquant que le nœud n'est pas pris en charge par Element 12.x :

+
** À commencer par les nœuds de stockage Element 12.8, SF4805, SF9605, SF19210 et SF38410.
** À commencer par l'élément 12.7, les nœuds de stockage SF2405 et SF9608 et les nœuds FC FC0025 et SF-FCN-01.


* *Contrat de licence utilisateur final (CLUF)* : À partir des services de gestion 2.20.69, vous devez accepter et enregistrer le CLUF avant d’utiliser l’interface utilisateur ou l’API de NetApp Hybrid Cloud Control pour mettre à niveau le logiciel Element :
+
.. Ouvrez l'adresse IP du nœud de gestion dans un navigateur Web :
+
[listing]
----
https://<ManagementNodeIP>
----
.. Connectez-vous à NetApp Hybrid Cloud Control en fournissant les identifiants de l'administrateur du cluster de stockage.
.. Sélectionnez *Mise à niveau* en haut à droite de l'interface.
.. Le CLUF s'affiche.  Faites défiler vers le bas, sélectionnez *J'accepte les mises à jour actuelles et futures*, puis sélectionnez *Enregistrer*.




.Options de mise à niveau
Choisissez l'une des options de mise à niveau du logiciel Element suivantes :

* <<Utilisez l'interface utilisateur de NetApp Hybrid Cloud Control pour mettre à niveau le stockage Element.>>
* <<Utilisez l'API NetApp Hybrid Cloud Control pour mettre à niveau le stockage Element.>>



IMPORTANT: Si vous mettez à niveau un nœud de la série H610S vers Element 12.5 ou une version ultérieure et que le nœud exécute une version d'Element antérieure à 11.8, vous devrez effectuer les étapes de mise à niveau supplémentaires décrites dans ce guide. https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/H_Series/NetApp_H610S_storage_node_power_off_and_on_procedure["Article de la base de connaissances"^] pour chaque nœud de stockage.  Si vous utilisez Element 11.8 ou une version ultérieure, les étapes de mise à niveau supplémentaires ne sont pas nécessaires.



== Utilisez l'interface utilisateur de NetApp Hybrid Cloud Control pour mettre à niveau le stockage Element.

L'interface utilisateur de NetApp Hybrid Cloud Control permet de mettre à niveau un cluster de stockage.


CAUTION: Pour connaître les problèmes potentiels rencontrés lors de la mise à niveau des clusters de stockage à l'aide de NetApp Hybrid Cloud Control et leurs solutions de contournement, consultez ce document. https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/NetApp_HCI/Potential_issues_and_workarounds_when_running_storage_upgrades_using_NetApp_Hybrid_Cloud_Control["Article de la base de connaissances"^] .

.Étapes
. Ouvrez l'adresse IP du nœud de gestion dans un navigateur Web :
+
[listing]
----
https://<ManagementNodeIP>
----
. Connectez-vous à NetApp Hybrid Cloud Control en fournissant les identifiants de l'administrateur du cluster de stockage.
. Sélectionnez *Mise à niveau* en haut à droite de l'interface.
. Sur la page *Mises à niveau*, sélectionnez *Stockage*.
+
L'onglet *Stockage* répertorie les clusters de stockage qui font partie de votre installation.  Si un cluster est inaccessible à NetApp Hybrid Cloud Control, il ne sera pas affiché sur la page *Mises à niveau*.

. Choisissez parmi les options suivantes et effectuez les étapes qui s'appliquent à votre cluster :
+
[cols="2*"]
|===
| Option | Étapes 


| Tous les clusters exécutant Element 11.8 et versions ultérieures  a| 
.. Sélectionnez *Parcourir* pour télécharger le package de mise à niveau que vous avez téléchargé.
.. Veuillez patienter jusqu'à la fin du téléchargement.  Une barre de progression indique l'état du téléchargement.
+

CAUTION: Le fichier téléchargé sera perdu si vous quittez la fenêtre du navigateur.

+
Un message s'affiche à l'écran une fois le fichier téléchargé et validé avec succès.  La validation peut prendre plusieurs minutes.  Si vous quittez la fenêtre du navigateur à ce stade, le fichier téléchargé est conservé.

.. Sélectionnez *Démarrer la mise à niveau*.
+

TIP: L'état de la mise à niveau change au cours de celle-ci pour refléter l'état du processus.  Il change également en fonction des actions que vous entreprenez, comme par exemple la suspension de la mise à niveau, ou si celle-ci renvoie une erreur. Voir<<changements d'état de la mise à niveau>> .

+

NOTE: Pendant la mise à jour, vous pouvez quitter la page et y revenir plus tard pour continuer à suivre son évolution.  La page ne met pas à jour dynamiquement l'état et la version actuelle si la ligne du cluster est réduite.  Il faut développer la ligne du groupe pour mettre à jour le tableau ou vous pouvez actualiser la page.

+
Vous pourrez télécharger les journaux une fois la mise à niveau terminée.





| Vous mettez à niveau un cluster H610S exécutant une version d'Element antérieure à la 11.8.  a| 
.. Sélectionnez la flèche déroulante à côté du cluster que vous mettez à niveau, puis choisissez parmi les versions de mise à niveau disponibles.
.. Sélectionnez *Démarrer la mise à niveau*.  Une fois la mise à niveau terminée, l'interface utilisateur vous invite à effectuer des étapes de mise à niveau supplémentaires.
.. Effectuez les étapes supplémentaires requises dans le https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/H_Series/NetApp_H610S_storage_node_power_off_and_on_procedure["Article de la base de connaissances"^] , et confirmez dans l'interface utilisateur que vous avez terminé la phase 2.


Vous pourrez télécharger les journaux une fois la mise à niveau terminée.  Pour plus d'informations sur les différents changements d'état de la mise à niveau, consultez<<changements d'état de la mise à niveau>> .

|===




=== changements d'état de la mise à niveau

Voici les différents états affichés par la colonne *État de la mise à niveau* dans l'interface utilisateur avant, pendant et après le processus de mise à niveau :

[cols="2*"]
|===
| État de mise à niveau | Description 


| À jour | Le cluster a été mis à niveau vers la dernière version d'Element disponible. 


| Versions disponibles | Des versions plus récentes du firmware Element et/ou du stockage sont disponibles pour la mise à niveau. 


| En cours | La mise à niveau est en cours.  Une barre de progression indique l'état de la mise à niveau.  Les messages à l'écran indiquent également les défauts au niveau des nœuds et affichent l'identifiant de chaque nœud du cluster au fur et à mesure de la progression de la mise à niveau.  Vous pouvez surveiller l'état de chaque nœud à l'aide de l'interface utilisateur Element ou du plug-in NetApp Element pour l'interface utilisateur de vCenter Server. 


| Mise à niveau en pause | Vous pouvez choisir de suspendre la mise à niveau.  Selon l'état du processus de mise à niveau, l'opération de pause peut réussir ou échouer.  Vous verrez apparaître une invite d'interface utilisateur vous demandant de confirmer l'opération de pause.  Pour garantir que le cluster se trouve dans une zone sécurisée avant de suspendre une mise à niveau, la suspension complète de l'opération peut prendre jusqu'à deux heures.  Pour reprendre la mise à niveau, sélectionnez *Reprendre*. 


| En pause | Vous avez interrompu la mise à niveau.  Sélectionnez *Reprendre* pour poursuivre le processus. 


| Erreur | Une erreur s'est produite lors de la mise à niveau.  Vous pouvez télécharger le journal des erreurs et l'envoyer au support NetApp .  Une fois l'erreur résolue, vous pouvez retourner à la page et sélectionner *Reprendre*.  Lorsque vous reprenez la mise à niveau, la barre de progression recule pendant quelques minutes pendant que le système effectue le contrôle d'intégrité et vérifie l'état actuel de la mise à niveau. 


| Avec suivi | Uniquement pour les nœuds H610S mis à niveau à partir d'une version Element antérieure à la 11.8.  Une fois la phase 1 du processus de mise à niveau terminée, cet état vous invite à effectuer des étapes de mise à niveau supplémentaires (voir la section correspondante). https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/H_Series/NetApp_H610S_storage_node_power_off_and_on_procedure["Article de la base de connaissances"^] ).  Une fois la phase 2 terminée et après avoir confirmé l'avoir achevée, le statut passe à *À jour*. 
|===


== Utilisez l'API NetApp Hybrid Cloud Control pour mettre à niveau le stockage Element.

Vous pouvez utiliser des API pour mettre à niveau les nœuds de stockage d'un cluster vers la dernière version du logiciel Element.  Vous pouvez utiliser l'outil d'automatisation de votre choix pour exécuter les API.  Le flux de travail API décrit ici utilise comme exemple l'interface utilisateur de l'API REST disponible sur le nœud de gestion.

.Étapes
. Téléchargez le package de mise à niveau du stockage sur un périphérique accessible par le nœud de gestion.
+
Accédez au logiciel Element https://mysupport.netapp.com/site/products/all/details/element-software/downloads-tab["page de téléchargements"^] et téléchargez la dernière image du nœud de stockage.

. Téléversez le package de mise à niveau du stockage sur le nœud de gestion :
+
.. Ouvrez l'interface utilisateur de l'API REST du nœud de gestion sur ce dernier :
+
[listing]
----
https://<ManagementNodeIP>/package-repository/1/
----
.. Sélectionnez *Autoriser* et complétez les informations suivantes :
+
... Saisissez le nom d'utilisateur et le mot de passe du cluster.
... Saisissez l'identifiant du client comme `mnode-client` .
... Sélectionnez *Autoriser* pour démarrer une session.
... Fermez la fenêtre d'autorisation.


.. Dans l'interface utilisateur de l'API REST, sélectionnez *POST /packages*.
.. Sélectionnez *Essayer*.
.. Sélectionnez *Parcourir* et choisissez le pack de mise à niveau.
.. Sélectionnez *Exécuter* pour lancer le téléchargement.
.. À partir de la réponse, copiez et enregistrez l'identifiant du paquet.(`"id"` ) pour une utilisation ultérieure.


. Vérifiez l'état du téléchargement.
+
.. Dans l'interface utilisateur de l'API REST, sélectionnez *GET /packages/{id}/status*.
.. Sélectionnez *Essayer*.
.. Saisissez l'identifiant du paquet que vous avez copié à l'étape précédente dans *id*.
.. Sélectionnez *Exécuter* pour lancer la demande de statut.
+
La réponse indique `state` comme `SUCCESS` une fois terminé.



. Localisez l'ID du cluster de stockage :
+
.. Ouvrez l'interface utilisateur de l'API REST du nœud de gestion sur ce dernier :
+
[listing]
----
https://<ManagementNodeIP>/inventory/1/
----
.. Sélectionnez *Autoriser* et complétez les informations suivantes :
+
... Saisissez le nom d'utilisateur et le mot de passe du cluster.
... Saisissez l'identifiant du client comme `mnode-client` .
... Sélectionnez *Autoriser* pour démarrer une session.
... Fermez la fenêtre d'autorisation.


.. Dans l'interface utilisateur de l'API REST, sélectionnez *GET /installations*.
.. Sélectionnez *Essayer*.
.. Sélectionnez *Exécuter*.
.. À partir de la réponse, copiez l'identifiant de l'actif d'installation.(`"id"` ).
.. Dans l'interface utilisateur de l'API REST, sélectionnez *GET /installations/{id}*.
.. Sélectionnez *Essayer*.
.. Collez l'identifiant de l'élément d'installation dans le champ *id*.
.. Sélectionnez *Exécuter*.
.. À partir de la réponse, copiez et enregistrez l'ID du cluster de stockage(`"id"` ) du cluster que vous avez l'intention de mettre à niveau pour une utilisation ultérieure.


. Exécutez la mise à niveau du stockage :
+
.. Ouvrez l'interface utilisateur de l'API REST de stockage sur le nœud de gestion :
+
[listing]
----
https://<ManagementNodeIP>/storage/1/
----
.. Sélectionnez *Autoriser* et complétez les informations suivantes :
+
... Saisissez le nom d'utilisateur et le mot de passe du cluster.
... Saisissez l'identifiant du client comme `mnode-client` .
... Sélectionnez *Autoriser* pour démarrer une session.
... Fermez la fenêtre d'autorisation.


.. Sélectionnez *POST /upgrades*.
.. Sélectionnez *Essayer*.
.. Saisissez l'identifiant du package de mise à niveau dans le champ paramètre.
.. Saisissez l'ID du cluster de stockage dans le champ paramètre.
+
La charge utile devrait ressembler à l'exemple suivant :

+
[listing]
----
{
  "config": {},
  "packageId": "884f14a4-5a2a-11e9-9088-6c0b84e211c4",
  "storageId": "884f14a4-5a2a-11e9-9088-6c0b84e211c4"
}
----
.. Sélectionnez *Exécuter* pour lancer la mise à niveau.
+
La réponse doit indiquer l'état comme `initializing` :

+
[listing]
----
{
  "_links": {
    "collection": "https://localhost:442/storage/upgrades",
    "self": "https://localhost:442/storage/upgrades/3fa85f64-1111-4562-b3fc-2c963f66abc1",
    "log": https://localhost:442/storage/upgrades/3fa85f64-1111-4562-b3fc-2c963f66abc1/log
  },
  "storageId": "114f14a4-1a1a-11e9-9088-6c0b84e200b4",
  "upgradeId": "334f14a4-1a1a-11e9-1055`-6c0b84e2001b4",
  "packageId": "774f14a4-1a1a-11e9-8888-6c0b84e200b4",
  "config": {},
  "state": "initializing",
  "status": {
    "availableActions": [
      "string"
    ],
    "message": "string",
    "nodeDetails": [
      {
        "message": "string",
        "step": "NodePreStart",
        "nodeID": 0,
        "numAttempt": 0
      }
    ],
    "percent": 0,
    "step": "ClusterPreStart",
    "timestamp": "2020-04-21T22:10:57.057Z",
    "failedHealthChecks": [
      {
        "checkID": 0,
        "name": "string",
        "displayName": "string",
        "passed": true,
        "kb": "string",
        "description": "string",
        "remedy": "string",
        "severity": "string",
        "data": {},
        "nodeID": 0
      }
    ]
  },
  "taskId": "123f14a4-1a1a-11e9-7777-6c0b84e123b2",
  "dateCompleted": "2020-04-21T22:10:57.057Z",
  "dateCreated": "2020-04-21T22:10:57.057Z"
}
----
.. Copiez l'identifiant de mise à niveau(`"upgradeId"` ) qui fait partie de la réponse.


. Vérifier l'avancement et les résultats de la mise à niveau :
+
.. Sélectionnez *GET /upgrades/{upgradeId}*.
.. Sélectionnez *Essayer*.
.. Saisissez l'ID de mise à niveau de l'étape précédente dans *upgradeId*.
.. Sélectionnez *Exécuter*.
.. En cas de problèmes ou d'exigences particulières lors de la mise à niveau, procédez comme suit :
+
[cols="2*"]
|===
| Option | Étapes 


| Vous devez corriger les problèmes de santé du cluster dus à `failedHealthChecks` message dans le corps de la réponse.  a| 
... Consultez l'article de la base de connaissances spécifique indiqué pour chaque problème ou appliquez la solution indiquée.
... Si une base de connaissances est spécifiée, suivez la procédure décrite dans l'article correspondant.
... Une fois les problèmes de cluster résolus, réauthentifiez-vous si nécessaire et sélectionnez *PUT /upgrades/{upgradeId}*.
... Sélectionnez *Essayer*.
... Saisissez l'ID de mise à niveau de l'étape précédente dans *upgradeId*.
... Entrer `"action":"resume"` dans le corps de la requête.
+
[listing]
----
{
  "action": "resume"
}
----
... Sélectionnez *Exécuter*.




| Vous devez interrompre la mise à niveau car la fenêtre de maintenance arrive à son terme ou pour une autre raison.  a| 
... Réauthentifiez-vous si nécessaire et sélectionnez *PUT /upgrades/{upgradeId}*.
... Sélectionnez *Essayer*.
... Saisissez l'ID de mise à niveau de l'étape précédente dans *upgradeId*.
... Entrer `"action":"pause"` dans le corps de la requête.
+
[listing]
----
{
  "action": "pause"
}
----
... Sélectionnez *Exécuter*.




| Si vous mettez à niveau un cluster H610S exécutant une version d'Element antérieure à la version 11.8, vous verrez l'état suivant : `finishedNeedsAck` dans le corps de la réponse. Vous devez effectuer des étapes de mise à niveau supplémentaires pour chaque nœud de stockage H610S.  a| 
... Suivez les étapes de mise à niveau supplémentaires décrites ici. https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/H_Series/NetApp_H610S_storage_node_power_off_and_on_procedure["Article de la base de connaissances"^] pour chaque nœud.
... Réauthentifiez-vous si nécessaire et sélectionnez *PUT /upgrades/{upgradeId}*.
... Sélectionnez *Essayer*.
... Saisissez l'ID de mise à niveau de l'étape précédente dans *upgradeId*.
... Entrer `"action":"acknowledge"` dans le corps de la requête.
+
[listing]
----
{
  "action": "acknowledge"
}
----
... Sélectionnez *Exécuter*.


|===
.. Exécutez l'API *GET /upgrades/{upgradeId}* plusieurs fois, selon les besoins, jusqu'à ce que le processus soit terminé.
+
Lors de la mise à niveau, le `status` indique `running` si aucune erreur n'est rencontrée.  À mesure que chaque nœud est mis à niveau, `step` la valeur change à `NodeFinished` .

+
La mise à niveau s'est terminée avec succès lorsque `percent` la valeur est `100` et le `state` indique `finished` .







== Que se passe-t-il si une mise à niveau échoue avec NetApp Hybrid Cloud Control ?

Si un disque ou un nœud tombe en panne pendant une mise à niveau, l'interface utilisateur d'Element affichera les défauts du cluster.  Le processus de mise à niveau ne passe pas au nœud suivant et attend que les erreurs du cluster soient résolues.  La barre de progression dans l'interface utilisateur indique que la mise à niveau est en attente de la résolution des erreurs du cluster.  À ce stade, la sélection de *Pause* dans l'interface utilisateur ne fonctionnera pas, car la mise à niveau attend que le cluster soit sain.  Vous devrez faire appel au support NetApp pour vous aider dans l'enquête sur la panne.

NetApp Hybrid Cloud Control prévoit une période d'attente de trois heures, durant laquelle l'un des scénarios suivants peut se produire :

* Les pannes du cluster sont résolues dans un délai de trois heures, et la mise à niveau reprend.  Vous n'avez aucune action à entreprendre dans ce cas de figure.
* Le problème persiste après trois heures et l'état de la mise à niveau affiche *Erreur* avec une bannière rouge.  Vous pouvez reprendre la mise à niveau en sélectionnant *Reprendre* une fois le problème résolu.
* Le support NetApp a déterminé que la mise à niveau doit être temporairement interrompue afin de prendre des mesures correctives avant l'expiration du délai de trois heures.  Le service d'assistance utilisera l'API pour annuler la mise à niveau.



CAUTION: L'interruption de la mise à niveau du cluster pendant la mise à jour d'un nœud peut entraîner le retrait brutal des disques du nœud.  Si les disques sont retirés de manière inappropriée, leur réinstallation lors d'une mise à niveau nécessitera une intervention manuelle du support NetApp .  Le nœud peut prendre plus de temps pour effectuer les mises à jour du micrologiciel ou les activités de synchronisation post-mise à jour.  Si la progression de la mise à niveau semble bloquée, contactez le support NetApp pour obtenir de l'aide.

[discrete]
== Trouver plus d'informations

* https://docs.netapp.com/us-en/element-software/index.html["Documentation logicielle SolidFire et Element"]
* https://docs.netapp.com/us-en/vcp/index.html["Module d'extension NetApp Element pour vCenter Server"^]

