---
permalink: hardware/task_sfseries_psurepl.html 
sidebar: sidebar 
keywords: solidfire chassis, power supply replacement, sf-series nodes 
summary: 'Chaque châssis SolidFire comprend deux blocs d"alimentation pour une redondance électrique.  En cas de panne d"un bloc d"alimentation, il convient de le remplacer dès que possible afin de garantir au châssis une alimentation de secours.' 
---
= Remplacer un bloc d'alimentation
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Chaque châssis SolidFire comprend deux blocs d'alimentation pour une redondance électrique.  En cas de panne d'un bloc d'alimentation, il convient de le remplacer dès que possible afin de garantir au châssis une alimentation de secours.

.Ce dont vous aurez besoin
* Vous avez déterminé que le bloc d'alimentation doit être remplacé.
* Vous disposez d'un bloc d'alimentation de remplacement.
* Vous avez vérifié que le deuxième bloc d'alimentation fonctionne.
* Vous portez un bracelet antistatique (ESD) ou vous avez pris d'autres précautions antistatiques.


.À propos de cette tâche
Ces instructions s'appliquent si vous disposez d'un châssis à une unité rack (1U) avec l'un des nœuds suivants :

* SF2405
* SF4805
* SF9605
* SF9608
* SF19210
* SF38410
* SF-FCN-01
* FC0025


[NOTE]
====
Selon votre version du logiciel Element, les nœuds suivants ne sont pas pris en charge :

* À commencer par les nœuds de stockage Element 12.8, SF4805, SF9605, SF19210 et SF38410.
* À commencer par l'élément 12.7, les nœuds de stockage SF2405 et SF9608, et les nœuds FC FC0025 et SF-FCN-01.
* À partir des nœuds de stockage Element 12.0, SF3010, SF6010 et SF9010.


====
.Étapes
. Débranchez le cordon d'alimentation du bloc d'alimentation que vous remplacez.
. Appuyez sur le bouton de déverrouillage pour faire glisser le bloc d'alimentation hors du châssis.
+

IMPORTANT: Veillez à utiliser vos deux mains pour soutenir le poids du bloc d'alimentation.

. À l'aide des deux mains, alignez les bords du bloc d'alimentation de remplacement avec l'ouverture du châssis, puis poussez délicatement le bloc dans le châssis.
+

IMPORTANT: N’exercez pas une force excessive lors de l’insertion du bloc d’alimentation dans le châssis afin d’éviter d’endommager le matériel.

. Branchez le cordon d'alimentation.
. Retournez l'appareil défectueux à NetApp en suivant les instructions figurant dans la boîte qui vous a été expédiée.
+
Vous pouvez contacter le support NetApp pour obtenir de l'aide concernant la procédure de remplacement.





== Trouver plus d'informations

* https://docs.netapp.com/us-en/element-software/index.html["Documentation logicielle SolidFire et Element"]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["Documentation relative aux versions antérieures des produits NetApp SolidFire et Element"^]

