---
sidebar: sidebar 
permalink: mnode/task_mnode_ssh_management.html 
summary: 'Vous pouvez désactiver et activer la fonctionnalité SSH sur le nœud de gestion à l"aide de l"interface utilisateur de contrôle NetApp Hybrid Cloud ou de l"interface utilisateur de l"API REST, ou déterminer l"état de la capacité de connexion de prise en charge SSH à l"aide de l"interface utilisateur de l"API REST.' 
keywords: netapp, mnode, management node, ssh, disable, enable, rest api, hybrid, cloud, control, hcc 
---
= Gérer la fonctionnalité SSH sur le nœud de gestion
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Vous pouvez désactiver, réactiver ou déterminer l'état de la fonctionnalité SSH sur le nœud de gestion (mNode) à l'aide de l'API REST.  capacité SSH qui fournitlink:task_mnode_enable_remote_support_connections.html["Accès à la session du tunnel d'assistance à distance (RST) de NetApp Support"] est désactivé par défaut sur les nœuds de gestion exécutant les services de gestion 2.18 ou ultérieurs.

À partir de Management Services 2.20.69, vous pouvez activer et désactiver la fonctionnalité SSH sur le nœud de gestion à l'aide de l'interface utilisateur de NetApp Hybrid Cloud Control.

.Ce dont vous aurez besoin
* * Autorisations NetApp Hybrid Cloud Control* : Vous disposez des autorisations d’administrateur.
* *Permissions d'administrateur de cluster* : Vous disposez des autorisations d'administrateur sur le cluster de stockage.
* *Logiciel Element* : Votre cluster exécute le logiciel NetApp Element 11.3 ou une version ultérieure.
* *Nœud de gestion* : Vous avez déployé un nœud de gestion exécutant la version 11.3 ou ultérieure.
* *Mises à jour des services de gestion* :
+
** Pour utiliser l'interface utilisateur de NetApp Hybrid Cloud Control, vous devez mettre à jour votre https://mysupport.netapp.com/site/products/all/details/mgmtservices/downloads-tab["ensemble de services de gestion"^] à la version 2.20.69 ou ultérieure.
** Pour utiliser l'interface utilisateur de l'API REST, vous avez mis à jour votre https://mysupport.netapp.com/site/products/all/details/mgmtservices/downloads-tab["ensemble de services de gestion"^] à la version 2.17.




.Options
* <<Activez ou désactivez la fonctionnalité SSH sur le nœud de gestion à l'aide de l'interface utilisateur de NetApp Hybrid Cloud Control.>>


Vous pouvez effectuer l'une des tâches suivantes après avoirlink:task_mnode_api_get_authorizationtouse.html["authentifier"] :

* <<Activer ou désactiver la fonctionnalité SSH sur le nœud de gestion à l'aide des API>>
* <<Déterminer l'état de la capacité SSH sur le nœud de gestion à l'aide des API>>




== Activez ou désactivez la fonctionnalité SSH sur le nœud de gestion à l'aide de l'interface utilisateur de NetApp Hybrid Cloud Control.

Vous pouvez désactiver ou réactiver la fonctionnalité SSH sur le nœud de gestion.  capacité SSH qui fournitlink:task_mnode_enable_remote_support_connections.html["Accès à la session du tunnel d'assistance à distance (RST) de NetApp Support"] est désactivé par défaut sur les nœuds de gestion exécutant les services de gestion 2.18 ou ultérieurs.  La désactivation de SSH ne met pas fin aux sessions client SSH existantes ni ne les déconnecte du nœud de gestion.  Si vous désactivez SSH et choisissez de le réactiver ultérieurement, vous pouvez le faire à l'aide de l'interface utilisateur de NetApp Hybrid Cloud Control.


NOTE: Pour activer ou désactiver l'accès au support via SSH pour un cluster de stockage, vous devez utiliser lelink:../storage/task_system_manage_cluster_enable_and_disable_support_access.html["page des paramètres du cluster Element UI"] .

.Étapes
. Depuis le tableau de bord, sélectionnez le menu des options en haut à droite et sélectionnez *Configurer*.
. Dans l'écran *Accès au support pour le nœud de gestion*, basculez le commutateur pour activer le SSH du nœud de gestion.
. Une fois le dépannage terminé, dans l'écran *Accès au support pour le nœud de gestion*, basculez l'interrupteur pour désactiver le SSH du nœud de gestion.




== Activer ou désactiver la fonctionnalité SSH sur le nœud de gestion à l'aide des API

Vous pouvez désactiver ou réactiver la fonctionnalité SSH sur le nœud de gestion.  capacité SSH qui fournitlink:task_mnode_enable_remote_support_connections.html["Accès à la session du tunnel d'assistance à distance (RST) de NetApp Support"] est désactivé par défaut sur les nœuds de gestion exécutant les services de gestion 2.18 ou ultérieurs.  La désactivation de SSH ne met pas fin aux sessions client SSH existantes ni ne les déconnecte du nœud de gestion.  Si vous désactivez SSH et choisissez de le réactiver ultérieurement, vous pouvez le faire en utilisant la même API.

.Commande API
Pour les services de gestion 2.18 ou ultérieurs :

[listing]
----
curl -k -X PUT "https://<<ManagementNodeIP>/mnode/2/settings/ssh?enabled=<false/true>" -H  "accept: application/json" -H  "Authorization: Bearer ${TOKEN}"
----
Pour les services de gestion 2.17 ou antérieurs :

[listing]
----
curl -X PUT "https://<ManagementNodeIP>/mnode/settings/ssh?enabled=<false/true>" -H  "accept: application/json" -H  "Authorization: Bearer ${TOKEN}"
----

NOTE: Vous pouvez trouver le porteur `${TOKEN}` utilisé par la commande API lorsque vouslink:task_mnode_api_get_authorizationtouse.html["autoriser"] .  Le porteur `${TOKEN}` se trouve dans la réponse curl.

.Étapes de l'interface utilisateur de l'API REST
. Accédez à l'interface utilisateur de l'API REST du service API du nœud de gestion en saisissant l'adresse IP du nœud de gestion suivie de `/mnode/` :
+
[listing]
----
https://<ManagementNodeIP>/mnode/
----
. Sélectionnez *Autoriser* et complétez les informations suivantes :
+
.. Saisissez le nom d'utilisateur et le mot de passe du cluster.
.. Saisissez l'identifiant du client comme `mnode-client` .
.. Sélectionnez *Autoriser* pour démarrer une session.
.. Ferme la fenêtre.


. Depuis l'interface utilisateur de l'API REST, sélectionnez *PUT /settings/ssh*.
+
.. Sélectionnez *Essayer*.
.. Définissez le paramètre *activé* sur `false` pour désactiver SSH ou `true` pour réactiver la fonctionnalité SSH qui avait été précédemment désactivée.
.. Sélectionnez *Exécuter*.






== Déterminer l'état de la capacité SSH sur le nœud de gestion à l'aide des API

Vous pouvez déterminer si la fonctionnalité SSH est activée ou non sur le nœud de gestion à l'aide d'une API de service du nœud de gestion.  Le protocole SSH est désactivé par défaut sur les nœuds de gestion exécutant les services de gestion 2.18 ou ultérieurs.

.Commande API
Pour les services de gestion 2.18 ou ultérieurs :

[listing]
----
curl -k -X PUT "https://<<ManagementNodeIP>/mnode/2/settings/ssh?enabled=<false/true>" -H  "accept: application/json" -H  "Authorization: Bearer ${TOKEN}"
----
Pour les services de gestion 2.17 ou antérieurs :

[listing]
----
curl -X PUT "https://<ManagementNodeIP>/mnode/settings/ssh?enabled=<false/true>" -H  "accept: application/json" -H  "Authorization: Bearer ${TOKEN}"
----

NOTE: Vous pouvez trouver le porteur `${TOKEN}` utilisé par la commande API lorsque vouslink:task_mnode_api_get_authorizationtouse.html["autoriser"] .  Le porteur `${TOKEN}` se trouve dans la réponse curl...

.Étapes de l'interface utilisateur de l'API REST
. Accédez à l'interface utilisateur de l'API REST du service API du nœud de gestion en saisissant l'adresse IP du nœud de gestion suivie de `/mnode/` :
+
[listing]
----
https://<ManagementNodeIP>/mnode/
----
. Sélectionnez *Autoriser* et complétez les informations suivantes :
+
.. Saisissez le nom d'utilisateur et le mot de passe du cluster.
.. Saisissez l'identifiant du client comme `mnode-client` .
.. Sélectionnez *Autoriser* pour démarrer une session.
.. Ferme la fenêtre.


. Dans l'interface utilisateur de l'API REST, sélectionnez *GET /settings/ssh*.
+
.. Sélectionnez *Essayer*.
.. Sélectionnez *Exécuter*.




[discrete]
== Trouver plus d'informations

* https://docs.netapp.com/us-en/vcp/index.html["Module d'extension NetApp Element pour vCenter Server"^]
* https://docs.netapp.com/us-en/element-software/index.html["Documentation logicielle SolidFire et Element"]

