---
sidebar: sidebar 
permalink: mnode/task_mnode_install_add_storage_NIC.html 
summary: Si vous utilisez une carte réseau supplémentaire pour le stockage, vous devez configurer une interface réseau non étiquetée ou étiquetée. 
keywords: netapp, element, management node, mnode, network, nic, storage nic 
---
= Configurer un contrôleur d'interface réseau (NIC) de stockage
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Si vous utilisez une carte réseau supplémentaire pour le stockage, vous pouvez vous connecter en SSH au nœud de gestion ou utiliser la console vCenter et exécuter une commande curl pour configurer une interface réseau étiquetée ou non étiquetée.

.Avant de commencer
* Vous connaissez votre adresse IP eth0.
* Votre version de cluster exécute le logiciel NetApp Element 11.3 ou une version ultérieure.
* Vous avez déployé un nœud de gestion 11.3 ou ultérieur.


.Options de configuration
Choisissez l'option qui correspond à votre environnement :

* <<Configurer un contrôleur d'interface réseau (NIC) de stockage pour une interface réseau non étiquetée>>
* <<Configurer un contrôleur d'interface réseau (NIC) de stockage pour une interface réseau étiquetée>>




== Configurer un contrôleur d'interface réseau (NIC) de stockage pour une interface réseau non étiquetée

.Étapes
. Ouvrez une console SSH ou vCenter.
. Remplacez les valeurs dans le modèle de commande suivant et exécutez la commande :
+

NOTE: Les valeurs sont représentées par `$` pour chacun des paramètres requis pour votre nouvelle interface réseau de stockage.  Le `cluster` L'objet figurant dans le modèle suivant est obligatoire et peut être utilisé pour renommer le nom d'hôte du nœud de gestion. `--insecure` ou `-k` Ces options ne doivent pas être utilisées dans les environnements de production.

+
[listing]
----
curl -u $mnode_user_name:$mnode_password --insecure -X POST \
https://$mnode_IP:442/json-rpc/10.0 \
-H 'Content-Type: application/json' \
-H 'cache-control: no-cache' \
-d ' {
     "params": {
               "network": {
                          "$eth1": {
                                   "#default" : false,
                                   "address" : "$storage_IP",
                                   "auto" : true,
                                   "family" : "inet",
                                   "method" : "static",
                                   "mtu" : "9000",
                                   "netmask" : "$subnet_mask",
                                   "status" : "Up"
                                   }
                          },
               "cluster": {
                         "name": "$mnode_host_name"
                         }
             },
    "method": "SetConfig"
}
'
----




== Configurer un contrôleur d'interface réseau (NIC) de stockage pour une interface réseau étiquetée

.Étapes
. Ouvrez une console SSH ou vCenter.
. Remplacez les valeurs dans le modèle de commande suivant et exécutez la commande :
+

NOTE: Les valeurs sont représentées par `$` pour chacun des paramètres requis pour votre nouvelle interface réseau de stockage.  Le `cluster` L'objet figurant dans le modèle suivant est obligatoire et peut être utilisé pour renommer le nom d'hôte du nœud de gestion. `--insecure` ou `-k` Ces options ne doivent pas être utilisées dans les environnements de production.

+
[listing]
----
curl -u $mnode_user_name:$mnode_password --insecure -X POST \
https://$mnode_IP:442/json-rpc/10.0 \
-H 'Content-Type: application/json' \
-H 'cache-control: no-cache' \
-d ' {
     "params": {
               "network": {
                          "$eth1": {
                                   "#default" : false,
                                   "address" : "$storage_IP",
                                   "auto" : true,
                                   "family" : "inet",
                                   "method" : "static",
                                   "mtu" : "9000",
                                   "netmask" : "$subnet_mask",
                                   "status" : "Up",
                                   "virtualNetworkTag" : "$vlan_id"
                                   }
                          },
               "cluster": {
                         "name": "$mnode_host_name",
                         "cipi": "$eth1.$vlan_id",
                         "sipi": "$eth1.$vlan_id"
                         }
             },
    "method": "SetConfig"
}
'
----


[discrete]
== Pour en savoir plus, consultez les informations disponibles.

* link:task_mnode_add_assets.html["Ajouter une ressource de contrôleur au nœud de gestion"]
* https://docs.netapp.com/us-en/vcp/index.html["Module d'extension NetApp Element pour vCenter Server"^]
* https://docs.netapp.com/us-en/element-software/index.html["Documentation logicielle SolidFire et Element"]

