= Paramètre
:allow-uri-read: 


Vous pouvez utiliser le `GetNodeFipsDrivesReport` méthode pour vérifier l'état de la capacité de chiffrement de lecteur FIPS 140-2 d'un nœud unique dans le cluster de stockage.  Vous devez exécuter cette méthode sur un nœud de stockage individuel.



== Paramètre

Cette méthode ne comporte aucun paramètre d'entrée.



== Valeurs de retour

Cette méthode renvoie les valeurs suivantes :

|===
| Nom | Description | Type 


 a| 
fipsDrives
 a| 
Un objet JSON contenant l'état de la prise en charge des fonctionnalités FIPS 140-2 pour ce nœud. Valeurs possibles :

* Aucun : le nœud n'est pas compatible FIPS.
* Partiel : Le nœud est compatible FIPS, mais tous les disques du nœud ne sont pas des disques FIPS.
* Prêt : le nœud est compatible FIPS et tous les disques du nœud sont des disques FIPS (ou aucun disque n’est présent).

 a| 
chaîne

|===


== Exemple de demande

Les requêtes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
  "method": "GetNodeFipsDrivesReport",
  "params": {},
  "id" : 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
    "id": 1,
    "result": {
        "fipsDrives": "None"
    }
}
----


== Nouveautés depuis la version

11,5
