= Pour plus d'informations
:allow-uri-read: 


https://activeiq.solidfire.com["SolidFire Active IQ"^]est un outil web qui fournit des vues historiques mises à jour en continu des données à l'échelle du cluster.  Vous pouvez configurer des alertes pour des événements, des seuils ou des indicateurs spécifiques.  SolidFire Active IQ vous permet de surveiller les performances et la capacité du système, ainsi que de rester informé de l'état de santé du cluster.

Vous trouverez les informations suivantes concernant votre système dans SolidFire Active IQ:

* Nombre de nœuds et leur état : opérationnels, hors ligne ou défaillants
* Représentation graphique de l'utilisation du processeur, de la mémoire et de la limitation du nombre de nœuds
* Détails concernant le nœud, tels que le numéro de série, l'emplacement dans le châssis, le modèle et la version du logiciel NetApp Element exécuté sur le nœud de stockage.
* Informations relatives au processeur et au stockage des machines virtuelles


Pour en savoir plus sur SolidFire Active IQ, consultez le https://docs.netapp.com/us-en/solidfire-active-iq/index.html["Documentation SolidFire Active IQ"^] .



== Pour plus d'informations

* https://docs.netapp.com/us-en/element-software/index.html["Documentation logicielle SolidFire et Element"]
* https://docs.netapp.com/us-en/vcp/index.html["Module d'extension NetApp Element pour vCenter Server"^]
* https://mysupport.netapp.com/site/tools/tool-eula/5ddb829ebd393e00015179b2["Site d'assistance NetApp > Outils pour Active IQ"^]

