---
permalink: concepts/concept_rn_whats_new_element.html 
sidebar: sidebar 
keywords: netapp, solidfire, element, storage, solidfire enterprise sds 
summary: NetApp met régulièrement à jour les logiciels SolidFire et Element afin de vous proposer de nouvelles fonctionnalités, des améliorations et des correctifs de bogues. 
---
= Nouveautés du logiciel Element
:allow-uri-read: 
:url-peak: https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Element_Software/Element_Software_-_Apache_Log4j_Vulnerability_-_Workaround
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp met régulièrement à jour les logiciels SolidFire et Element afin de vous proposer de nouvelles fonctionnalités, des améliorations et des correctifs de bugs.  Element 12.8 est la dernière version et comprend des mises à jour de sécurité et des composants système, des améliorations opérationnelles et des problèmes résolus.


NOTE: Les mises à jour cumulatives des logiciels et des microprogrammes sont installées dans le cadre d'une mise à niveau d'Element 12.8 basée sur la version actuelle d'Element exécutée sur un cluster de stockage.  Par exemple, si un cluster exécute actuellement Element 12.5, vous pouvez effectuer une mise à niveau directe vers Element 12.8 pour obtenir les mises à jour cumulatives d'Element 12.7 et 12.8.  Pour connaître les chemins de mise à niveau pris en charge, consultez l'article de la base de connaissances. https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Element_Software/What_is_the_upgrade_matrix_for_storage_clusters_running_NetApp_Element_software["Quelle est la matrice de mise à niveau pour les clusters de stockage exécutant le logiciel NetApp Element ?"^] .



== Élément 12.8

Découvrez les nouveautés d'Element 12.8.



=== Équilibrage de charge volumétrique

Element 12.8 introduit la fonction d'équilibrage de charge volumétrique.  Vous pouvez utiliser cette fonctionnalité pour équilibrer les volumes entre les nœuds en fonction du niveau d'IOPS réel de chaque volume au lieu du niveau d'IOPS minimum configuré dans la politique QoS.  Vous pouvez uniquement utiliser la fonction d'équilibrage de charge des volumes pour équilibrer les volumes.  Vous ne pouvez pas l'utiliser pour équilibrer des volumes virtuels.  La fonction d'équilibrage de charge volumétrique est désactivée par défaut.  Vous pouvez l'activer et le désactiver en utilisant le `VolumeLoadBalanceOnActualIOPS` Paramètre API avec lelink:../api/reference_element_api_enablefeature.html["Activer la fonctionnalité"] etlink:../api/reference_element_api_disablefeature.html["Désactiver la fonctionnalité"] méthodes API ou en utilisant leslink:../storage/task_system_manage_cluster_volume_load_balancing.html["Équilibrage de charge volumétrique"] option dans l'interface utilisateur de l'élément.



=== Afficher les informations d'utilisation des nœuds

Avec Element 12.8, vous pouvez consulter les informations d'utilisation des nœuds comme `nodeHeat` en utilisant le `GetNodeStats` et `ListNodeStats` Méthodes API.  Le `nodeHeat` l'objet est un membre de `nodeStats` objet et affiche les informations d'utilisation du nœud en fonction du ratio des IOPS totales primaires ou des IOPS totales par rapport aux IOPS configurées, moyennées dans le temps.

De plus, vous pouvez visualiser l'utilisation des nœuds en pourcentage de `recentPrimaryTotalHeat` dans l'affichage des détails d'un nœud dans l'interface utilisateur de l'élément.



=== Afficher les statistiques d'E/S pour un volume

Avec Element 12.8, vous pouvez consulter les statistiques d'utilisation des E/S pour un volume sous forme de `sliceIopsStats` en utilisant le `GetVolumeStats` et `ListVolumeStatsByVolume` Méthodes API.  Les statistiques d'E/S sont calculées à partir des informations IOPS de lecture et d'écriture du volume et mesurées sur deux périodes : les dernières 24 heures et la dernière heure. link:../api/reference_element_api_volumestats.html#object-members["Apprendre encore plus"].



=== Algorithme CHAP pour session iSCSI

Un initiateur iSCSI hôte demande une liste d'algorithmes du protocole d'authentification Challenge-Handshake (CHAP) à utiliser lorsqu'il crée une session iSCSI avec une cible iSCSI Element.  À partir d'Element 12.8, vous pouvez consulter l'algorithme CHAP pris en charge que la cible iSCSI Element choisit d'utiliser pour une session iSCSI.



=== Mise à niveau de la version matérielle de la machine virtuelle

Si vous effectuez une mise à niveau sur place d'un nœud de gestion existant vers Element 12.8, avant de procéder à la mise à niveau, vous devez vous assurer que la version matérielle de la machine virtuelle sur le nœud de gestion est compatible avec ESXi 6.7 (version matérielle de la machine virtuelle 14) ou ultérieure en fonction de votre environnement. link:../upgrade/task_hcc_upgrade_management_node.html#step-1-upgrade-vm-hardware-version-on-a-management-node["Apprendre encore plus"].



== Élément 12.7

Découvrez les nouveautés d'Element 12.7.



=== Algorithmes CHAP sécurisés

L'élément 12.7 inclut la prise en charge des algorithmes de protocole d'authentification Challenge-Handshake (CHAP) sécurisés et conformes à la norme FIPS : SHA1, SHA-256 et SHA3-256. link:../storage/task_data_manage_accounts_work_with_accounts_task.html["Apprendre encore plus"].



=== taux de synchronisation dynamique des blocs (bins)

Les opérations de cluster telles que les ajouts, les mises à niveau ou la maintenance des nœuds, ou l'ajout de disques, etc., déclenchent la synchronisation des blocs (bin) pour distribuer les données de blocs aux nœuds nouveaux ou mis à jour dans une configuration de cluster.  L'utilisation d'une seule vitesse lente comme taux de synchronisation par défaut entraîne un allongement du temps d'exécution de ces opérations et ne tire pas parti de la puissance de traitement supérieure des nœuds plus grands.  À partir d'Element 12.7, le taux de synchronisation est ajusté dynamiquement en fonction du nombre de cœurs du nœud de stockage, ce qui permet à ces opérations d'être nettement plus rapides.

Par exemple, lorsque vous ajoutez de grands nœuds de stockage à 28 cœurs (H610S, SF19210 et SF38410) exécutant Element 12.7 à un cluster existant, le taux de synchronisation des données passe automatiquement à 110 Mbps au lieu de 60 Mbps.  De plus, lorsque vous sortez ces grands nœuds de stockage du mode de maintenance des nœuds, par exemple lors d'une mise à niveau d'Element 12.3.x ou ultérieure vers Element 12.7 à l'aide de NetApp Hybrid Cloud Control, le taux de synchronisation pour le débit de données de bloc modifié passe automatiquement à 110 Mbps au lieu de 20 Mbps.

Lorsque vous ajoutez des nœuds de stockage moyens à 16 cœurs (H410S) et des petits nœuds de stockage à 12 cœurs (SF4805) à un cluster Element 12.7, le taux de synchronisation des données reste à 60 Mbps ; cependant, pour la synchronisation des blocs modifiés lorsque vous les sortez du mode de maintenance des nœuds lors des mises à niveau d'Element 12.3.x vers Element 12.7, le taux de synchronisation s'ajuste automatiquement de 20 Mbps à 60 Mbps pour les nœuds de stockage moyens et à 40 Mbps pour les petits nœuds de stockage.

Lorsque vous supprimez des nœuds de stockage, le taux de synchronisation des blocs n'est pas affecté, ce qui évite tout impact sur les performances des E/S client.



=== Amélioration de la collecte des ordures

Pour les clusters dotés de nœuds de stockage plus grands, par exemple un H610S-4, qui ont 1 PB d'espace utilisé, exécutent des charges de travail très élevées avec des écrasements et ont une déduplication et une compression élevées, l'opération de collecte des déchets peut désormais suivre le rythme car la taille par défaut du filtre de Bloom a été augmentée pour les nœuds plus grands de 700 Go ou plus de mémoire à 1048576 bits.  Cette modification prend effet automatiquement après la mise à niveau de vos nœuds de stockage vers Element 12.7 et n'a aucun impact sur les nœuds plus petits.



=== Amélioration de l'échelle

Avec Element 12.7, vous n'avez plus besoin de suivre un séquençage spécifique lors de l'ajout de plusieurs nœuds de stockage de disques de blocs et de métadonnées à un cluster existant.  En utilisant l'interface utilisateur ou l'API d'Element, vous pouvez simplement sélectionner tous les disques disponibles et les ajouter en masse simultanément.  Element 12.7 gère automatiquement la synchronisation des données afin que tous les services de blocs soient synchronisés simultanément.  Une fois la synchronisation des services de blocs terminée pour chaque nœud, le lecteur de métadonnées de ce nœud devient assignable aux volumes hôtes.  Cette amélioration d'échelle réduit considérablement la latence de réponse en lecture et empêche la dégradation des performances pendant la synchronisation des données sur les nœuds de stockage nouvellement ajoutés.



=== mises à jour du firmware des nœuds de stockage

Element 12.7 inclut la version 2.164.0 du firmware de stockage, qui prend en charge de nouveaux composants système. link:https://docs.netapp.com/us-en/hci/docs/rn_storage_firmware_2.164.0.html["Apprendre encore plus"].


NOTE: La version Element 12.7 ne contient aucune nouvelle mise à jour du firmware.  Cependant, en fonction du firmware actuel exécuté sur les nœuds de stockage, les mises à jour cumulatives sont installées lors de la mise à niveau vers Element 12.7.



=== Documentation SolidFire Active IQ

Dans l'interface utilisateur de SolidFire Active IQ , vous pouvez désormais accéder à la page de gestion de la QoS pour consulter les recommandations et les informations de limitation de bande passante des nœuds de votre cluster.  De plus, le tableau de bord du cluster affiche désormais le nombre total d'instantanés.  Parmi les autres améliorations récentes, citons l'ajout d'informations sur les nœuds principaux et secondaires pour les volumes actifs, ainsi que le débit moyen, les IOPS et la latence moyenne des 30 dernières minutes sur les volumes principaux d'un nœud.

Vous pouvez désormais accéder à la documentation SolidFire Active IQ depuis la documentation du logiciel Element. link:https://docs.netapp.com/us-en/element-software/monitor-storage-active-iq.html["Apprendre encore plus"].



=== NetApp Bugs Online contient les problèmes résolus et connus.

Les problèmes résolus et connus sont répertoriés dans l'outil NetApp Bugs Online.  Vous pouvez consulter ces numéros concernant le logiciel Element et d'autres produits sur https://mysupport.netapp.com/site/products/all/details/element-software/bugsonline-tab["Bugs NetApp en ligne"^] .



== Élément 12.5

Découvrez les nouveautés d'Element 12.5.



=== Accès amélioré aux nœuds de stockage

Element 12.5 offre un accès distant amélioré aux nœuds individuels grâce à l'utilisation de certificats SSH signés.  Pour assurer un accès distant sécurisé aux nœuds de stockage, un nouveau compte d'utilisateur local à privilèges limités a été créé. `sfreadonly` est désormais créé lors de l'exécution en temps réel d'un nœud de stockage.  Le `sfreadonly` Ce compte permet d'accéder au système dorsal du nœud de stockage à des fins de maintenance de base ou de dépannage.  Vous pouvez maintenant configurer le `supportAdmin` type d'accès pour un utilisateur administrateur de cluster permettant au support NetApp d'accéder au cluster selon les besoins.



=== Gestion améliorée des domaines de protection personnalisés

Element 12.5 propose une nouvelle interface utilisateur qui vous permet de visualiser rapidement et facilement les domaines de protection personnalisés existants et de configurer de nouveaux domaines de protection personnalisés.



=== Nouveaux défauts, événements et alertes de cluster améliorés

Element 12.5 améliore le dépannage de votre système grâce à l'introduction des nouveaux codes d'erreur du groupe d'outils `BmcSelfTestFailed` et `CpuThermalEventThreshold` .  L'élément 12.5 contient également des améliorations de robustesse pour les événements et alertes de cluster existants, tels que : `nodeOffline` , `volumeOffline` , `driveHealthFault` , `networkEvent` , et	`cSumEvent` .



=== Activez le chiffrement logiciel au repos depuis l'interface utilisateur de création de cluster

Avec l'ajout d'une nouvelle case à cocher dans l'interface utilisateur de création de cluster, Element 12.5 vous offre la possibilité d'activer le chiffrement logiciel au repos à l'échelle du cluster pour les clusters de stockage tout flash SolidFire lors de la création du cluster.



=== mises à jour du firmware des nœuds de stockage

Element 12.5 inclut des mises à jour du firmware pour les nœuds de stockage. link:../concepts/concept_rn_relatedrn_element.html#storage-firmware["Apprendre encore plus"].



=== Sécurité renforcée

L'élément 12.5 contient la mesure d'atténuation qui corrige l'exposition du logiciel Element à la vulnérabilité Apache Log4j.  Les clusters de stockage NetApp SolidFire avec la fonctionnalité Virtual Volumes (VVols) activée sont exposés à la vulnérabilité Apache Log4j.  Pour plus d'informations sur la solution de contournement de la vulnérabilité Apache Log4j dans le logiciel NetApp Element , consultez l'article de la base de connaissances {url-peak}[KB article^].

Si vous utilisez Element 11.x, 12.0 ou 12.2 ou si votre cluster de stockage est déjà sous Element 12.3 ou 12.3.1 avec la fonctionnalité VVols activée, vous devriez effectuer une mise à niveau vers la version 12.5.

L'élément 12.5 comprend également plus de 120 correctifs pour les vulnérabilités de sécurité CVE.



== Trouver plus d'informations

* https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Management_services_for_Element_Software_and_NetApp_HCI/Management_Services_Release_Notes["Notes de version des services de contrôle et de gestion du cloud hybride NetApp"^]
* https://docs.netapp.com/us-en/vcp/index.html["Module d'extension NetApp Element pour vCenter Server"^]
* http://docs.netapp.com/sfe-122/index.jsp["Centre de documentation SolidFire et Element Software pour les versions précédentes"^]
* https://docs.netapp.com/us-en/hci/index.html["Documentation NetApp HCI"^]
* link:../hardware/fw_storage_nodes.html["Versions de firmware de stockage prises en charge pour les nœuds de stockage SolidFire"]

