---
permalink: concepts/concept_solidfire_concepts_data_protection.html 
sidebar: sidebar 
keywords: what is, element, solidfire, replication, clone, snapshot, protection domain, double helix 
summary: Les fonctionnalités de protection des données incluent la réplication à distance, les instantanés de volume, le clonage de volume, les domaines de protection et la haute disponibilité grâce à la technologie Double Helix. 
---
= Protection des données
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les fonctionnalités de protection des données incluent la réplication à distance, les instantanés de volume, le clonage de volume, les domaines de protection et la haute disponibilité grâce à la technologie Double Helix.

La protection des données stockées dans les éléments comprend les concepts suivants :

* <<types de réplication à distance>>
* <<Instantanés de volume pour la protection des données>>
* <<Clones de volume>>
* <<Aperçu du processus de sauvegarde et de restauration pour Element Storage>>
* <<Domaines de protection>>
* <<custom_pd,Domaines de protection personnalisés>>
* <<Haute disponibilité de la double hélice>>




== types de réplication à distance

La réplication à distance des données peut prendre les formes suivantes :

* <<Réplication synchrone et asynchrone entre les clusters>>
* <<Réplication par instantané uniquement>>
* <<Réplication entre les clusters Element et ONTAP à l'aide de SnapMirror>>


Pour plus d'informations, consultez https://www.netapp.com/pdf.html?item=/media/10607-tr4741pdf.pdf["TR-4741 : Réplication à distance du logiciel NetApp Element"^] .



=== Réplication synchrone et asynchrone entre les clusters

Pour les clusters exécutant le logiciel NetApp Element , la réplication en temps réel permet la création rapide de copies distantes des données de volume.

Vous pouvez associer un cluster de stockage à un maximum de quatre autres clusters de stockage.  Vous pouvez répliquer les données de volume de manière synchrone ou asynchrone à partir de l'un ou l'autre cluster d'une paire de clusters pour les scénarios de basculement et de restauration.



==== Réplication synchrone

La réplication synchrone réplique en continu les données du cluster source vers le cluster cible et est affectée par la latence, la perte de paquets, la gigue et la bande passante.

La réplication synchrone est appropriée dans les situations suivantes :

* Réplication de plusieurs systèmes sur une courte distance
* Un site de reprise après sinistre situé géographiquement à proximité de la source
* Applications sensibles au temps et protection des bases de données
* Applications de continuité d'activité nécessitant que le site secondaire prenne le relais du site principal en cas d'indisponibilité de ce dernier.




==== Réplication asynchrone

La réplication asynchrone réplique en continu les données d'un cluster source vers un cluster cible sans attendre les accusés de réception du cluster cible.  Lors de la réplication asynchrone, les écritures sont confirmées au client (application) après leur validation sur le cluster source.

La réplication asynchrone est appropriée dans les situations suivantes :

* Le site de reprise après sinistre est éloigné de la source et l'application ne tolère pas les latences induites par le réseau.
* Le réseau reliant les clusters source et cible présente des limitations de bande passante.




=== Réplication par instantané uniquement

La protection des données par instantané réplique les données modifiées à des moments précis sur un cluster distant.  Seuls les instantanés créés sur le cluster source sont répliqués.  Les écritures actives à partir du volume source ne le sont pas.

Vous pouvez définir la fréquence des réplications d'instantanés.

La réplication par instantané n'affecte pas la réplication asynchrone ou synchrone.



=== Réplication entre les clusters Element et ONTAP à l'aide de SnapMirror

Grâce à la technologie NetApp SnapMirror , vous pouvez répliquer les instantanés pris à l'aide du logiciel NetApp Element vers ONTAP à des fins de reprise après sinistre.  Dans une relation SnapMirror , Element est un point de terminaison et ONTAP est l'autre.

SnapMirror est une technologie de réplication de snapshots NetApp qui facilite la reprise après sinistre, conçue pour le basculement du stockage principal vers le stockage secondaire sur un site géographiquement distant.  La technologie SnapMirror crée une réplique, ou un miroir, des données de travail dans un stockage secondaire à partir duquel vous pouvez continuer à diffuser des données en cas de panne sur le site principal.  Les données sont dupliquées au niveau du volume.

La relation entre le volume source dans le stockage principal et le volume de destination dans le stockage secondaire est appelée relation de protection des données.  Les clusters sont appelés points de terminaison dans lesquels résident les volumes, et les volumes contenant les données répliquées doivent être appariés.  Une relation entre pairs permet aux clusters et aux volumes d'échanger des données en toute sécurité.

SnapMirror fonctionne nativement sur les contrôleurs NetApp ONTAP et est intégré à Element, qui fonctionne sur les clusters NetApp HCI et SolidFire .  La logique de contrôle de SnapMirror réside dans le logiciel ONTAP ; par conséquent, toutes les relations SnapMirror doivent impliquer au moins un système ONTAP pour effectuer le travail de coordination.  Les utilisateurs gèrent les relations entre Element et les clusters ONTAP principalement via l'interface utilisateur d'Element ; cependant, certaines tâches de gestion résident dans NetApp ONTAP System Manager.  Les utilisateurs peuvent également gérer SnapMirror via l'interface de ligne de commande (CLI) et l'interface de programmation (API), toutes deux disponibles dans ONTAP et Element.

Voir https://fieldportal.netapp.com/content/616239["TR-4651 : Architecture et configuration de NetApp SolidFire SnapMirror"^] (connexion requise)

Vous devez activer manuellement la fonctionnalité SnapMirror au niveau du cluster à l'aide du logiciel Element.  La fonctionnalité SnapMirror est désactivée par défaut et n'est pas activée automatiquement lors d'une nouvelle installation ou d'une mise à niveau.

Après avoir activé SnapMirror, vous pouvez créer des relations SnapMirror à partir de l'onglet Protection des données du logiciel Element.

Le logiciel NetApp Element 10.1 et versions ultérieures prend en charge la fonctionnalité SnapMirror pour copier et restaurer des instantanés avec les systèmes ONTAP .

Les systèmes exécutant Element 10.1 et versions ultérieures incluent un code qui peut communiquer directement avec SnapMirror sur les systèmes ONTAP exécutant la version 9.3 ou supérieure.  L'API Element fournit des méthodes permettant d'activer la fonctionnalité SnapMirror sur les clusters, les volumes et les snapshots.  De plus, l'interface utilisateur d'Element inclut des fonctionnalités permettant de gérer les relations SnapMirror entre le logiciel Element et les systèmes ONTAP .

À partir des systèmes Element 10.3 et ONTAP 9.4, vous pouvez répliquer des volumes d'origine ONTAP vers des volumes Element dans des cas d'utilisation spécifiques avec des fonctionnalités limitées.

Pour plus d'informations, voir link:../storage/element-replication-index.html["Réplication entre NetApp Element Software et ONTAP (interface de ligne de commande ONTAP )"].



== Instantanés de volume pour la protection des données

Un instantané de volume est une copie à un instant précis d'un volume que vous pouvez utiliser ultérieurement pour restaurer un volume à ce moment précis.

Bien que les snapshots soient similaires aux clones de volume, les snapshots ne sont que des répliques des métadonnées du volume ; vous ne pouvez donc ni les monter ni y écrire.  La création d'un instantané de volume ne nécessite qu'une petite quantité de ressources système et d'espace, ce qui rend la création d'un instantané plus rapide que le clonage.

Vous pouvez répliquer des instantanés sur un cluster distant et les utiliser comme copie de sauvegarde du volume.  Cela vous permet de restaurer un volume à un point précis dans le temps en utilisant l'instantané répliqué ; vous pouvez également créer un clone d'un volume à partir d'un instantané répliqué.

Vous pouvez sauvegarder des instantanés d'un cluster Element vers un stockage d'objets externe ou vers un autre cluster Element.  Lorsque vous sauvegardez un instantané sur un stockage d'objets externe, vous devez disposer d'une connexion à ce stockage d'objets autorisant les opérations de lecture/écriture.

Vous pouvez prendre un instantané d'un volume individuel ou de plusieurs volumes pour la protection des données.



== Clones de volume

Un clone d'un seul volume ou de plusieurs volumes est une copie des données à un instant précis.  Lorsque vous clonez un volume, le système crée un instantané du volume, puis une copie des données référencées par cet instantané.

Il s'agit d'un processus asynchrone, et sa durée dépend de la taille du volume à cloner et de la charge actuelle du cluster.

Le cluster prend en charge jusqu'à deux demandes de clonage en cours par volume simultanément et jusqu'à huit opérations de clonage de volume actives simultanément.  Les requêtes dépassant ces limites sont mises en file d'attente pour un traitement ultérieur.



== Aperçu du processus de sauvegarde et de restauration pour Element Storage

Vous pouvez sauvegarder et restaurer des volumes sur d'autres systèmes de stockage SolidFire , ainsi que sur des systèmes de stockage d'objets secondaires compatibles avec Amazon S3 ou OpenStack Swift.

Vous pouvez sauvegarder un volume sur les supports suivants :

* Un cluster de stockage SolidFire
* Un magasin d'objets Amazon S3
* Un magasin d'objets OpenStack Swift


Lorsque vous restaurez des volumes à partir d'OpenStack Swift ou d'Amazon S3, vous avez besoin des informations du manifeste issues du processus de sauvegarde d'origine.  Si vous restaurez un volume sauvegardé sur un système de stockage SolidFire , aucune information de manifeste n'est requise.



== Domaines de protection

Un domaine de protection est un nœud ou un ensemble de nœuds regroupés de telle sorte que toute partie, voire la totalité, puisse tomber en panne, tout en maintenant la disponibilité des données.  Les domaines de protection permettent à un cluster de stockage de se réparer automatiquement en cas de perte d'un châssis (affinité de châssis) ou d'un domaine entier (groupe de châssis).

Vous pouvez activer manuellement la surveillance du domaine de protection à l'aide du point d'extension de configuration NetApp Element dans le plug-in NetApp Element pour vCenter Server.  Vous pouvez sélectionner un seuil de domaine de protection en fonction des domaines de nœuds ou de châssis.  Vous pouvez également activer la surveillance du domaine de protection à l'aide de l'API Element ou de l'interface utilisateur Web.

Une configuration de domaine de protection attribue chaque nœud à un domaine de protection spécifique.

Deux configurations de domaine de protection différentes, appelées niveaux de domaine de protection, sont prises en charge.

* Au niveau du nœud, chaque nœud se trouve dans son propre domaine de protection.
* Au niveau du châssis, seuls les nœuds qui partagent un châssis appartiennent au même domaine de protection.
+
** La configuration au niveau du châssis est automatiquement déterminée à partir du matériel lorsque le nœud est ajouté au cluster.
** Dans un cluster où chaque nœud se trouve dans un châssis séparé, ces deux niveaux sont fonctionnellement identiques.




Lors de la création d'un nouveau cluster, si vous utilisez des nœuds de stockage situés dans un châssis partagé, vous pouvez envisager de concevoir une protection contre les pannes au niveau du châssis à l'aide de la fonctionnalité Domaines de protection.



== [[custom_pd]]Domaines de protection personnalisés

Vous pouvez définir une configuration de domaine de protection personnalisée qui correspond à la configuration spécifique de votre châssis et de vos nœuds, et dans laquelle chaque nœud est associé à un seul et unique domaine de protection personnalisé.  Par défaut, chaque nœud est affecté au même domaine de protection personnalisé par défaut.

Si aucun domaine de protection personnalisé n'est attribué :

* Le fonctionnement du cluster n'est pas affecté.
* Le niveau personnalisé n'est ni tolérant ni résilient.


Lorsque vous configurez des domaines de protection personnalisés pour un cluster, il existe trois niveaux de protection possibles, que vous pouvez voir sur le tableau de bord de l'interface utilisateur Web d'Element :

* Non protégé : le cluster de stockage n’est pas protégé contre la défaillance de l’un de ses domaines de protection personnalisés.  Pour résoudre ce problème, ajoutez de la capacité de stockage supplémentaire au cluster ou reconfigurez les domaines de protection personnalisés du cluster afin de le protéger contre d'éventuelles pertes de données.
* Tolérance aux pannes : le cluster de stockage dispose d’une capacité libre suffisante pour éviter toute perte de données après la défaillance de l’un de ses domaines de protection personnalisés.
* Résilience aux pannes : le cluster de stockage dispose d’une capacité libre suffisante pour s’auto-réparer après la défaillance de l’un de ses domaines de protection personnalisés.  Une fois le processus de réparation terminé, le cluster sera protégé contre toute perte de données en cas de défaillance d'autres domaines.


Si plusieurs domaines de protection personnalisés sont attribués, chaque sous-système attribuera les doublons à des domaines de protection personnalisés distincts.  Si cela s'avère impossible, le système attribue les doublons à des nœuds distincts.  Chaque sous-système (par exemple, les compartiments, les tranches, les fournisseurs de points de terminaison de protocole et l'ensemble) effectue cette opération indépendamment.

Vous pouvez utiliser l'interface utilisateur Element pourlink:../storage/task_data_protection_configure_custom_protection_domains.html["configurer des domaines de protection personnalisés"] , ou vous pouvez utiliser les méthodes API suivantes :

* link:../api/reference_element_api_getprotectiondomainlayout.html["ObtenirProtectionDomainLayout"]- indique dans quel châssis et dans quel domaine de protection personnalisé chaque nœud se trouve.
* link:../api/reference_element_api_setprotectiondomainlayout.html["Définir la disposition du domaine de protection"]- permet d'attribuer un domaine de protection personnalisé à chaque nœud.




== Haute disponibilité de la double hélice

La protection des données Double Helix est une méthode de réplication qui répartit au moins deux copies redondantes des données sur tous les disques d'un système.  L’approche « sans RAID » permet à un système d’absorber de multiples pannes simultanées à tous les niveaux du système de stockage et de se réparer rapidement.
