---
permalink: concepts/concept_intro_clusters.html 
sidebar: sidebar 
keywords: element, solidfire, cluster, what is, authoritative  cluster, rule of thirds, stranded capacity, storage efficiency, storage cluster quorum 
summary: 'Un cluster est le centre névralgique d"un système de stockage SolidFire et se compose d"un ensemble de nœuds.  Pour bénéficier des performances de stockage SolidFire , vous devez disposer d"au moins quatre nœuds dans un cluster.  Un cluster apparaît sur le réseau comme un groupe logique unique et peut ensuite être utilisé comme stockage par blocs.' 
---
= Groupes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Un cluster est le centre névralgique d'un système de stockage SolidFire et se compose d'un ensemble de nœuds.  Pour bénéficier des performances de stockage SolidFire , vous devez disposer d'au moins quatre nœuds dans un cluster.  Un cluster apparaît sur le réseau comme un groupe logique unique et peut ensuite être utilisé comme stockage par blocs.

La création d'un nouveau cluster initialise un nœud en tant que propriétaire des communications pour un cluster et établit des communications réseau pour chaque nœud du cluster.  Ce processus n'est effectué qu'une seule fois pour chaque nouveau cluster.  Vous pouvez créer un cluster à l'aide de l'interface utilisateur d'Element ou de l'API.

Vous pouvez faire évoluer un cluster en ajoutant des nœuds supplémentaires.  Lorsque vous ajoutez un nouveau nœud, il n'y a aucune interruption de service et le cluster utilise automatiquement les performances et la capacité du nouveau nœud.

Les administrateurs et les hôtes peuvent accéder au cluster à l'aide d'adresses IP virtuelles.  N'importe quel nœud du cluster peut héberger les adresses IP virtuelles.  L'adresse IP virtuelle de gestion (MVIP) permet la gestion du cluster via une connexion 1GbE, tandis que l'adresse IP virtuelle de stockage (SVIP) permet l'accès de l'hôte au stockage via une connexion 10GbE.  Ces adresses IP virtuelles permettent des connexions stables quelle que soit la taille ou la composition d'un cluster SolidFire .  Si un nœud hébergeant une adresse IP virtuelle tombe en panne, un autre nœud du cluster prend le relais pour héberger cette adresse IP virtuelle.


NOTE: À partir de la version 11.0 d'Element, les nœuds peuvent être configurés avec des adresses IPv4, IPv6 ou les deux pour leur réseau de gestion.  Ceci s'applique aux nœuds de stockage et aux nœuds de gestion, à l'exception du nœud de gestion 11.3 et versions ultérieures qui ne prend pas en charge IPv6.  Lors de la création d'un cluster, une seule adresse IPv4 ou IPv6 peut être utilisée pour le MVIP et le type d'adresse correspondant doit être configuré sur tous les nœuds.

.Plus d'informations sur les clusters
* <<Clusters de stockage faisant autorité>>
* <<Règle des tiers>>
* <<Capacité bloquée>>
* <<Efficacité du stockage>>
* <<quorum du cluster de stockage>>




== Clusters de stockage faisant autorité

Le cluster de stockage faisant autorité est le cluster de stockage utilisé par NetApp Hybrid Cloud Control pour authentifier les utilisateurs.

Si votre nœud de gestion ne possède qu'un seul cluster de stockage, alors il s'agit du cluster faisant autorité.  Si votre nœud de gestion comporte deux clusters de stockage ou plus, l'un de ces clusters est désigné comme cluster faisant autorité et seuls les utilisateurs de ce cluster peuvent se connecter à NetApp Hybrid Cloud Control.  Pour déterminer quel cluster fait autorité, vous pouvez utiliser le `GET /mnode/about` API.  Dans la réponse, l'adresse IP dans le `token_url` Ce champ correspond à l'adresse IP virtuelle de gestion (MVIP) du cluster de stockage faisant autorité.  Si vous tentez de vous connecter à NetApp Hybrid Cloud Control en tant qu'utilisateur n'appartenant pas au cluster faisant autorité, la tentative de connexion échouera.

De nombreuses fonctionnalités de NetApp Hybrid Cloud Control sont conçues pour fonctionner avec plusieurs clusters de stockage, mais l'authentification et l'autorisation présentent des limitations.  La limitation concernant l'authentification et l'autorisation est que l'utilisateur du cluster faisant autorité peut exécuter des actions sur d'autres clusters liés à NetApp Hybrid Cloud Control même s'il n'est pas un utilisateur sur les autres clusters de stockage.

Avant de procéder à la gestion de plusieurs clusters de stockage, vous devez vous assurer que les utilisateurs définis sur les clusters faisant autorité sont définis sur tous les autres clusters de stockage avec les mêmes autorisations.  Vous pouvez gérer les utilisateurs depuis lelink:../storage/concept_system_manage_manage_cluster_administrator_users.html["interface utilisateur du logiciel Element"] .

Voirlink:../mnode/task_mnode_manage_storage_cluster_assets.html["créer et gérer les ressources du cluster de stockage"] pour plus d'informations sur l'utilisation des ressources du cluster de stockage du nœud de gestion.



== Règle des tiers

Lorsque vous mélangez différents types de nœuds de stockage dans un cluster de stockage NetApp SolidFire , aucun nœud de stockage ne peut contenir plus de 33 % de la capacité totale du cluster de stockage.



== Capacité bloquée

Si un nœud nouvellement ajouté représente plus de 50 % de la capacité totale du cluster, une partie de la capacité de ce nœud est rendue inutilisable (« bloquée »), afin qu'il se conforme à la règle de capacité.  Cela restera le cas jusqu'à ce que davantage de capacité de stockage soit ajoutée.  Si un nœud très volumineux est ajouté et qu'il enfreint également la règle de capacité, le nœud précédemment bloqué ne le sera plus, tandis que le nœud nouvellement ajouté le deviendra.  Il convient toujours d'ajouter des capacités par paires pour éviter que cela ne se produise.  Lorsqu'un nœud devient indisponible, une erreur de cluster appropriée est déclenchée.



== Efficacité du stockage

Les clusters de stockage Netapp SolidFire utilisent la déduplication, la compression et le provisionnement fin pour réduire la quantité de stockage physique nécessaire au stockage d'un volume.

* *Compression*
+
La compression réduit la quantité de stockage physique requise pour un volume en combinant les blocs de données en groupes de compression, chacun étant stocké comme un seul bloc.

* *Déduplication*
+
La déduplication réduit la quantité de stockage physique requise pour un volume en supprimant les blocs de données dupliqués.

* *Provisionnement fin*
+
Un volume à provisionnement fin, ou LUN, est un volume pour lequel l'espace de stockage n'est pas réservé à l'avance.  L'espace de stockage est alloué dynamiquement, en fonction des besoins.  L'espace libre est restitué au système de stockage lorsque des données sont supprimées du volume ou du LUN.





== quorum du cluster de stockage

Le logiciel Element crée un cluster de stockage à partir de nœuds sélectionnés, qui maintient une base de données répliquée de la configuration du cluster.  Un minimum de trois nœuds est requis pour participer à l'ensemble du cluster afin de maintenir le quorum nécessaire à la résilience du cluster.
