---
permalink: storage/concept_intro_fibre_channel_nodes.html 
sidebar: sidebar 
keywords: fibre channel nodes, fibre channel switch, clients, protcols, iSCSi protocols, clusters, interconnections, fc, FC, connectivity, fibre channel connectivity, fibre channel nodes, fibre channel protocol 
summary: 'Les nœuds Fibre Channel de SolidFire assurent la connectivité à un commutateur Fibre Channel, auquel vous pouvez connecter des clients Fibre Channel.  Les nœuds Fibre Channel servent de convertisseur de protocole entre les protocoles Fibre Channel et iSCSI ; cela vous permet d"ajouter une connectivité Fibre Channel à tout cluster SolidFire nouveau ou existant.' 
---
= Nœuds Fibre Channel
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les nœuds Fibre Channel de SolidFire assurent la connectivité à un commutateur Fibre Channel, auquel vous pouvez connecter des clients Fibre Channel.  Les nœuds Fibre Channel servent de convertisseur de protocole entre les protocoles Fibre Channel et iSCSI ; cela vous permet d'ajouter une connectivité Fibre Channel à tout cluster SolidFire nouveau ou existant.

Les nœuds Fibre Channel présentent les caractéristiques suivantes :

* Les commutateurs Fibre Channel gèrent l'état du réseau, assurant des interconnexions optimisées.
* Le trafic entre deux ports transite uniquement par les commutateurs ; il n'est transmis à aucun autre port.
* La défaillance d'un port est isolée et n'affecte pas le fonctionnement des autres ports.
* Plusieurs paires de ports peuvent communiquer simultanément au sein d'un réseau.

