---
permalink: storage/concept_system_manage_system_management.html 
sidebar: sidebar 
keywords: element, cluster, fips, cluster, multi-factor authentication, authentication 
summary: 'Vous pouvez gérer votre système dans l"interface utilisateur Element.  Cela inclut l"activation de l"authentification multifactorielle, la gestion des paramètres de cluster, la prise en charge des normes fédérales de traitement de l"information (FIPS) et l"utilisation de la gestion externe des clés.' 
---
= Gérez votre système
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez gérer votre système dans l'interface utilisateur Element.  Cela inclut l'activation de l'authentification multifactorielle, la gestion des paramètres de cluster, la prise en charge des normes fédérales de traitement de l'information (FIPS) et l'utilisation de la gestion externe des clés.

* link:task_system_manage_mfa_set_up_multi_factor_authentication.html["Activer l'authentification multifacteur"]
* link:task_system_manage_cluster_enable_and_disable_encryption_for_a_cluster.html["Configurer les paramètres du cluster"]
* link:task_system_manage_fips_create_a_cluster_supporting_fips_drives.html["Créer un cluster prenant en charge les disques FIPS"]
* link:concept_system_manage_key_get_started_with_external_key_management.html["Commencez la gestion des clés externes"]




== Pour plus d'informations

* https://docs.netapp.com/us-en/element-software/index.html["Documentation logicielle SolidFire et Element"]
* https://docs.netapp.com/us-en/vcp/index.html["Module d'extension NetApp Element pour vCenter Server"^]

