---
permalink: storage/concept_prereq_switch_configuration_for_solidfire_clusters.html 
sidebar: sidebar 
keywords: cluster switch configuration, best practices for switch configuration, optimal storage performance, node hardware, traffic, cluster, Element software, best practices, switches, switch requirements, storage, performance, storage performance 
summary: Le système logiciel NetApp Element présente certaines exigences en matière de commutation et des bonnes pratiques pour des performances de stockage optimales. 
---
= Configuration du commutateur pour les clusters exécutant le logiciel Element
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le système logiciel NetApp Element présente certaines exigences en matière de commutation et des bonnes pratiques pour des performances de stockage optimales.

Les nœuds de stockage nécessitent des commutateurs Ethernet 10 ou 25GbE, selon le matériel spécifique du nœud, pour les services de stockage iSCSI et la communication des services intra-cluster des nœuds.  Les commutateurs 1GbE peuvent être utilisés pour ces types de trafic :

* Gestion du cluster et des nœuds
* Trafic de gestion intra-cluster entre les nœuds
* Le trafic entre les nœuds du cluster et la machine virtuelle du nœud de gestion


|===


 a| 
*Meilleures pratiques :* Vous devriez mettre en œuvre les meilleures pratiques suivantes lors de la configuration des commutateurs Ethernet pour le trafic de cluster :

* Pour le trafic non lié au stockage dans le cluster, déployez une paire de commutateurs 1GbE pour assurer une haute disponibilité et un partage de charge.
* Sur les commutateurs du réseau de stockage, déployez les commutateurs par paires et configurez et utilisez des trames jumbo (une taille MTU de 9216 octets).  Cela garantit une installation réussie et élimine les erreurs de réseau de stockage dues à la fragmentation des paquets.


|===
Le déploiement de l'élément nécessite au moins deux segments de réseau, un pour chacun des types de trafic suivants :

* Gestion
* Stockage/Données


Selon les modèles de nœuds de stockage NetApp série H et la configuration de câblage prévue, vous pouvez séparer physiquement ces réseaux à l'aide de commutateurs distincts ou les séparer logiquement à l'aide de VLAN.  Pour la plupart des déploiements, il est toutefois nécessaire de séparer logiquement ces réseaux à l'aide de VLAN.

Les nœuds de stockage doivent pouvoir communiquer avant, pendant et après le déploiement.

Si vous mettez en œuvre des réseaux de gestion distincts pour les nœuds de stockage, assurez-vous que ces réseaux de gestion disposent de routes réseau entre eux.  Ces réseaux doivent avoir des passerelles attribuées, et il doit exister un itinéraire entre ces passerelles.  Veillez à ce que chaque nouveau nœud dispose d'une passerelle pour faciliter la communication entre les nœuds et les réseaux de gestion.

NetApp Element requiert les éléments suivants :

* Tous les ports de commutateur connectés aux nœuds de stockage NetApp série H doivent être configurés comme ports de périphérie de protocole Spanning Tree.
+
** Sur les commutateurs Cisco , en fonction du modèle de commutateur, de la version du logiciel et du type de port, vous pouvez le faire avec l'une des commandes suivantes :
+
*** `spanning-tree port type edge`
*** `spanning-tree port type edge trunk`
*** `spanning-tree portfast`
*** `spanning-tree portfast trunk`


** Sur les commutateurs Mellanox, vous pouvez le faire avec le `spanning-tree port type edge` commande.


* Les commutateurs gérant le trafic de stockage doivent prendre en charge des vitesses d'au moins 10 GbE par port (jusqu'à 25 GbE par port sont pris en charge).
* Les commutateurs gérant le trafic de gestion doivent prendre en charge des vitesses d'au moins 1 GbE par port.
* Vous devez configurer les trames jumbo sur les ports du commutateur gérant le trafic de stockage.  Pour une installation réussie, les hôtes doivent pouvoir envoyer des paquets de 9000 octets de bout en bout.
* La latence réseau aller-retour entre tous les nœuds de stockage ne doit pas dépasser 2 ms.


Certains nœuds offrent des capacités de gestion hors bande supplémentaires via un port de gestion dédié.  Les nœuds NetApp H300S, H500S et H700S permettent également un accès IPMI via le port A. Il est recommandé, pour faciliter la gestion à distance, de configurer la gestion hors bande pour tous les nœuds de votre environnement.



== Pour plus d'informations

* https://docs.netapp.com/us-en/hci/docs/hci_prereqs_network_switch.html["Exigences relatives au réseau et aux commutateurs NetApp HCI"^]
* https://docs.netapp.com/us-en/element-software/index.html["Documentation logicielle SolidFire et Element"]
* https://docs.netapp.com/us-en/vcp/index.html["Module d'extension NetApp Element pour vCenter Server"^]

