---
permalink: storage/reference_replication_volume_pairing_warnings.html 
sidebar: sidebar 
keywords: volume warnings, messages, replication, data protection 
summary: 'La page « Paires de volumes » de l’onglet « Protection des données » affiche ces messages après l’association des volumes.  Ces messages peuvent s"afficher à la fois sur la source et sur la cible de la paire (sauf indication contraire) dans la vue de liste des volumes répliqués.' 
---
= Avertissements de couplage de volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La page « Paires de volumes » de l’onglet « Protection des données » affiche ces messages après l’appairage des volumes.  Ces messages peuvent s'afficher à la fois sur la source et sur la cible de la paire (sauf indication contraire) dans la vue de liste des volumes répliqués.

* *PausedClusterFull*
+
Le cluster cible étant plein, la réplication source et le transfert de données en masse ne peuvent pas avoir lieu.  Le message s'affiche uniquement sur le périphérique source de la paire.

* *PausedExceededMaxSnapshotCount*
+
Le volume cible possède déjà le nombre maximal d'instantanés et ne peut pas répliquer d'instantanés supplémentaires.

* *Manuel en pause*
+
Le volume local a été mis en pause manuellement.  Il faut la réactiver avant que la réplication ne reprenne.

* *Télécommande manuelle en pause*
+
Le volume de la télécommande est en mode pause manuelle.  Une intervention manuelle est nécessaire pour réactiver le volume distant avant que la réplication ne reprenne.

* *Pause - Configuration incorrecte*
+
En attente d'une source et d'une cible actives.  Intervention manuelle requise pour reprendre la réplication.

* *QoS en pause*
+
La qualité de service cible n'a pas pu supporter les E/S entrantes.  La réplication reprend automatiquement.  Le message s'affiche uniquement sur le périphérique source de la paire.

* *Lien lent en pause*
+
Lien lent détecté, réplication arrêtée.  La réplication reprend automatiquement.  Le message s'affiche uniquement sur le périphérique source de la paire.

* *Incompatibilité de taille de volume en pause*
+
Le volume cible n'est pas de la même taille que le volume source.

* *CopieX en pause*
+
Une commande SCSI XCOPY est émise vers un volume source.  La commande doit s'exécuter complètement avant que la réplication puisse reprendre.  Le message s'affiche uniquement sur le périphérique source de la paire.

* *Arrêt dû à une mauvaise configuration*
+
Une erreur de configuration permanente a été détectée.  Le volume distant a été purgé ou dissocié.  Aucune mesure corrective n'est possible ; un nouveau jumelage doit être établi.


