---
permalink: storage/reference_copyright.html 
sidebar: sidebar 
keywords:  
summary:  
---
= Copyright
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


Copyright © 2021 NetApp, Inc. Tous droits réservés. Imprimé aux États-Unis.

Aucune partie de ce document protégé par le droit d'auteur ne peut être reproduite sous quelque forme ou par quelque moyen que ce soit – graphique, électronique ou mécanique, y compris la photocopie, l'enregistrement, la numérisation ou le stockage dans un système de récupération électronique – sans l'autorisation écrite préalable du titulaire du droit d'auteur.

Les logiciels dérivés des éléments NetApp protégés par copyright sont soumis à la licence et à l'avis de non-responsabilité suivants :

CE LOGICIEL EST FOURNI PAR NETAPP « EN L'ÉTAT » ET SANS GARANTIES EXPRESSES OU TACITES, Y COMPRIS LES GARANTIES TACITES DE QUALITÉ MARCHANDE ET D'ADÉQUATION À UN USAGE PARTICULIER, QUI SONT EXCLUES PAR LA PRÉSENTE. EN AUCUN CAS NETAPP NE SERA TENU POUR RESPONSABLE DE DOMMAGES DIRECTS, INDIRECTS, ACCESSOIRES, PARTICULIERS OU EXEMPLAIRES (Y COMPRIS L'ACHAT DE BIENS ET DE SERVICES DE SUBSTITUTION, LA PERTE DE JOUISSANCE, DE DONNÉES OU DE PROFITS, OU L'INTERRUPTION D'ACTIVITÉ) QUELLES QU'EN SOIENT LA CAUSE ET LA DOCTRINE DE RESPONSABILITÉ, QU'IL S'AGISSE DE RESPONSABILITÉ CONTRACTUELLE, STRICTE OU DÉLICTUELLE (Y COMPRIS LA NÉGLIGENCE OU AUTRE) DÉCOULANT DE L'UTILISATION DE CE LOGICIEL, MÊME SI LA SOCIÉTÉ A ÉTÉ INFORMÉE DE LA POSSIBILITÉ DE TELS DOMMAGES.

NetApp se réserve le droit de modifier les produits décrits dans le présent document à tout moment et sans préavis. NetApp n'accepte aucune responsabilité découlant de l'utilisation des produits décrits dans le présent document, sauf accord explicite écrit de NetApp. L'utilisation ou l'achat de ce produit ne concède pas de licence dans le cadre de droits de brevet, de droits de marque commerciale ou de tout autre droit de propriété intellectuelle de NetApp.

Le produit décrit dans ce manuel peut être protégé par un ou plusieurs brevets américains ou étrangers, ou par des demandes de brevet en attente.

Les données contenues dans le présent document concernent un article commercial (tel que défini dans le FAR 2.101) et sont la propriété de NetApp, Inc. Le gouvernement américain dispose d'une licence non exclusive, non transférable, non sous-licenciable, mondiale, limitée et irrévocable pour utiliser les données uniquement dans le cadre et à l'appui du contrat du gouvernement américain en vertu duquel les données ont été livrées.  Sauf disposition contraire des présentes, les Données ne peuvent être utilisées, divulguées, reproduites, modifiées, exécutées ou affichées sans l'autorisation écrite préalable de NetApp, Inc. Les droits de licence du gouvernement des États-Unis pour le Département de la Défense sont limités aux droits identifiés dans la clause DFARS 252.227-7015(b).
