---
permalink: storage/task_replication_pair_volumes_using_a_pairing_key.html 
sidebar: sidebar 
keywords: volume pairings, pairing key, replication 
summary: 'Si vous ne disposez pas des identifiants d"administrateur de cluster pour un cluster distant, vous pouvez associer un volume à un autre volume sur un cluster distant à l"aide d"une clé d"association.' 
---
= Appairer les volumes à l'aide d'une clé d'appairage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous disposez d'un accès d'administrateur de cluster uniquement au cluster source (vous ne disposez pas d'identifiants d'administrateur de cluster pour un cluster distant), vous pouvez associer un volume à un autre volume sur un cluster distant à l'aide d'une clé d'association.

.Ce dont vous aurez besoin
* Assurez-vous que les clusters contenant les volumes soient appariés.
* Assurez-vous qu'un volume est disponible sur le cluster distant pour l'appairage.
+

NOTE: Vous pouvez attribuer une source et une cible de réplication après le processus d'appairage.  Une source ou une cible de réplication peut être l'un ou l'autre volume d'une paire de volumes.  Vous devez créer un volume cible ne contenant aucune donnée et possédant les caractéristiques exactes du volume source, telles que la taille, le paramètre de taille de bloc pour les volumes (soit 512e, soit 4k) et la configuration QoS.  Si vous désignez un volume existant comme cible de réplication, les données de ce volume seront écrasées.  Le volume cible peut être supérieur ou égal au volume source, mais il ne peut pas être inférieur.



.Étapes
. Sélectionnez *Gestion* > *Volumes*.
. Cliquez sur l'icône *Actions* pour le volume que vous souhaitez appairer.
. Cliquez sur *Associer*.
. Dans la boîte de dialogue *Appairer le volume*, sélectionnez *Démarrer l'appairage*.
. Sélectionnez *Je ne* pour indiquer que vous n'avez pas accès au cluster distant.
. Sélectionnez un *mode de réplication* dans la liste :
+
** *Temps réel (asynchrone)* : Les écritures sont confirmées auprès du client après leur validation sur le cluster source.
** *Temps réel (synchrone)* : Les écritures sont confirmées au client après leur validation sur les clusters source et cible.
** *Instantanés uniquement* : Seuls les instantanés créés sur le cluster source sont répliqués.  Les écritures actives provenant du volume source ne sont pas répliquées.


. Cliquez sur *Générer la clé*.
+

NOTE: Cette action génère une clé de texte pour l'appariement et crée une paire de volumes non configurée sur le cluster local.  Si vous ne terminez pas la procédure, vous devrez supprimer manuellement la paire de volumes.

. Copiez la clé d'appairage dans le presse-papiers de votre ordinateur.
. Rendez la clé d'appairage accessible à l'administrateur du cluster sur le site distant.
+

NOTE: La clé d'appairage du volume doit être traitée de manière sécurisée et ne doit pas être utilisée d'une façon qui permettrait un accès accidentel ou non sécurisé.

+

IMPORTANT: Ne modifiez aucun des caractères de la clé d'appariement.  La clé devient invalide si elle est modifiée.

. Dans l'interface utilisateur Element du cluster distant, sélectionnez *Gestion* > *Volumes*.
. Cliquez sur l'icône Actions correspondant au volume que vous souhaitez appairer.
. Cliquez sur *Associer*.
. Dans la boîte de dialogue *Appairer le volume*, sélectionnez *Terminer l'appairage*.
. Collez la clé d'appairage de l'autre cluster dans la case *Clé d'appairage*.
. Cliquez sur *Terminer l'appairage*.
+
Une fois l'appairage confirmé, les deux clusters entament le processus de connexion des volumes pour l'appairage.  Pendant le processus d'appairage, vous pouvez voir des messages dans la colonne *État du volume* de la fenêtre *Paires de volumes*.  La paire de volumes affiche `PausedMisconfigured` jusqu'à ce que la paire de volumes source et cible soit attribuée.

+
Une fois l'appairage terminé avec succès, il est recommandé d'actualiser le tableau Volumes pour supprimer l'option *Apparier* de la liste *Actions* du volume apparié.  Si vous ne rafraîchissez pas le tableau, l'option *Paire* reste disponible pour la sélection.  Si vous sélectionnez à nouveau l'option *Associer*, un nouvel onglet s'ouvre et, comme le volume est déjà associé, le système signale un `StartVolumePairing Failed: xVolumeAlreadyPaired` Message d'erreur dans la fenêtre *Volume de la paire* de la page Element UI.





== Trouver plus d'informations

* xref:reference_replication_volume_pairing_messages.adoc[Messages de couplage de volume]
* xref:reference_replication_volume_pairing_warnings.adoc[Avertissements de couplage de volume]
* xref:task_replication_assign_replication_source_and_target_to_paired_volumes.adoc[Attribuer une source et une cible de réplication aux volumes appariés]

