---
permalink: storage/task_system_manage_fips_create_a_cluster_supporting_fips_drives.html 
sidebar: sidebar 
keywords: fips, security, federal information processing standards, 140-2, cluster, create 
summary: 'La sécurité devient un facteur de plus en plus crucial pour le déploiement de solutions dans de nombreux environnements clients.  Les normes fédérales de traitement de l"information (FIPS) sont des normes relatives à la sécurité et à l"interopérabilité des ordinateurs.  Le chiffrement des données au repos, certifié FIPS 140-2, est un élément de la solution de sécurité globale.' 
---
= Préparer le cluster Element pour la fonction de disques FIPS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La sécurité devient un facteur de plus en plus crucial pour le déploiement de solutions dans de nombreux environnements clients.  Les normes fédérales de traitement de l'information (FIPS) sont des normes relatives à la sécurité et à l'interopérabilité des ordinateurs.  Le chiffrement des données au repos, certifié FIPS 140-2, est un élément de la solution de sécurité globale.

Pour préparer l'activation de la fonctionnalité des disques FIPS, vous devez éviter de mélanger des nœuds dont certains sont compatibles avec les disques FIPS et d'autres non.

Un cluster est considéré comme conforme aux normes FIPS selon les conditions suivantes :

* Tous les disques sont certifiés FIPS.
* Tous les nœuds sont des nœuds de disques FIPS.
* Le chiffrement au repos (EAR) est activé.
* La fonction de lecteur FIPS est activée.  Tous les disques et nœuds doivent être compatibles FIPS et le chiffrement au repos doit être activé pour activer la fonctionnalité de disque FIPS.

