---
permalink: storage/task_data_manage_vvol_create_a_storage_container.html 
sidebar: sidebar 
keywords: storage container, create 
summary: 'Vous pouvez créer des conteneurs de stockage dans l"interface utilisateur d"Element et les découvrir dans vCenter.  Vous devez créer au moins un conteneur de stockage pour commencer à provisionner des machines virtuelles basées sur VVol.' 
---
= Créer un conteneur de stockage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez créer des conteneurs de stockage dans l'interface utilisateur d'Element et les découvrir dans vCenter.  Vous devez créer au moins un conteneur de stockage pour commencer à provisionner des machines virtuelles basées sur VVol.

Vous avez activé la fonctionnalité VVols dans l'interface utilisateur Element pour le cluster.

. Sélectionnez *VVols* > *Conteneurs de stockage*.
. Cliquez sur le bouton *Créer des conteneurs de stockage*.
. Saisissez les informations du conteneur de stockage dans la boîte de dialogue *Créer un nouveau conteneur de stockage* :
+
.. Saisissez un nom pour le conteneur de stockage.
.. Configurez les secrets de l'initiateur et de la cible pour CHAP.
+

TIP: Laissez les champs Paramètres CHAP vides pour générer automatiquement les secrets.

.. Cliquez sur le bouton *Créer un conteneur de stockage*.


. Vérifiez que le nouveau conteneur de stockage apparaît bien dans la liste de l'onglet *Conteneurs de stockage*.
+

NOTE: Comme un ID de compte NetApp Element est créé automatiquement et attribué au conteneur de stockage, il n'est pas nécessaire de créer un compte manuellement.


