---
permalink: storage/task_post_deploy_credential_change_ipmi_password.html 
sidebar: sidebar 
keywords: ipmi, password, intelligent platform management interface, netapp, element, h410s, h610s 
summary: 'Vous pouvez modifier le mot de passe administrateur par défaut de l"interface de gestion de plateforme intelligente (IPMI) dès que vous disposez d"un accès IPMI distant au nœud.  Vous pourriez vouloir faire cela s"il y a des mises à jour d"installation.' 
---
= Modifier le mot de passe IPMI par défaut des nœuds
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez modifier le mot de passe administrateur par défaut de l'interface de gestion de plateforme intelligente (IPMI) dès que vous disposez d'un accès IPMI distant au nœud.  Vous pourriez vouloir faire cela s'il y a des mises à jour d'installation.

Pour plus de détails sur la configuration de l'accès IPM pour les nœuds, consultezlink:https://docs.netapp.com/us-en/hci/docs/hci_prereqs_final_prep.html["Configurer IPMI pour chaque nœud"^] .

Vous pouvez modifier le mot de passe IPM pour ces nœuds :

* Nœuds H410S
* Nœuds H610S




== Modifier le mot de passe IPMI par défaut des nœuds H410S

Vous devez modifier le mot de passe par défaut du compte administrateur IPMI sur chaque nœud de stockage dès que vous configurez le port réseau IPMI.

.Ce dont vous aurez besoin
Vous auriez dû configurer l'adresse IP IPMI pour chaque nœud de stockage.

.Étapes
. Ouvrez un navigateur web sur un ordinateur pouvant accéder au réseau IPMI et accédez à l'adresse IP IPMI du nœud.
. Saisissez le nom d'utilisateur `ADMIN` et mot de passe `ADMIN` dans l'invite de connexion.
. Une fois connecté, cliquez sur l'onglet *Configuration*.
. Cliquez sur *Utilisateurs*.
. Sélectionnez `ADMIN` utilisateur et cliquez sur *Modifier l'utilisateur*.
. Cochez la case *Changer le mot de passe*.
. Saisissez un nouveau mot de passe dans les champs *Mot de passe* et *Confirmer le mot de passe*.
. Cliquez sur *Modifier*, puis sur *OK*.
. Répétez cette procédure pour tous les autres nœuds H410S ayant des mots de passe IPMI par défaut.




== Modifier le mot de passe IPMI par défaut des nœuds H610S

Vous devez modifier le mot de passe par défaut du compte administrateur IPMI sur chaque nœud de stockage dès que vous configurez le port réseau IPMI.

.Ce dont vous aurez besoin
Vous auriez dû configurer l'adresse IP IPMI pour chaque nœud de stockage.

.Étapes
. Ouvrez un navigateur web sur un ordinateur pouvant accéder au réseau IPMI et accédez à l'adresse IP IPMI du nœud.
. Saisissez le nom d'utilisateur `root` et mot de passe `calvin` dans l'invite de connexion.
. Une fois connecté, cliquez sur l'icône de navigation du menu en haut à gauche de la page pour ouvrir le panneau latéral.
. Cliquez sur *Paramètres*.
. Cliquez sur *Gestion des utilisateurs*.
. Sélectionnez l'utilisateur *Administrateur* dans la liste.
. Cochez la case *Changer le mot de passe*.
. Saisissez un nouveau mot de passe fort dans les champs *Mot de passe* et *Confirmer le mot de passe*.
. Cliquez sur *Enregistrer* en bas de la page.
. Répétez cette procédure pour tous les autres nœuds H610S ayant des mots de passe IPMI par défaut.




== Trouver plus d'informations

* https://docs.netapp.com/us-en/element-software/index.html["Documentation logicielle SolidFire et Element"]
* https://docs.netapp.com/us-en/vcp/index.html["Module d'extension NetApp Element pour vCenter Server"^]

