---
permalink: storage/task-element-replication-reactivate-original-source-volume.html 
sidebar: sidebar 
keywords: ontap,cli, reactivate, original, source, volume 
summary: 'Vous pouvez rétablir la relation de protection des données d"origine entre les volumes source et de destination lorsque vous n"avez plus besoin de diffuser de données depuis la destination.' 
---
= Réactiver le volume source d'origine
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez rétablir la relation de protection des données d'origine entre les volumes source et de destination lorsque vous n'avez plus besoin de diffuser de données depuis la destination.

.À propos de cette tâche
La procédure ci-dessous suppose que la ligne de base du volume source d'origine est intacte.  Si la ligne de base n'est pas intacte, vous devez créer et initialiser la relation entre le volume à partir duquel vous servez les données et le volume source d'origine avant d'effectuer la procédure.

Vous devez spécifier le chemin source de l'élément dans le formulaire `<hostip:>/lun/<name>` , où "`lun`" est la chaîne de caractères réelle "`lun`" et `name` est le nom du volume Element.

À partir d' ONTAP 9.4, les copies instantanées d'un LUN créées pendant que vous servez des données à partir de la destination ONTAP sont automatiquement répliquées lorsque la source Element est réactivée.

Les règles de réplication sont les suivantes :

* Seuls les LUN iSCSI sont pris en charge.
* Vous ne pouvez pas répliquer plus d'un LUN d'un volume ONTAP vers un volume Element.
* Vous ne pouvez pas répliquer un LUN d'un volume ONTAP vers plusieurs volumes Element.


.Étapes
. Supprimer la relation de protection des données d'origine :
+
`snapmirror delete -source-path <SVM:volume>|<cluster://SVM/volume> -destination-path <hostip:>/lun/<name> -policy <policy>`

+
Pour connaître la syntaxe complète des commandes, consultez la page de manuel.

+
L'exemple suivant supprime la relation entre le volume source d'origine, `0005` à l'adresse IP 10.0.0.11 et le volume à partir duquel vous servez des données, `volA_dst` sur `svm_backup` :

+
[listing]
----
cluster_dst::> snapmirror delete -source-path 10.0.0.11:/lun/0005 -policy MirrorLatest -destination-path svm_backup:volA_dst
----
. Inverser la relation initiale de protection des données :
+
`snapmirror resync -source-path <SVM:volume>|<cluster://SVM/volume> -destination-path <hostip:>/lun/<name> -policy <policy>`

+
Pour connaître la syntaxe complète des commandes, consultez la page de manuel.

+
Bien que la resynchronisation ne nécessite pas de transfert de base, elle peut prendre du temps.  Il serait peut-être préférable d'effectuer la resynchronisation en dehors des heures de pointe.

+
L'exemple suivant inverse la relation entre le volume source d'origine, `0005` à l'adresse IP 10.0.0.11 et le volume à partir duquel vous servez des données, `volA_dst` sur `svm_backup` :

+
[listing]
----
cluster_dst::> snapmirror resync -source-path svm_backup:volA_dst -destination-path 10.0.0.11:/lun/0005 -policy MirrorLatest
----
. Mettre à jour la relation inversée :
+
`snapmirror update -source-path <SVM:volume>|<cluster://SVM/volume> -destination-path <hostip:>/lun/<name>`

+
Pour connaître la syntaxe complète des commandes, consultez la page de manuel.

+
[NOTE]
====
La commande échoue si une copie instantanée commune n'existe pas sur la source et la destination.  Utiliser `snapmirror initialize` pour réinitialiser la relation.

====
+
L'exemple suivant met à jour la relation entre le volume à partir duquel vous servez des données, `volA_dst` sur `svm_backup` , et le volume source original, `0005` à l'adresse IP 10.0.0.11 :

+
[listing]
----
cluster_dst::> snapmirror update -source-path svm_backup:volA_dst -destination-path 10.0.0.11:/lun/0005
----
. Interrompre les virements programmés pour la relation inversée :
+
`snapmirror quiesce -source-path <SVM:volume>|<cluster://SVM/volume> -destination-path <hostip:>/lun/<name>`

+
Pour connaître la syntaxe complète des commandes, consultez la page de manuel.

+
L'exemple suivant interrompt les transferts planifiés entre le volume à partir duquel vous servez des données, `volA_dst` sur `svm_backup` , et le volume source original, `0005` à l'adresse IP 10.0.0.11 :

+
[listing]
----
cluster_dst::> snapmirror quiesce -source-path svm_backup:volA_dst -destination-path 10.0.0.11:/lun/0005
----
. Arrêter les transferts en cours pour la relation inversée :
+
`snapmirror abort -source-path <SVM:volume>|<cluster://SVM/volume> -destination-path <hostip:>/lun/<name>`

+
Pour connaître la syntaxe complète des commandes, consultez la page de manuel.

+
L'exemple suivant interrompt les transferts en cours entre le volume à partir duquel vous servez les données, `volA_dst` sur `svm_backup` , et le volume source original, `0005` à l'adresse IP 10.0.0.11 :

+
[listing]
----
cluster_dst::> snapmirror abort -source-path svm_backup:volA_dst -destination-path 10.0.0.11:/lun/0005
----
. Rompre la relation inversée :
+
`snapmirror break -source-path <SVM:volume>|<cluster://SVM/volume> -destination-path <hostip:>/lun/<name>`

+
Pour connaître la syntaxe complète des commandes, consultez la page de manuel.

+
L'exemple suivant rompt la relation entre le volume à partir duquel vous servez des données, `volA_dst` sur `svm_backup` , et le volume source original, `0005` à l'adresse IP 10.0.0.11 :

+
[listing]
----
cluster_dst::> snapmirror break -source-path svm_backup:volA_dst -destination-path 10.0.0.11:/lun/0005
----
. Supprimer la relation de protection des données inversée :
+
`snapmirror delete -source-path <SVM:volume>|<cluster://SVM/volume> -destination-path <hostip:>/lun/<name> -policy <policy>`

+
Pour connaître la syntaxe complète des commandes, consultez la page de manuel.

+
L'exemple suivant supprime la relation inversée entre le volume source d'origine, `0005` à l'adresse IP 10.0.0.11 et le volume à partir duquel vous servez des données, `volA_dst` sur `svm_backup` :

+
[listing]
----
cluster_src::> snapmirror delete -source-path svm_backup:volA_dst -destination-path 10.0.0.11:/lun/0005 -policy MirrorLatest
----
. Rétablir la relation initiale de protection des données :
+
`snapmirror resync -source-path <hostip:>/lun/<name> -destination-path <SVM:volume>|<cluster://SVM/volume>`

+
Pour connaître la syntaxe complète des commandes, consultez la page de manuel.

+
L'exemple suivant rétablit la relation entre le volume source original, `0005` à l'adresse IP 10.0.0.11 et au volume de destination d'origine, `volA_dst` sur `svm_backup` :

+
[listing]
----
cluster_dst::> snapmirror resync -source-path 10.0.0.11:/lun/0005 -destination-path svm_backup:volA_dst
----


.Après avoir terminé
Utilisez le `snapmirror show` commande permettant de vérifier que la relation SnapMirror a été créée.  Pour connaître la syntaxe complète des commandes, consultez la page de manuel.
