---
permalink: storage/task_replication_plan_cluster_and_volume_pairing.html 
sidebar: sidebar 
keywords: cluster, volume pairing, plan for, real-time replication 
summary: La réplication à distance en temps réel nécessite que vous appariiez deux clusters de stockage exécutant le logiciel Element, appariiez les volumes sur chaque cluster et validiez la réplication.  Une fois la réplication terminée, vous devez supprimer la relation de volume. 
---
= Planifier l'association des clusters et des volumes pour la réplication en temps réel
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La réplication à distance en temps réel nécessite que vous appariiez deux clusters de stockage exécutant le logiciel Element, appariiez les volumes sur chaque cluster et validiez la réplication.  Une fois la réplication terminée, vous devez supprimer la relation de volume.

.Ce dont vous aurez besoin
* Vous devez disposer des privilèges d'administrateur de cluster pour l'un ou les deux clusters appariés.
* Toutes les adresses IP des nœuds des réseaux de gestion et de stockage des clusters appariés sont routées entre elles.
* L'unité de transmission maximale (MTU) de tous les nœuds appariés doit être identique et prise en charge de bout en bout entre les clusters.
* Chaque cluster de stockage doit avoir un nom de cluster unique, des adresses IP virtuelles multiples (MVIP), des adresses IP virtuelles de second niveau (SVIP) et des adresses IP de nœud uniques.
* La différence entre les versions du logiciel Element sur les clusters ne dépasse pas une version majeure.  Si la différence est plus importante, l'un des clusters doit être mis à niveau pour effectuer la réplication des données.



NOTE: Les appliances WAN Accelerator n'ont pas été homologuées par NetApp pour une utilisation lors de la réplication de données.  Ces dispositifs peuvent interférer avec la compression et la déduplication s'ils sont déployés entre deux clusters qui répliquent des données.  Veillez à bien évaluer les effets de tout dispositif d'accélération WAN avant de le déployer dans un environnement de production.



== Trouver plus d'informations

* xref:task_replication_pair_clusters.adoc[Apparier les clusters pour la réplication]
* xref:task_replication_pair_volumes.adoc[Volumes de paires]
* xref:task_replication_assign_replication_source_and_target_to_paired_volumes.adoc[Attribuer une source et une cible de réplication aux volumes appariés]

