---
permalink: storage/task_data_protection_clone_multiple_volumes.html 
sidebar: sidebar 
keywords: multiple volumes, clone, create 
summary: Vous pouvez créer plusieurs clones de volume en une seule opération afin de créer une copie à un instant donné des données sur un groupe de volumes. 
---
= Cloner plusieurs volumes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez créer plusieurs clones de volume en une seule opération afin de créer une copie à un instant donné des données sur un groupe de volumes.

Lorsque vous clonez un volume, le système crée un instantané du volume, puis crée un nouveau volume à partir des données contenues dans cet instantané.  Vous pouvez monter le nouveau clone de volume et y écrire.  Le clonage de plusieurs volumes est un processus asynchrone et prend un temps variable en fonction de la taille et du nombre de volumes clonés.

La taille du volume et la charge actuelle du cluster influent sur le temps nécessaire pour effectuer une opération de clonage.

.Étapes
. Cliquez sur *Gestion* > *Volumes*.
. Cliquez sur l'onglet *Actif*.
. Utilisez les cases à cocher pour sélectionner plusieurs volumes et créer un groupe de volumes.
. Cliquez sur *Actions groupées*.
. Cliquez sur *Cloner* dans le menu qui s'affiche.
. Saisissez un *préfixe de nom de nouveau volume* dans la boîte de dialogue *Cloner plusieurs volumes*.
+
Le préfixe est appliqué à tous les volumes du groupe.

. *Facultatif :* Sélectionnez un autre compte auquel le clone appartiendra.
+
Si vous ne sélectionnez pas de compte, le système attribue les nouveaux volumes au compte de volumes actuel.

. *Facultatif :* Sélectionnez une autre méthode d’accès pour les volumes du clone.
+
Si vous ne sélectionnez pas de méthode d'accès, le système utilise l'accès au volume actuel.

. Cliquez sur *Démarrer le clonage*.

