---
permalink: storage/task_data_protection_delete_a_snapshot.html 
sidebar: sidebar 
keywords: snapshot, delete, volume snapshot, storage cluster, remove snapshot 
summary: 'Vous pouvez supprimer un instantané de volume d"un cluster de stockage exécutant le logiciel Element.  Lorsque vous supprimez un instantané, le système le supprime immédiatement.' 
---
= Supprimer un instantané
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez supprimer un instantané de volume d'un cluster de stockage exécutant le logiciel Element.  Lorsque vous supprimez un instantané, le système le supprime immédiatement.

Vous pouvez supprimer les instantanés en cours de réplication à partir du cluster source.  Si un instantané est en cours de synchronisation avec le cluster cible lorsque vous le supprimez, la réplication de synchronisation se termine et l'instantané est supprimé du cluster source.  L'instantané n'est pas supprimé du cluster cible.

Vous pouvez également supprimer les instantanés qui ont été répliqués sur la cible depuis le cluster cible.  L'instantané supprimé est conservé dans une liste d'instantanés supprimés sur la cible jusqu'à ce que le système détecte que vous avez supprimé l'instantané sur le cluster source.  Lorsque la cible détecte que vous avez supprimé l'instantané source, elle interrompt la réplication de cet instantané.

Lorsque vous supprimez un instantané du cluster source, l'instantané du cluster cible n'est pas affecté (et inversement).

. Cliquez sur *Protection des données* > *Instantanés*.
. Cliquez sur l'icône *Actions* correspondant à l'instantané que vous souhaitez supprimer.
. Dans le menu qui s'affiche, sélectionnez *Supprimer*.
. Confirmez l'action.

