---
permalink: storage/task_data_manage_vol_access_group_add_a_single_initiator.html 
sidebar: sidebar 
keywords: initiator, add to volume access group, access groups, add single initiator, create initiator 
summary: 'Vous pouvez ajouter un initiateur à un groupe d"accès aux volumes existant.' 
---
= Ajouter un seul initiateur à un groupe d'accès aux volumes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez ajouter un initiateur à un groupe d'accès aux volumes existant.

Lorsque vous ajoutez un initiateur à un groupe d'accès aux volumes, cet initiateur a accès à tous les volumes de ce groupe.


TIP: Vous pouvez trouver l'initiateur de chaque volume en cliquant sur l'icône Actions, puis en sélectionnant *Afficher les détails* pour le volume dans la liste des volumes actifs.

Si vous utilisez CHAP basé sur l'initiateur, vous pouvez ajouter des informations d'identification CHAP pour un seul initiateur dans un groupe d'accès aux volumes, ce qui renforce la sécurité.  Cela vous permet d'appliquer cette option aux groupes d'accès aux volumes qui existent déjà.

.Étapes
. Cliquez sur *Gestion* > *Groupes d'accès*.
. Cliquez sur l'icône *Actions* du groupe d'accès que vous souhaitez modifier.
. Cliquez sur *Modifier*.
. Pour ajouter un initiateur Fibre Channel au groupe d'accès au volume, procédez comme suit :
+
.. Sous Ajouter des initiateurs, sélectionnez un initiateur Fibre Channel existant dans la liste *Initiateurs Fibre Channel non liés*.
.. Cliquez sur *Ajouter un initiateur FC*.
+

NOTE: Vous pouvez créer un initiateur au cours de cette étape si vous cliquez sur le lien *Créer un initiateur*, saisissez un nom d'initiateur et cliquez sur *Créer*.  Le système ajoute automatiquement l'initiateur à la liste *Initiateurs* après sa création.

+
Voici un exemple de format :



+
[listing]
----
5f:47:ac:c0:5c:74:d4:02
----
. Pour ajouter un initiateur iSCSI au groupe d'accès au volume, sous Ajouter des initiateurs, sélectionnez un initiateur existant dans la liste *Initiateurs*.
+

NOTE: Vous pouvez créer un initiateur au cours de cette étape si vous cliquez sur le lien *Créer un initiateur*, saisissez un nom d'initiateur et cliquez sur *Créer*.  Le système ajoute automatiquement l'initiateur à la liste *Initiateurs* après sa création.

+
Le format accepté d'un IQN d'initiateur est le suivant : iqn.yyyy-mm, dans lequel y et m sont des chiffres, suivis d'un texte qui ne doit contenir que des chiffres, des caractères alphabétiques minuscules, un point (.), deux-points (:) ou un tiret (-).

+
Voici un exemple de format :

+
[listing]
----
iqn.2010-01.com.solidfire:c2r9.fc0.2100000e1e09bb8b
----
+

TIP: Vous pouvez trouver l'IQN de l'initiateur pour chaque volume sur la page *Gestion* > *Volumes* Volumes actifs en cliquant sur l'icône Actions puis en sélectionnant *Afficher les détails* pour le volume.

. Cliquez sur *Enregistrer les modifications*.

