---
permalink: storage/task_snapmirror_transfer_or_one_time_migration_from_ontap_to_element.html 
sidebar: sidebar 
keywords: element, ui, transfer, perform, source, volume, snapmirror, dr, disaster, recovery, one-time, migration 
summary: 'En règle générale, lorsque vous utilisez SnapMirror pour la reprise après sinistre d"un cluster de stockage SolidFire exécutant le logiciel NetApp Element vers le logiciel ONTAP , Element est la source et ONTAP la destination.  Cependant, dans certains cas, le système de stockage ONTAP peut servir de source et Element de destination.' 
---
= Effectuez un transfert ou une migration ponctuelle d' ONTAP vers Element.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
En règle générale, lorsque vous utilisez SnapMirror pour la reprise après sinistre d'un cluster de stockage SolidFire exécutant le logiciel NetApp Element vers le logiciel ONTAP , Element est la source et ONTAP la destination.  Cependant, dans certains cas, le système de stockage ONTAP peut servir de source et Element de destination.

* Deux scénarios sont possibles :
+
** Il n'existe aucune relation antérieure en matière de reprise après sinistre.  Suivez toutes les étapes de cette procédure.
** Il existe bien une relation de reprise après sinistre antérieure, mais pas entre les volumes utilisés pour cette atténuation.  Dans ce cas, suivez uniquement les étapes 3 et 4 ci-dessous.




.Ce dont vous aurez besoin
* Le nœud de destination de l'élément doit avoir été rendu accessible à ONTAP.
* Le volume Element doit avoir été activé pour la réplication SnapMirror .


Vous devez spécifier le chemin de destination de l'élément sous la forme hostip:/lun/<id_number>, où lun est la chaîne de caractères "`lun`" et id_number est l'ID du volume de l'élément.

.Étapes
. À l'aide d' ONTAP, créez la relation avec le cluster Element :
+
[listing]
----
snapmirror create -source-path SVM:volume|cluster://SVM/volume
-destination-path hostip:/lun/name -type XDP -schedule schedule -policy
    policy
----
+
[listing]
----
cluster_dst::> snapmirror create -source-path svm_1:volA_dst
-destination-path 10.0.0.11:/lun/0005 -type XDP -schedule my_daily -policy MirrorLatest
----
. Vérifiez que la relation SnapMirror a été créée à l'aide de la commande ONTAP snapmirror show.
+
Consultez la documentation ONTAP pour obtenir des informations sur la création d'une relation de réplication et la page de manuel ONTAP pour connaître la syntaxe complète des commandes.

. En utilisant le `ElementCreateVolume` API, créez le volume cible et définissez le mode d'accès au volume cible sur SnapMirror:
+
Créez un volume Element à l'aide de l'API Element.

+
[listing]
----
{
   "method": "CreateVolume",
   "params": {
        "name": "SMTargetVolumeTest2",
        "accountID": 1,
        "totalSize": 100000000000,
        "enable512e": true,
        "attributes": {},
        "qosPolicyID": 1,
        "enableSnapMirrorReplication": true,
        "access": "snapMirrorTarget"
    },
    "id": 1
}
----
. Initialisez la relation de réplication à l'aide d' ONTAP `snapmirror initialize` commande:
+
[listing]
----
snapmirror initialize -source-path hostip:/lun/name
-destination-path SVM:volume|cluster://SVM/volume
----

