---
permalink: storage/task_data_protection_roll_back_a_volume_to_a_snapshot.html 
sidebar: sidebar 
keywords: volume to snapshot roll back, snapshot roll back, revert changes 
summary: 'Vous pouvez restaurer un volume à un instantané précédent à tout moment.  Cette opération annule toutes les modifications apportées au volume depuis la création de l"instantané.' 
---
= Restaurer un volume à un instantané
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez restaurer un volume à un instantané précédent à tout moment.  Cette opération annule toutes les modifications apportées au volume depuis la création de l'instantané.

.Étapes
. Cliquez sur *Protection des données* > *Instantanés*.
. Cliquez sur l'icône *Actions* correspondant à l'instantané que vous souhaitez utiliser pour la restauration du volume.
. Dans le menu qui s'affiche, sélectionnez *Restaurer le volume à l'instantané*.
. *Facultatif :* Pour enregistrer l’état actuel du volume avant de revenir à l’instantané :
+
.. Dans la boîte de dialogue *Restaurer à partir d'un instantané*, sélectionnez *Enregistrer l'état actuel du volume sous forme d'instantané*.
.. Saisissez un nom pour le nouveau snapshot.


. Cliquez sur *Restaurer l'instantané*.

