---
permalink: storage/task_data_manage_vol_access_group_delete_an_initiator.html 
sidebar: sidebar 
keywords: initiator delete, deleted multiple initiators 
summary: 'Vous pouvez supprimer un initiateur lorsqu"il n"est plus nécessaire.  Lorsque vous supprimez un initiateur, le système le retire de tout groupe d"accès aux volumes associé.  Toute connexion utilisant l"initiateur reste valide jusqu"à sa réinitialisation.' 
---
= Supprimer un initiateur
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez supprimer un initiateur lorsqu'il n'est plus nécessaire.  Lorsque vous supprimez un initiateur, le système le retire de tout groupe d'accès aux volumes associé.  Toute connexion utilisant l'initiateur reste valide jusqu'à sa réinitialisation.

.Étapes
. Cliquez sur *Gestion* > *Initiateurs*.
. Suivez les étapes pour supprimer un ou plusieurs initiateurs :
+
[cols="25,75"]
|===
| Option | Étapes 


 a| 
Supprimer l'initiateur unique
 a| 
.. Cliquez sur l'icône *Actions* correspondant à l'initiateur que vous souhaitez supprimer.
.. Cliquez sur *Supprimer*.
.. Confirmez l'action.




 a| 
Supprimer plusieurs initiateurs
 a| 
.. Cochez les cases correspondant aux initiateurs que vous souhaitez supprimer.
.. Cliquez sur le bouton *Actions groupées*.
.. Dans le menu qui s'affiche, sélectionnez *Supprimer*.
.. Confirmez l'action.


|===

