---
permalink: storage/task_monitor_volume_performance.html 
sidebar: sidebar 
keywords: volume performance, view, view alerts 
summary: 'Vous pouvez consulter des informations détaillées sur les performances de tous les volumes du cluster.  Vous pouvez trier les informations par ID de volume ou par n"importe quelle colonne de performance.  Vous pouvez également filtrer les informations selon certains critères.' 
---
= Afficher les performances en volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez consulter des informations détaillées sur les performances de tous les volumes du cluster.  Vous pouvez trier les informations par ID de volume ou par n'importe quelle colonne de performance.  Vous pouvez également filtrer les informations selon certains critères.

Vous pouvez modifier la fréquence d'actualisation des informations de performance sur la page en cliquant sur la liste *Actualiser toutes les* et en choisissant une valeur différente.  L'intervalle d'actualisation par défaut est de 10 secondes si le cluster comporte moins de 1000 volumes ; sinon, la valeur par défaut est de 60 secondes.  Si vous choisissez la valeur « Jamais », l'actualisation automatique de la page est désactivée.

Vous pouvez réactiver l'actualisation automatique en cliquant sur *Activer l'actualisation automatique*.

. Dans l'interface utilisateur d'Element, sélectionnez *Rapports* > *Performances du volume*.
. Dans la liste des volumes, cliquez sur l'icône Actions correspondant à un volume.
. Cliquez sur *Afficher les détails*.
+
Un encadré contenant des informations générales sur le volume est affiché en bas de la page.

. Pour obtenir des informations plus détaillées sur le volume, cliquez sur *Voir plus de détails*.
+
Le système affiche des informations détaillées ainsi que des graphiques de performance pour le volume.





== Trouver plus d'informations

xref:reference_monitor_volume_performance_details.adoc[Détails des performances du volume]
