---
permalink: storage/task_data_protection_back_up_volume_to_amazon_s3.html 
sidebar: sidebar 
keywords: volume backup, amazon s3 object store 
summary: 'Vous pouvez sauvegarder des volumes sur des supports de stockage d"objets externes compatibles avec Amazon S3.' 
---
= Sauvegardez un volume sur un stockage d'objets Amazon S3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez sauvegarder des volumes sur des supports de stockage d'objets externes compatibles avec Amazon S3.

. Cliquez sur *Gestion* > *Volumes*.
. Cliquez sur l'icône Actions correspondant au volume que vous souhaitez sauvegarder.
. Dans le menu qui apparaît, cliquez sur *Sauvegarder vers*.
. Dans la boîte de dialogue *Sauvegarde intégrée*, sous *Sauvegarder vers*, sélectionnez *S3*.
. Sélectionnez une option sous *Format des données* :
+
** *Natif* : Un format compressé lisible uniquement par les systèmes de stockage SolidFire .
** *Non compressé* : Un format non compressé compatible avec d’autres systèmes.


. Saisissez un nom d'hôte à utiliser pour accéder au stockage d'objets dans le champ *Nom d'hôte*.
. Saisissez un identifiant de clé d'accès pour le compte dans le champ *Identifiant de clé d'accès*.
. Saisissez la clé d'accès secrète du compte dans le champ *Clé d'accès secrète*.
. Saisissez le compartiment S3 dans lequel stocker la sauvegarde dans le champ *Compartiment S3*.
. Saisissez un nom à ajouter au préfixe dans le champ *Nom*.
. Cliquez sur *Commencer la lecture*.

