---
permalink: storage/task_replication_create_a_target_volume_with_read_write_access.html 
sidebar: sidebar 
keywords: target volume, create, read, write access 
summary: 'Le processus de réplication comprend deux points d"extrémité : le volume source et le volume cible.  Lorsque vous créez le volume cible, celui-ci est automatiquement configuré en mode lecture/écriture pour accepter les données lors de la réplication.' 
---
= Créez un volume cible avec accès en lecture ou en écriture
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le processus de réplication comprend deux points d'extrémité : le volume source et le volume cible.  Lorsque vous créez le volume cible, celui-ci est automatiquement configuré en mode lecture/écriture pour accepter les données lors de la réplication.

. Sélectionnez *Gestion* > *Volumes*.
. Cliquez sur *Créer un volume*.
. Dans la boîte de dialogue Créer un nouveau volume, saisissez le nom du volume.
. Saisissez la taille totale du volume, sélectionnez une taille de bloc pour le volume et sélectionnez le compte qui doit avoir accès au volume.
. Cliquez sur *Créer un volume*.
. Dans la fenêtre active, cliquez sur l'icône Actions du volume.
. Cliquez sur *Modifier*.
. Modifiez le niveau d'accès du compte en Cible de réplication.
. Cliquez sur *Enregistrer les modifications*.

