---
permalink: storage/task_data_manage_vol_access_group_view_individual_access_group_details.html 
sidebar: sidebar 
keywords: access group details, view, view details, initiators 
summary: 'Vous pouvez consulter les détails d"un groupe d"accès individuel, tels que les volumes et les initiateurs associés, sous forme graphique.' 
---
= Afficher les détails du groupe d'accès individuel
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez consulter les détails d'un groupe d'accès individuel, tels que les volumes et les initiateurs associés, sous forme graphique.

. Cliquez sur *Gestion* > *Groupes d'accès*.
. Cliquez sur l'icône Actions pour un groupe d'accès.
. Cliquez sur *Afficher les détails*.




== Détails du groupe d'accès au volume

La page Groupes d'accès de l'onglet Gestion fournit des informations sur les groupes d'accès aux volumes.

Les informations suivantes sont affichées :

* *ID* : L’identifiant généré par le système pour le groupe d’accès.
* *Nom* : Le nom donné au groupe d’accès lors de sa création.
* *Volumes actifs* : Le nombre de volumes actifs dans le groupe d’accès.
* *Compression* : Score d’efficacité de compression pour le groupe d’accès.
* *Déduplication* : Score d’efficacité de la déduplication pour le groupe d’accès.
* *Provisionnement fin* : Score d’efficacité du provisionnement fin pour le groupe d’accès.
* *Efficacité globale* : Score d'efficacité globale du groupe d'accès.
* *Initiateurs* : Le nombre d’initiateurs connectés au groupe d’accès.

