---
permalink: storage/task_data_protection_clone_multiple_volumes_from_a_group_snapshot.html 
sidebar: sidebar 
keywords: multiple volumes, group snapshot, clone, create, data protection 
summary: 'Vous pouvez cloner un groupe de volumes à partir d"un instantané de groupe à un instant donné.  Cette opération nécessite qu"un instantané de groupe des volumes existe déjà, car cet instantané de groupe sert de base à la création des volumes.  Une fois les volumes créés, vous pouvez les utiliser comme n"importe quel autre volume du système.' 
---
= Clonage de plusieurs volumes à partir d'un instantané de groupe
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez cloner un groupe de volumes à partir d'un instantané de groupe à un instant donné.  Cette opération nécessite qu'un instantané de groupe des volumes existe déjà, car cet instantané de groupe sert de base à la création des volumes.  Une fois les volumes créés, vous pouvez les utiliser comme n'importe quel autre volume du système.

La taille du volume et la charge actuelle du cluster influent sur le temps nécessaire pour effectuer une opération de clonage.

. Cliquez sur *Protection des données* > *Instantanés de groupe*.
. Cliquez sur l'icône Actions correspondant à l'instantané de groupe que vous souhaitez utiliser pour les clones de volume.
. Dans le menu qui s'affiche, sélectionnez *Cloner les volumes à partir d'un instantané de groupe*.
. Saisissez un *préfixe de nom de nouveau volume* dans la boîte de dialogue *Cloner les volumes à partir d'un instantané de groupe*.
+
Le préfixe est appliqué à tous les volumes créés à partir de l'instantané de groupe.

. *Facultatif :* Sélectionnez un autre compte auquel le clone appartiendra.
+
Si vous ne sélectionnez pas de compte, le système attribue les nouveaux volumes au compte de volumes actuel.

. *Facultatif :* Sélectionnez une autre méthode d’accès pour les volumes du clone.
+
Si vous ne sélectionnez pas de méthode d'accès, le système utilise l'accès au volume actuel.

. Cliquez sur *Démarrer le clonage*.

