---
permalink: storage/task_data_protection_back_up_a_volume_snapshot_to_openstack_swift.html 
sidebar: sidebar 
keywords: volume snapshot, backup, openstack swift S3 object store 
summary: 'Vous pouvez sauvegarder les instantanés SolidFire sur des supports de stockage d"objets secondaires compatibles avec OpenStack Swift.' 
---
= Sauvegardez un instantané de volume sur un stockage d'objets OpenStack Swift
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez sauvegarder les instantanés SolidFire sur des supports de stockage d'objets secondaires compatibles avec OpenStack Swift.

. Cliquez sur *Protection des données* > *Instantanés*.
. Cliquez sur l'icône *Actions* correspondant à l'instantané que vous souhaitez sauvegarder.
. Dans le menu qui apparaît, cliquez sur *Sauvegarder vers*.
. Dans la boîte de dialogue *Sauvegarde intégrée*, sous *Sauvegarder vers*, sélectionnez *Swift*.
. Sélectionnez une option sous *Format des données* :
+
** *Natif* : Un format compressé lisible uniquement par les systèmes de stockage SolidFire .
** *Non compressé* : Un format non compressé compatible avec d’autres systèmes.


. Saisissez une *URL* pour accéder au magasin d'objets.
. Veuillez saisir un *nom d'utilisateur* pour le compte.
. Saisissez la *clé d'authentification* du compte.
. Saisissez le *conteneur* dans lequel stocker la sauvegarde.
. *Facultatif* : Saisissez un *nom*.
. Cliquez sur *Commencer la lecture*.

