---
permalink: storage/task_data_protection_use_group_snapshots_for_data_protection.html 
sidebar: sidebar 
keywords: group snapshots, data protection, set of volumes, backup, rollback 
summary: 'Vous pouvez créer un instantané de groupe d"un ensemble de volumes liés afin de préserver une copie à un instant donné des métadonnées de chaque volume.  Vous pourrez utiliser ultérieurement l"instantané de groupe comme sauvegarde ou restauration pour rétablir l"état du groupe de volumes à un état antérieur.' 
---
= Utilisation des instantanés de groupe pour la tâche de protection des données
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez créer un instantané de groupe d'un ensemble de volumes liés afin de préserver une copie à un instant donné des métadonnées de chaque volume.  Vous pourrez utiliser ultérieurement l'instantané de groupe comme sauvegarde ou restauration pour rétablir l'état du groupe de volumes à un état antérieur.



== Trouver plus d'informations

* xref:task_data_protection_create_a_group_snapshot.adoc[Créer un instantané de groupe]
* xref:task_data_protection_edit_group_snapshots.adoc[Modifier les instantanés de groupe]
* xref:task_data_protection_edit_members_of_group_snapshot.adoc[Modifier les membres du groupe (instantané)]
* xref:task_data_protection_delete_a_group_snapshot.adoc[Supprimer un instantané de groupe]
* xref:task_data_protection_roll_back_volumes_to_a_group_snapshot.adoc[Restaurez les volumes à partir d'un instantané de groupe]
* xref:task_data_protection_clone_multiple_volumes.adoc[Cloner plusieurs volumes]
* xref:task_data_protection_clone_multiple_volumes_from_a_group_snapshot.adoc[Cloner plusieurs volumes à partir d'un snapshot de groupe]

