---
permalink: storage/task_data_protection_restore_volume_from_backup_on_amazon_s3.html 
sidebar: sidebar 
keywords: volume restore, amazon s3 object store 
summary: 'Vous pouvez restaurer un volume à partir d"une sauvegarde sur un stockage d"objets Amazon S3.' 
---
= Restaurez un volume à partir d'une sauvegarde sur un stockage d'objets Amazon S3.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez restaurer un volume à partir d'une sauvegarde sur un stockage d'objets Amazon S3.

. Cliquez sur *Rapports* > *Journal des événements*.
. Localisez l'événement de sauvegarde qui a créé la sauvegarde que vous devez restaurer.
. Dans la colonne *Détails* de l'événement, cliquez sur *Afficher les détails*.
. Copiez les informations du manifeste dans votre presse-papiers.
. Cliquez sur *Gestion* > *Volumes*.
. Cliquez sur l'icône Actions correspondant au volume que vous souhaitez restaurer.
. Dans le menu qui s'affiche, cliquez sur *Restaurer à partir de*.
. Dans la boîte de dialogue *Restauration intégrée*, sous *Restaurer à partir de*, sélectionnez *S3*.
. Sélectionnez l'option correspondant à la sauvegarde sous *Format des données* :
+
** *Natif* : Un format compressé lisible uniquement par les systèmes de stockage SolidFire .
** *Non compressé* : Un format non compressé compatible avec d’autres systèmes.


. Saisissez un nom d'hôte à utiliser pour accéder au stockage d'objets dans le champ *Nom d'hôte*.
. Saisissez un identifiant de clé d'accès pour le compte dans le champ *Identifiant de clé d'accès*.
. Saisissez la clé d'accès secrète du compte dans le champ *Clé d'accès secrète*.
. Saisissez le compartiment S3 dans lequel stocker la sauvegarde dans le champ *Compartiment S3*.
. Collez les informations du manifeste dans le champ *Manifeste*.
. Cliquez sur *Commencer à écrire*.

