---
permalink: storage/task_intro_sort_lists.html 
sidebar: sidebar 
keywords: sort lists, sorting on a single column, sorting on multiple columns, sort button, column selections, using sort criteria 
summary: 'Vous pouvez trier les informations de la liste selon un ou plusieurs critères sur certaines pages de l"interface utilisateur Element.  Cela vous permet d"organiser les informations dont vous avez besoin à l"écran.' 
---
= Listes de tri
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez trier les informations de la liste selon un ou plusieurs critères sur certaines pages de l'interface utilisateur Element.  Cela vous permet d'organiser les informations dont vous avez besoin à l'écran.

. Pour trier selon une seule colonne, cliquez sur l'en-tête de la colonne jusqu'à ce que les informations soient triées dans l'ordre souhaité.
. Pour trier selon plusieurs colonnes, cliquez sur l'en-tête de chaque colonne selon laquelle vous souhaitez trier, jusqu'à ce que les informations de chaque colonne soient triées dans l'ordre souhaité.
+
Le bouton Trier apparaît lorsque vous effectuez un tri à l'aide de plusieurs colonnes.

. Pour réorganiser les critères de tri, procédez comme suit :
+
.. Cliquez sur *Trier*.
+
Le système remplit le champ « Trier par » avec vos sélections de colonnes.

.. Disposez les colonnes du champ Trier par dans l'ordre où vous souhaitez que la liste soit triée.
+
Le système trie les informations de la liste.



. Pour supprimer un critère de tri, cliquez sur l'icône *Supprimer* située à côté du nom du critère.
. Pour supprimer tous les critères de tri, cliquez sur *Tout effacer*.

