---
permalink: storage/task_data_protection_restore_volume_from_backup_on_openstack_swift.html 
sidebar: sidebar 
keywords: volume restore, openstack swift object store 
summary: 'Vous pouvez restaurer un volume à partir d"une sauvegarde sur un stockage d"objets OpenStack Swift.' 
---
= Restaurez un volume à partir d'une sauvegarde sur un magasin d'objets OpenStack Swift
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez restaurer un volume à partir d'une sauvegarde sur un stockage d'objets OpenStack Swift.

. Cliquez sur *Rapports* > *Journal des événements*.
. Localisez l'événement de sauvegarde qui a créé la sauvegarde que vous devez restaurer.
. Dans la colonne *Détails* de l'événement, cliquez sur *Afficher les détails*.
. Copiez les informations du manifeste dans votre presse-papiers.
. Cliquez sur *Gestion* > *Volumes*.
. Cliquez sur l'icône Actions correspondant au volume que vous souhaitez restaurer.
. Dans le menu qui s'affiche, cliquez sur *Restaurer à partir de*.
. Dans la boîte de dialogue *Restauration intégrée*, sous *Restaurer à partir de*, sélectionnez *Swift*.
. Sélectionnez l'option correspondant à la sauvegarde sous *Format des données* :
+
** *Natif* : Un format compressé lisible uniquement par les systèmes de stockage SolidFire .
** *Non compressé* : Un format non compressé compatible avec d’autres systèmes.


. Saisissez une URL dans le champ *URL* pour accéder au magasin d'objets.
. Veuillez saisir un nom d'utilisateur pour le compte dans le champ *Nom d'utilisateur*.
. Saisissez la clé d'authentification du compte dans le champ *Clé d'authentification*.
. Saisissez le nom du conteneur dans lequel la sauvegarde est stockée dans le champ *Conteneur*.
. Collez les informations du manifeste dans le champ *Manifeste*.
. Cliquez sur *Commencer à écrire*.

