---
permalink: storage/task_system_manage_virtual_enable_virtual_routing_and_forwarding.html 
sidebar: sidebar 
keywords: virtual routing, forwarding, enable, vrf, storage networks, create a vlan 
summary: 'Vous pouvez activer le routage et le transfert virtuels (VRF), ce qui permet à plusieurs instances d"une table de routage d"exister dans un routeur et de fonctionner simultanément.  Cette fonctionnalité est disponible uniquement pour les réseaux de stockage.' 
---
= Activer le routage et le transfert virtuels
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez activer le routage et le transfert virtuels (VRF), ce qui permet à plusieurs instances d'une table de routage d'exister dans un routeur et de fonctionner simultanément.  Cette fonctionnalité est disponible uniquement pour les réseaux de stockage.

Vous ne pouvez activer VRF qu'au moment de la création d'un VLAN.  Si vous souhaitez revenir à un mode non-VRF, vous devez supprimer puis recréer le VLAN.

. Cliquez sur *Cluster* > *Réseau*.
. Pour activer VRF sur un nouveau VLAN, sélectionnez *Créer un VLAN*.
+
.. Saisissez les informations pertinentes pour le nouveau VRF/VLAN.  Voir Ajout d'un réseau virtuel.
.. Cochez la case *Activer le VRF*.
.. *Facultatif* : Saisissez une passerelle.


. Cliquez sur *Créer un VLAN*.




== Trouver plus d'informations

xref:task_system_manage_virtual_add_a_virtual_network.adoc[Ajouter un réseau virtuel]
