---
permalink: storage/task_data_protection_back_up_volume_to_openstack_swift.html 
sidebar: sidebar 
keywords: volume backup, openstack swift object store 
summary: 'Vous pouvez sauvegarder des volumes sur des supports de stockage d"objets externes compatibles avec OpenStack Swift.' 
---
= Sauvegarder un volume sur un stockage d'objets OpenStack Swift
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez sauvegarder des volumes sur des supports de stockage d'objets externes compatibles avec OpenStack Swift.

. Cliquez sur *Gestion* > *Volumes*.
. Cliquez sur l'icône Actions pour rétablir le volume.
. Dans le menu qui apparaît, cliquez sur *Sauvegarder vers*.
. Dans la boîte de dialogue *Sauvegarde intégrée*, sous *Sauvegarder vers*, sélectionnez *Swift*.
. Sélectionnez un format de données sous *Format des données* :
+
** *Natif* : Un format compressé lisible uniquement par les systèmes de stockage SolidFire .
** *Non compressé* : Un format non compressé compatible avec d’autres systèmes.


. Saisissez une URL dans le champ *URL* pour accéder au magasin d'objets.
. Veuillez saisir un nom d'utilisateur pour le compte dans le champ *Nom d'utilisateur*.
. Saisissez la clé d'authentification du compte dans le champ *Clé d'authentification*.
. Saisissez le conteneur dans lequel stocker la sauvegarde dans le champ *Conteneur*.
. *Facultatif* : Saisissez un nom à ajouter au préfixe dans le champ *Nom*.
. Cliquez sur *Commencer la lecture*.

