---
permalink: setup/task_setup_configure_fqdn_web_ui_access.html 
sidebar: sidebar 
keywords: netapp, element, fqdn, ui, access, web, administration 
summary: 'Apprenez à configurer, supprimer et dépanner l"accès à l"interface utilisateur Web de votre nom de domaine complet (FQDN).' 
---
= Configurer l'accès à l'interface web du nom de domaine pleinement qualifié
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le stockage tout flash SolidFire avec le logiciel NetApp Element 12.2 ou ultérieur vous permet d'accéder aux interfaces Web du cluster de stockage à l'aide du nom de domaine pleinement qualifié (FQDN).  Si vous souhaitez utiliser le nom de domaine complet (FQDN) pour accéder aux interfaces utilisateur Web telles que l'interface utilisateur Web Element, l'interface utilisateur par nœud ou l'interface utilisateur du nœud de gestion, vous devez d'abord ajouter un paramètre de cluster de stockage pour identifier le FQDN utilisé par le cluster.

Ce processus permet au cluster de rediriger correctement une session de connexion et améliore l'intégration avec des services externes tels que les gestionnaires de clés et les fournisseurs d'identité pour l'authentification multifacteurs.

.Ce dont vous aurez besoin
* Cette fonctionnalité nécessite Element 12.2 ou une version ultérieure.
* La configuration de cette fonctionnalité à l'aide des API REST de NetApp Hybrid Cloud Control nécessite les services de gestion 2.15 ou une version ultérieure.
* La configuration de cette fonctionnalité à l'aide de l'interface utilisateur de NetApp Hybrid Cloud Control nécessite les services de gestion 2.19 ou une version ultérieure.
* Pour utiliser les API REST, vous devez avoir déployé un nœud de gestion exécutant la version 11.5 ou ultérieure.
* Vous avez besoin de noms de domaine entièrement qualifiés pour le nœud de gestion et chaque cluster de stockage, qui doivent correspondre correctement à l'adresse IP du nœud de gestion et à l'adresse IP de chaque cluster de stockage.


Vous pouvez configurer ou supprimer l'accès à l'interface utilisateur Web FQDN à l'aide de NetApp Hybrid Cloud Control et de l'API REST.  Vous pouvez également dépanner les noms de domaine pleinement qualifiés (FQDN) mal configurés.

* <<Configurer l'accès à l'interface utilisateur Web FQDN à l'aide de NetApp Hybrid Cloud Control>>
* <<Configurer l'accès à l'interface utilisateur Web du nom de domaine complet (FQDN) à l'aide de l'API REST>>
* <<Supprimer l'accès à l'interface utilisateur Web FQDN à l'aide de NetApp Hybrid Cloud Control>>
* <<Supprimer l'accès à l'interface utilisateur Web FQDN via l'API REST>>
* <<Dépannage>>




== Configurer l'accès à l'interface utilisateur Web FQDN à l'aide de NetApp Hybrid Cloud Control

.Étapes
. Ouvrez l'adresse IP du nœud de gestion dans un navigateur Web :
+
[listing]
----
https://<ManagementNodeIP>
----
. Connectez-vous à NetApp Hybrid Cloud Control en fournissant les identifiants de l'administrateur du cluster de stockage.
. Sélectionnez l'icône de menu en haut à droite de la page.
. Sélectionnez *Configurer*.
. Dans le volet *Noms de domaine pleinement qualifiés*, sélectionnez *Configurer*.
. Dans la fenêtre qui s'affiche, saisissez les noms de domaine complets (FQDN) du nœud de gestion et de chaque cluster de stockage.
. Sélectionnez *Enregistrer*.
+
Le volet *Noms de domaine pleinement qualifiés* répertorie chaque cluster de stockage avec son MVIP et son FQDN associés.

+

NOTE: Seuls les clusters de stockage connectés avec le nom de domaine pleinement qualifié (FQDN) défini sont répertoriés dans le volet *Noms de domaine pleinement qualifiés*.





== Configurer l'accès à l'interface utilisateur Web du nom de domaine complet (FQDN) à l'aide de l'API REST

.Étapes
. Assurez-vous que les nœuds de stockage Element et le mNode disposent d'une configuration DNS correcte pour l'environnement réseau afin que les noms de domaine pleinement qualifiés (FQDN) de l'environnement puissent être résolus.  Pour configurer le DNS, accédez à l'interface utilisateur par nœud pour les nœuds de stockage et au nœud de gestion, puis sélectionnez *Paramètres réseau* > *Réseau de gestion*.
+
.. Interface utilisateur par nœud pour les nœuds de stockage : `https://<storage_node_management_IP>:442`
.. Interface utilisateur par nœud pour le nœud de gestion : `https://<management_node_IP>:442`


. Modifiez les paramètres du cluster de stockage à l'aide de l'API Element.
+
.. Accédez à l'API Element et créez la préférence d'interface de cluster suivante à l'aide delink:../api/reference_element_api_createclusterinterfacepreference.html["Préférence de création d'interface de cluster"] Méthode API, insertion du nom de domaine complet MVIP du cluster pour la valeur de préférence :
+
*** Nom: `mvip_fqdn`
*** Valeur: `Fully Qualified Domain Name for the Cluster MVIP`
+
Dans cet exemple, FQDN=storagecluster.my.org :

+
[listing]
----
https://<Cluster_MVIP>/json-rpc/12.2?
method=CreateClusterInterfacePreference&name=mvip_fqdn&value=storagecluster.my.org
----




. Modifiez les paramètres du nœud de gestion à l'aide de l'API REST sur le nœud de gestion :
+
.. Accédez à l'interface utilisateur de l'API REST du nœud de gestion en saisissant l'adresse IP du nœud de gestion suivie de `/mnode/2/`
+
Par exemple:

+
`https://<management_node_IP>/mnode/2/`

.. Cliquez sur *Autoriser* ou sur n'importe quelle icône de verrouillage et saisissez le nom d'utilisateur et le mot de passe du cluster.
.. Saisissez l'identifiant du client comme `mnode-client` .
.. Cliquez sur *Autoriser* pour démarrer la session, puis fermez la fenêtre.
.. Dans la liste des serveurs, sélectionnez `mnode2` .
.. Cliquez sur *OBTENIR /paramètres*.
.. Cliquez sur *Essayer*.
.. Cliquez sur *Exécuter*.
.. Consignez tous les paramètres de proxy signalés dans le corps de la réponse.
.. Cliquez sur *PUT/paramètres*.
.. Cliquez sur *Essayer*.
.. Dans le corps de la requête, saisissez le nom de domaine complet (FQDN) du nœud de gestion comme valeur pour le `mnode_fqdn` paramètre.
.. Saisissez les valeurs de configuration du proxy que vous avez enregistrées précédemment dans les paramètres restants du corps de la requête.  Si vous laissez les paramètres du proxy vides ou si vous ne les incluez pas dans le corps de la requête, les paramètres de proxy existants seront supprimés.
.. Cliquez sur *Exécuter*.






== Supprimer l'accès à l'interface utilisateur Web FQDN à l'aide de NetApp Hybrid Cloud Control

Vous pouvez utiliser cette procédure pour supprimer l'accès Web FQDN pour le nœud de gestion et les clusters de stockage.

.Étapes
. Dans le volet *Noms de domaine pleinement qualifiés*, sélectionnez *Modifier*.
. Dans la fenêtre qui s'affiche, supprimez le contenu du champ de texte *FQDN*.
. Sélectionnez *Enregistrer*.
+
La fenêtre se ferme et le nom de domaine pleinement qualifié (FQDN) n'apparaît plus dans le volet *Noms de domaine pleinement qualifiés*.





== Supprimer l'accès à l'interface utilisateur Web FQDN via l'API REST

.Étapes
. Modifiez les paramètres du cluster de stockage à l'aide de l'API Element.
+
.. Accédez à l'API Element et supprimez la préférence d'interface de cluster suivante à l'aide de `DeleteClusterInterfacePreference` Méthode API :
+
*** Nom: `mvip_fqdn`
+
Par exemple:

+
[listing]
----
https://<Cluster_MVIP>/json-rpc/12.2?method=DeleteClusterInterfacePreference&name=mvip_fqdn
----




. Modifiez les paramètres du nœud de gestion à l'aide de l'API REST sur le nœud de gestion :
+
.. Accédez à l'interface utilisateur de l'API REST du nœud de gestion en saisissant l'adresse IP du nœud de gestion suivie de `/mnode/2/` . Par exemple:
+
[listing]
----
https://<management_node_IP>/mnode/2/
----
.. Sélectionnez *Autoriser* ou toute icône de verrouillage et saisissez le nom d'utilisateur et le mot de passe du cluster Element.
.. Saisissez l'identifiant du client comme `mnode-client` .
.. Sélectionnez *Autoriser* pour démarrer une session.
.. Ferme la fenêtre.
.. Sélectionnez *PUT /settings*.
.. Sélectionnez *Essayer*.
.. Dans le corps de la requête, ne saisissez aucune valeur pour le `mnode_fqdn` paramètre.  Veuillez également préciser si le proxy doit être utilisé.(`true` ou `false` ) pour le `use_proxy` paramètre.
+
[listing]
----
{
 "mnode_fqdn": "",
 "use_proxy": false
}
----
.. Sélectionnez *Exécuter*.






== Dépannage

Si les noms de domaine pleinement qualifiés (FQDN) sont mal configurés, vous pourriez rencontrer des problèmes d'accès au nœud de gestion, à un cluster de stockage, ou aux deux.  Utilisez les informations suivantes pour vous aider à résoudre le problème.

[cols="3*"]
|===
| Problème | Cause | Résolution 


 a| 
* Vous obtenez une erreur de navigateur lorsque vous tentez d'accéder au nœud de gestion ou au cluster de stockage à l'aide du nom de domaine complet (FQDN).
* Vous ne pouvez pas vous connecter au nœud de gestion ni au cluster de stockage en utilisant une adresse IP.

| Le nom de domaine complet (FQDN) du nœud de gestion et celui du cluster de stockage sont tous deux mal configurés. | Utilisez les instructions de l'API REST sur cette page pour supprimer les paramètres FQDN du nœud de gestion et du cluster de stockage, puis configurez-les à nouveau. 


 a| 
* Vous obtenez une erreur de navigateur lorsque vous tentez d'accéder au nom de domaine complet (FQDN) du cluster de stockage.
* Vous ne pouvez pas vous connecter au nœud de gestion ni au cluster de stockage en utilisant une adresse IP.

| Le nom de domaine complet (FQDN) du nœud de gestion est correctement configuré, mais le nom de domaine complet (FQDN) du cluster de stockage est incorrectement configuré. | Utilisez les instructions de l'API REST sur cette page pour supprimer les paramètres FQDN du cluster de stockage et les reconfigurer. 


 a| 
* Vous obtenez une erreur de navigateur lorsque vous tentez d'accéder au nom de domaine complet (FQDN) du nœud de gestion.
* Vous pouvez vous connecter au nœud de gestion et au cluster de stockage à l'aide d'une adresse IP.

| Le nom de domaine complet (FQDN) du nœud de gestion est mal configuré, mais le nom de domaine complet (FQDN) du cluster de stockage est correctement configuré. | Connectez-vous à NetApp Hybrid Cloud Control pour corriger les paramètres FQDN du nœud de gestion dans l'interface utilisateur, ou utilisez les instructions de l'API REST sur cette page pour corriger les paramètres. 
|===


== Trouver plus d'informations

* https://docs.netapp.com/us-en/element-software/index.html["Documentation logicielle SolidFire et Element"]
* https://docs.netapp.com/us-en/vcp/index.html["Module d'extension NetApp Element pour vCenter Server"^]

