---
permalink: api/concept_element_api_drive_api_methods.html 
sidebar: sidebar 
keywords: drive,API,methods,method 
summary: 'Vous pouvez utiliser les méthodes de l"API Drive pour ajouter et gérer les disques disponibles pour un cluster de stockage.  Lorsque vous ajoutez un nœud de stockage au cluster de stockage ou que vous installez de nouveaux disques dans un nœud de stockage existant, ces disques peuvent être ajoutés au cluster de stockage.' 
---
= Méthodes de l'API Drive
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser les méthodes de l'API Drive pour ajouter et gérer les disques disponibles pour un cluster de stockage.  Lorsque vous ajoutez un nœud de stockage au cluster de stockage ou que vous installez de nouveaux disques dans un nœud de stockage existant, ces disques peuvent être ajoutés au cluster de stockage.

* xref:reference_element_api_adddrives.adoc[Ajouter des lecteurs]
* xref:reference_element_api_getdrivehardwareinfo.adoc[GetDriveHardwareInfo]
* xref:reference_element_api_getdrivestats.adoc[GetDriveStats]
* xref:reference_element_api_listdrives.adoc[ListDrives]
* xref:reference_element_api_listdrivestats.adoc[ListDriveStats]
* xref:reference_element_api_removedrives.adoc[Supprimer les lecteurs]
* xref:reference_element_api_secureerasedrives.adoc[SecureEraseDrives]




== Trouver plus d'informations

* https://docs.netapp.com/us-en/element-software/index.html["Documentation logicielle SolidFire et Element"]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["Documentation relative aux versions antérieures des produits NetApp SolidFire et Element"^]

