---
permalink: api/concept_element_api_virtual_network_naming_conventions.html 
sidebar: sidebar 
keywords: storage,system,naming,convention,virtual,network 
summary: Les systèmes de stockage NetApp Element utilisent des nombres croissants de manière monotone comme identifiants uniques pour tous les objets du système. 
---
= Conventions d'appellation des réseaux virtuels
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les systèmes de stockage NetApp Element utilisent des nombres croissants de manière monotone comme identifiants uniques pour tous les objets du système.

Lorsque vous créez un nouveau volume, le nouvel ID de volume est incrémenté de 1 exactement.  Cette convention reste valable pour les réseaux virtuels dans les clusters de stockage exécutant le logiciel Element.  Le premier réseau virtuel que vous créez dans un cluster Element possède un VirtualNetworkID de 1.  Cet identifiant n'est pas la même chose qu'un numéro d'étiquette VLAN.

Vous pouvez utiliser VirtualNetworkID et VirtualNetworkTag (étiquette VLAN) de manière interchangeable lorsque cela est indiqué dans les méthodes de l'API.



== Trouver plus d'informations

* https://docs.netapp.com/us-en/element-software/index.html["Documentation logicielle SolidFire et Element"]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["Documentation relative aux versions antérieures des produits NetApp SolidFire et Element"^]

