---
permalink: api/reference_element_api_startvolumepairing.html 
sidebar: sidebar 
keywords: volume,pair,pairing,start,starting,startvolumepairing 
summary: 'Vous pouvez utiliser la méthode StartVolumePairing pour créer une clé encodée à partir d"un volume qui sera utilisée pour l"appairer avec un autre volume.  La clé créée par cette méthode est utilisée dans la méthode CompleteVolumePairing pour établir un appariement de volumes.' 
---
= Début du couplage de volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `StartVolumePairing` méthode permettant de créer une clé encodée à partir d'un volume utilisé pour l'apparier avec un autre volume.  La clé que cette méthode crée est utilisée dans le `CompleteVolumePairing` méthode pour établir un appariement de volumes.



== Paramètres

Cette méthode possède les paramètres d'entrée suivants :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
mode
 a| 
Le mode du volume sur lequel démarrer le processus d'appairage.  Ce mode ne peut être défini que si le volume correspond au volume source. Valeurs possibles :

* `Async`Les écrits sont pris en compte lorsqu'ils sont finalisés localement.  Le cluster n'attend pas que les écritures soient répliquées sur le cluster cible.  (Valeur par défaut si aucun paramètre de mode n'est spécifié.)
* `Sync`La source confirme l'écriture lorsque les données sont stockées localement et sur le cluster distant.
* `SnapshotsOnly`Seuls les instantanés créés sur le cluster source sont répliqués.  Les écritures actives provenant du volume source ne sont pas répliquées.

 a| 
chaîne
 a| 
Aucune
 a| 
Non



 a| 
volumeID
 a| 
L'identifiant du volume sur lequel démarrer le processus d'appairage.
 a| 
entier
 a| 
Aucune
 a| 
Oui

|===


== valeur de retour

Cette méthode a la valeur de retour suivante :

|===
| Nom | Description | Type 


 a| 
Clé d'appairage du volume
 a| 
Une chaîne de caractères utilisée par lexref:reference_element_api_completevolumepairing.adoc[Appariement complet des volumes] Méthode API.
 a| 
chaîne

|===


== Exemple de demande

Les requêtes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
   "method": "StartVolumePairing",
   "params": {
         "mode": "Async",
	 "volumeID" : 14
      },
   "id" : 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
   "id" : 1,
   "result" : {
      "volumePairingKey" : "7b226d766970223a223139322e3136382e3133392e313232222c22766f6c756d654944223a312c22766f6c756d654e616d65223a2254657374222c22766f6c756d655061697255554944223a2236393632346663622d323032652d343332352d613536392d656339633635356337623561227d"
      }
}
----


== Nouveautés depuis la version

9,6



== Trouver plus d'informations

xref:reference_element_api_completevolumepairing.adoc[Appariement complet des volumes]
