---
permalink: api/reference_element_api_modifysnapmirrorrelationship.html 
sidebar: sidebar 
keywords: modify,modifying,edit,editing,change,changing,snapmirror,relationship,modifysnapmirrorrelationship 
summary: Vous pouvez utiliser ModifySnapMirrorRelationship pour modifier les intervalles auxquels un instantané planifié est effectué.  Vous pouvez également supprimer ou suspendre une planification en utilisant cette méthode. 
---
= ModifierSnapMirrorRelation
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser `ModifySnapMirrorRelationship` modifier les intervalles auxquels un instantané programmé est effectué.  Vous pouvez également supprimer ou suspendre une planification en utilisant cette méthode.



== Paramètres

Cette méthode possède les paramètres d'entrée suivants :

|===


| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
destinationVolume
 a| 
Le volume de destination dans la relation SnapMirror .
 a| 
xref:reference_element_api_snapmirrorvolumeinfo.adoc[snapMirrorVolumeinfo]
 a| 
Aucune
 a| 
Oui



 a| 
taux de transfert maximal
 a| 
Spécifie le débit de transfert de données maximal entre les volumes en kilo-octets par seconde.  La valeur par défaut, 0, est illimitée et permet à la relation SnapMirror d'utiliser pleinement la bande passante réseau disponible.
 a| 
entier
 a| 
Aucune
 a| 
Non



 a| 
Nom de la politique
 a| 
Spécifie le nom de la stratégie ONTAP SnapMirror pour la relation.
 a| 
chaîne
 a| 
Aucune
 a| 
Non



 a| 
nom_de_l'horaire
 a| 
Le nom de la planification cron préexistante sur le système ONTAP qui est utilisée pour mettre à jour la relation SnapMirror .
 a| 
chaîne
 a| 
Aucune
 a| 
Non



 a| 
snapMirrorEndpointID
 a| 
L'identifiant du point de terminaison du système de stockage ONTAP distant communiquant avec le cluster de stockage Element.
 a| 
entier
 a| 
Aucune
 a| 
Oui

|===


== valeur de retour

Cette méthode a la valeur de retour suivante :

|===


| Nom | Description | Type 


 a| 
snapMirrorRelation
 a| 
Un objet contenant les attributs de relation SnapMirror modifiés.
 a| 
xref:reference_element_api_snapmirrorrelationship.adoc[snapMirrorRelation]

|===


== Nouveautés depuis la version

10,1
