---
permalink: api/reference_element_api_getkeyserverkmip.html 
sidebar: sidebar 
keywords: KMIP,key server,getting information,retrieving 
summary: 'Vous pouvez utiliser la méthode GetKeyServerKmip pour obtenir des informations sur le serveur de clés du protocole d"interopérabilité de gestion de clés (KMIP) spécifié.' 
---
= GetKeyServerKmip
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `GetKeyServerKmip` méthode permettant de renvoyer des informations sur le serveur de clés KMIP (Key Management Interoperability Protocol) spécifié.



== Paramètres

Cette méthode possède les paramètres d'entrée suivants :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
ID du serveur de clés
 a| 
L'identifiant du serveur de clés KMIP sur lequel renvoyer des informations.
 a| 
entier
 a| 
Aucune
 a| 
Oui

|===


== Valeurs de retour

Cette méthode renvoie les valeurs suivantes :

|===
| Nom | Description | Type 


 a| 
kmipKeyServer
 a| 
Un objet contenant des informations sur le serveur de clés demandé.
 a| 
link:reference_element_api_keyserverkmip.html["KeyServerKmip"]

|===


== Exemple de demande

Les requêtes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
  "method": "GetKeyServerKmip",
  "params": {
     "keyServerID": 15
  },
"id": 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
   "id": 1,
   "result":
      {
        "kmipKeyServer": {
            "kmipCaCertificate":"MIICPDCCAaUCEDyRMcsf9tAbDpq40ES/E...",
            "kmipKeyServerHostnames":[
                "server1.hostname.com", "server2.hostname.com"
            ],
            "keyProviderID":1,
            "kmipKeyServerName":"keyserverName",
            "keyServerID":15
            "kmipKeyServerPort":1,
            "kmipClientCertificate":"dKkkirWmnWXbj9T/UWZYB2oK0z5...",
            "kmipAssignedProviderIsActive":true
        }
    }
}
----


== Nouveautés depuis la version

11,7
