---
permalink: api/reference_element_api_setclusterconfig.html 
sidebar: sidebar 
keywords: cluster,configuration,set,setting,node,setclusterconfig 
summary: 'Vous pouvez utiliser la méthode SetClusterConfig pour définir la configuration qu"un nœud utilise pour communiquer avec le cluster auquel il est associé.  Pour afficher les paramètres d"interface de cluster actuels d"un nœud, exécutez la méthode API GetClusterConfig.' 
---
= Configurer le cluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `SetClusterConfig` méthode permettant de définir la configuration utilisée par un nœud pour communiquer avec le cluster auquel il est associé.  Pour afficher les paramètres d'interface de cluster actuels d'un nœud, exécutez la commande suivante : `GetClusterConfig` Méthode API.



== Paramètre

Cette méthode possède le paramètre d'entrée suivant :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
grappe
 a| 
Attributs de configuration à modifier lors de cet appel de méthode.  Seuls les champs que vous souhaitez modifier doivent être ajoutés à cette méthode en tant que membres de ce paramètre.
 a| 
xref:reference_element_api_cluster.adoc[grappe]
 a| 
Aucune
 a| 
Non

|===


== valeur de retour

Cette méthode a la valeur de retour suivante :

|===
| Nom | Description | Type 


 a| 
grappe
 a| 
Informations de configuration utilisées par le nœud pour communiquer avec le cluster.
 a| 
xref:reference_element_api_cluster.adoc[grappe]

|===


== Exemple de demande

Les requêtes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
   "method": "SetClusterConfig",
   "params": {
      "cluster": {
         "name": "myhost",
         "mipi": "Bond10G"
      },
    "id" : 1
   }
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
   "id" : 1,
   "result" : {
      "cluster" : {
         "cipi" : "Bond10G",
         "cluster" : "QoS",
         "ensemble" : [
            "1:10.10.5.42",
            "2:10.10.5.43",
            "3:10.10.5.44",
            "4:10.10.5.46",
            "5:10.10.5.47"
         ],
          "hostname" : "myhost",
          "mipi" : "Bond10G",
          "nodeID" : 1,
          "sipi" : "Bond10G",
          "state" : "Active"
      }
   }
}
----


== Nouveautés depuis la version

9,6
