---
permalink: api/reference_element_api_testkeyserverkmip.html 
sidebar: sidebar 
keywords: KMIP,key server,testing,test 
summary: 'Vous pouvez utiliser la méthode TestKeyServerKmip pour tester si le serveur de clés du protocole d"interopérabilité de gestion des clés (KMIP) spécifié est accessible et fonctionne normalement.' 
---
= TestKeyServerKmip
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `TestKeyServerKmip` méthode permettant de tester si le serveur de clés KMIP (Key Management Interoperability Protocol) spécifié est accessible et fonctionne normalement.



== Paramètres

Cette méthode possède les paramètres d'entrée suivants :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
ID du serveur de clés
 a| 
L'identifiant du serveur de clés KMIP à tester.
 a| 
entier
 a| 
Aucune
 a| 
Oui

|===


== Valeurs de retour

Cette méthode ne renvoie aucune valeur.  Le test est considéré comme réussi si aucune erreur n'est renvoyée.



== Exemple de demande

Les requêtes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
  "method": "TestKeyServerKmip",
  "params": {
    "keyServerID": 15
  },
"id": 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
   "id": 1,
   "result":
      {}
    }
----


== Nouveautés depuis la version

11,7
