---
permalink: api/reference_element_api_enableclusterssh.html 
sidebar: sidebar 
keywords: SSH,enabling,enable,cluster,EnableClusterSsh 
summary: Vous pouvez utiliser la méthode EnableClusterSsh pour activer le service SSH sur tous les nœuds du cluster de stockage. 
---
= Activer le cluster SSH
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `EnableClusterSsh` méthode pour activer le service SSH sur tous les nœuds du cluster de stockage.



== Paramètre

Cette méthode possède le paramètre d'entrée suivant :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
durée
 a| 
Durée pendant laquelle le service SSH restera activé.
 a| 
chaîne
 a| 
Aucune
 a| 
Oui

|===


== Valeurs de retour

Cette méthode renvoie les valeurs suivantes :

|===
| Nom | Description | Type 


 a| 
résultat
 a| 
Un objet JSON contenant l'état du service SSH pour le cluster de stockage, le temps restant avant la désactivation de SSH et l'état du service SSH pour chaque nœud.
 a| 
objet JSON

|===


== Exemple de demande

Les requêtes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
  "method": "EnableClusterSsh",
  "params": {
      "duration"  : "02:00:00.00"
  },
  "id" : 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
	"id": 1,
	"result" : {
    "enabled": true,
    "timeRemaining": "00:43:21",
    "nodes": [
    {
        "nodeID": 1,
        "enabled": true
    },
    {
        "nodeID": 2,
        "enabled": true
    },
    {
        "nodeID": 3,
        "enabled": false
    },
    {
        "nodeID": 4,
        "enabled": false
    } ]
			}
	}
----


== Nouveautés depuis la version

10,3
