---
permalink: api/reference_element_api_modifybackuptarget.html 
sidebar: sidebar 
keywords: modify,modifying,edit,editing,change,changing,backup,target,modifybackuptarget 
summary: 'Vous pouvez utiliser la méthode ModifyBackupTarget pour modifier les attributs d"une cible de sauvegarde.' 
---
= Modifier la cible de sauvegarde
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `ModifyBackupTarget` Méthode permettant de modifier les attributs d'une cible de sauvegarde.



== Paramètres

Cette méthode possède les paramètres d'entrée suivants :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
ID cible de sauvegarde
 a| 
Identifiant unique de la cible à modifier.
 a| 
entier
 a| 
Aucune
 a| 
Oui



 a| 
attributs
 a| 
Liste de paires nom-valeur au format objet JSON.
 a| 
objet JSON
 a| 
Aucune
 a| 
Non



 a| 
nom
 a| 
Nouveau nom pour la cible de sauvegarde.
 a| 
chaîne
 a| 
Aucune
 a| 
Non

|===


== Valeurs de retour

Cette méthode ne renvoie aucune valeur.



== Exemple de demande

Les requêtes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
   "method": "ModifyBackupTarget",
   "params": {
      "backupTargetID" : 1,
      "name": "yourtargetS3"
      "attributes" : {
          "size" : 500,
      }
   },
  "id": 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
   "id": 1,
   "result": {}
}
----


== Nouveautés depuis la version

9,6
