---
permalink: api/reference_element_api_getdriveconfig.html 
sidebar: sidebar 
keywords: drive,config,configuration,get,getting,getdriveconfig 
summary: Vous pouvez utiliser la méthode GetDriveConfig pour obtenir des informations sur les disques, notamment le nombre de disques de tranches et de blocs attendu, ainsi que le nombre de disques de tranches et de blocs actuellement connectés au nœud. 
---
= GetDriveConfig
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `GetDriveConfig` méthode permettant d'obtenir des informations sur les disques pour le nombre attendu de disques de tranches et de blocs, ainsi que sur le nombre de disques de tranches et de blocs actuellement connectés au nœud.



== Paramètres

Cette méthode ne requiert aucun paramètre d'entrée.



== valeur de retour

Cette méthode a la valeur de retour suivante :

|===
| Nom | Description | Type 


 a| 
configuration du lecteur
 a| 
Informations sur les disques connectés au nœud.
 a| 
xref:reference_element_api_drive.adoc[conduire]

|===


== Exemple de demande

Les requêtes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
   "method": "GetDriveConfig",
   "params": {},
   "id" : 1
}
----


== Exemple de réponse

Les réponses pour cette méthode sont similaires à l'exemple suivant.  En raison de sa longueur, la réponse ne contient d'informations que pour un seul lecteur d'un seul nœud de stockage.

[listing]
----
{
	"id": 1,
	"result": {
			"driveConfig": {
					"drives": [
						{
							"canonicalName": "sda",
							"connected": true,
							"dev": 2052,
							"devPath": "/dev/sdimm0p4",
							"driveType": "Slice",
							"name": "scsi-SATA_VRFSD3400GNCVMT205581853-part4",
							"path": "/dev/sda4",
							"pathLink": "/dev/sdimm0p4",
							"product": "VRFSD3400GNCVMTKS1",
							"scsiCompatId": "scsi-SATA_VRFSD3400GNCVMT205581853-part4",
							"scsiState": "Running",
							"securityAtMaximum": false,
							"securityEnabled": false,
							"securityFrozen": true,
							"securityLocked": false,
							"securitySupported": true,
							"serial": "205581853",
							"size": 299988156416,
							"slot": -1,
							"uuid": "9d4b198b-5ff9-4f7c-04fc-3bc4e2f38974",
							"vendor": "Viking",
							"version": "612ABBF0"
						}
					],
					"numBlockActual": 10,
					"numBlockExpected": 10,
					"numSliceActual": 1,
					"numSliceExpected": 1,
					"numTotalActual": 11,
					"numTotalExpected": 11
			}
	}
}
----