---
permalink: api/reference_element_api_createqospolicy.html 
sidebar: sidebar 
keywords: QoS,policy,policies,create,creating 
summary: Vous pouvez utiliser la méthode CreateQoSPolicy pour créer un objet QoSPolicy que vous pourrez ensuite appliquer à un volume lors de sa création ou de sa modification.  Une politique QoS possède un identifiant unique, un nom et des paramètres QoS. 
---
= Créer une politique de qualité
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `CreateQoSPolicy` méthode permettant de créer un objet QoSPolicy que vous pourrez ensuite appliquer à un volume lors de sa création ou de sa modification.  Une politique QoS possède un identifiant unique, un nom et des paramètres QoS.



== Paramètres

Cette méthode possède les paramètres d'entrée suivants :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
nom
 a| 
Le nom de la politique QoS ; par exemple, or, platine ou argent.
 a| 
chaîne
 a| 
Aucune
 a| 
Oui



 a| 
qualité de service
 a| 
Les paramètres QoS que représente cette politique.
 a| 
xref:reference_element_api_qos.adoc[Qualité de service]
 a| 
Aucune
 a| 
Oui

|===


== valeur de retour

Cette méthode a la valeur de retour suivante :

|===


| Nom | Description | Type 


 a| 
Politique de QoS
 a| 
L'objet QoSPolicy nouvellement créé.
 a| 
xref:reference_element_api_qospolicy.adoc[Politique de qualité]

|===


== Exemple de demande

Les requêtes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
  "id": 68,
  "method": "CreateQoSPolicy",
  "params": {
    "name": "bronze",
    "qos": {
      "minIOPS": 50,
      "maxIOPS": 15000,
      "burstIOPS": 15000
    }
  }
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
  "id": 68,
  "result": {
    "qosPolicy": {
      "name": "bronze",
      "qos": {
        "burstIOPS": 15000,
        "burstTime": 60,
        "curve": {
          "4096": 100,
          "8192": 160,
          "16384": 270,
          "32768": 500,
          "65536": 1000,
          "131072": 1950,
          "262144": 3900,
          "524288": 7600,
          "1048576": 15000
        },
        "maxIOPS": 15000,
        "minIOPS": 50
      },
      "qosPolicyID": 2,
      "volumeIDs": []
    }
  }
}
----


== Nouveautés depuis la version

10,0
