---
permalink: api/reference_element_api_removevolumesfromvolumeaccessgroup.html 
sidebar: sidebar 
keywords: remove,removing,volume,volumes,access,group,removevolumesfromvolumeaccessgroup 
summary: 'Vous pouvez utiliser la méthode RemoveVolumesFromVolumeAccessGroup pour supprimer des volumes d"un groupe d"accès aux volumes spécifié.' 
---
= Supprimer les volumes du groupe d'accès aux volumes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `RemoveVolumesFromVolumeAccessGroup` méthode permettant de supprimer des volumes d'un groupe d'accès aux volumes spécifié.



== Paramètres

Cette méthode possède les paramètres d'entrée suivants :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
volumeAccessGroupID
 a| 
ID du groupe d'accès au volume à supprimer.
 a| 
entier
 a| 
Aucune
 a| 
Oui



 a| 
volumes
 a| 
Identifiants des volumes à supprimer du groupe d'accès aux volumes.
 a| 
tableau d'entiers
 a| 
Aucune
 a| 
Oui

|===


== valeur de retour

Cette méthode a la valeur de retour suivante :

|===
| Nom | Description | Type 


 a| 
volumeAccessGroup
 a| 
Un objet contenant des informations sur le groupe d'accès aux volumes nouvellement modifié.
 a| 
xref:reference_element_api_volumeaccessgroup.adoc[volumeAccessGroup]

|===


== Exemple de demande

Les requêtes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
   "method": "RemoveVolumesFromVolumeAccessGroup",
   "params": {
      "volumeAccessGroupID": 96,
      "volumes": [1,2]
   },
   "id": 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
  "id": 1,
  "result": {
    "volumeAccessGroup": {
      "attributes": {},
      "deletedVolumes": [
        346
      ],
      "initiatorIDs": [
        116,
        117
      ],
      "initiators": [
        "iqn.1993-08.org.debian:01:181324777",
        "iqn.1993-08.org.debian:01:181324888"
      ],
      "name": "northbanktest",
      "volumeAccessGroupID": 96,
      "volumes": []
    }
  }
}
----


== Nouveautés depuis la version

9,6
