---
permalink: api/reference_element_api_clonevolume.html 
sidebar: sidebar 
keywords: volumes,volume,cloning,clone,CloneVolume 
summary: 'Vous pouvez utiliser la méthode CloneVolume pour créer une copie d"un volume.  Cette méthode est asynchrone et son exécution peut prendre un temps variable.' 
---
= Volume cloné
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `CloneVolume` méthode pour créer une copie d'un volume.  Cette méthode est asynchrone et son exécution peut prendre un temps variable.

Le processus de clonage commence immédiatement lorsque vous effectuez le `CloneVolume` requête et est représentative de l'état du volume au moment où la méthode API est émise.  Vous pouvez utiliser lexref:reference_element_api_getasyncresult.adoc[GetAsyncResult] méthode permettant de déterminer quand le processus de clonage est terminé et que le nouveau volume est disponible pour les connexions.  Vous pouvez utiliserxref:reference_element_api_listsyncjobs.adoc[ListSyncJobs] pour suivre l'avancement de la création du clone.  Les attributs initiaux et les paramètres de qualité de service du volume sont hérités du volume cloné.  Vous pouvez modifier ces paramètres avecxref:reference_element_api_modifyvolume.adoc[Modifier le volume] .


NOTE: Les volumes clonés n'héritent pas de l'appartenance au groupe d'accès aux volumes du volume source.



== Paramètres

Cette méthode possède les paramètres d'entrée suivants :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
accéder
 a| 
L'accès a été autorisé pour le nouveau volume.  Si aucune valeur n'est spécifiée, la valeur d'accès reste inchangée. Valeurs possibles :

* `readOnly`: (Facultatif) Seules les opérations de lecture sont autorisées.
* `readWrite`: (Facultatif) Les lectures et les écritures sont autorisées.
* `locked`: (Facultatif) Aucune lecture ni écriture n'est autorisée.  Si aucune valeur n'est spécifiée, la valeur d'accès du volume cloné est utilisée.
* `replicationTarget`: (Facultatif) Identifier un volume comme volume cible pour un ensemble de volumes appariés.  Si le volume n'est pas apparié, l'accès est verrouillé.

 a| 
chaîne
 a| 
Aucune
 a| 
Non



 a| 
attributs
 a| 
Liste de paires nom-valeur au format objet JSON.
 a| 
objet JSON
 a| 
Aucune
 a| 
Non



 a| 
enable512e
 a| 
Indique si le nouveau volume doit utiliser l'émulation de secteur de 512 octets.  Si aucun paramètre n'est spécifié, c'est celui du volume cloné qui est utilisé.
 a| 
booléen
 a| 
Réglage du volume d'origine
 a| 
Non



 a| 
activerSnapMirrorReplication
 a| 
Détermine si le volume peut être utilisé pour la réplication avec les points de terminaison SnapMirror . Valeurs possibles :

* true
* FAUX

 a| 
booléen
 a| 
FAUX
 a| 
Non



 a| 
nom
 a| 
Nom du nouveau volume cloné ; doit comporter entre 1 et 64 caractères.
 a| 
chaîne
 a| 
Aucune
 a| 
Oui



 a| 
nouvelID de compte
 a| 
Identifiant du compte du propriétaire du nouveau volume.  Si aucun identifiant n'est spécifié, l'identifiant du compte du propriétaire du volume cloné est utilisé.
 a| 
entier
 a| 
Identifiant du compte du propriétaire du volume d'origine
 a| 
Non



 a| 
nouvelle taille
 a| 
Nouvelle taille du volume, en octets.  Peut être supérieur ou inférieur à la taille du volume cloné.  Si aucune valeur n'est spécifiée, la taille du volume reste inchangée.  La taille est arrondie à la Mo supérieure la plus proche.
 a| 
entier
 a| 
Aucune
 a| 
Non



 a| 
snapshotID
 a| 
Identifiant de l'instantané utilisé comme source du clone.  Si aucun identifiant n'est fourni, le volume actif actuel est utilisé.
 a| 
entier
 a| 
Aucune
 a| 
Non



 a| 
volumeID
 a| 
Identifiant du volume à cloner.
 a| 
entier
 a| 
Aucune
 a| 
Oui

|===


== Valeurs de retour

Cette méthode renvoie les valeurs suivantes :

|===


| Nom | Description | Type 


 a| 
asyncHandle
 a| 
La valeur du descripteur utilisée pour obtenir le résultat de l'opération.
 a| 
entier



 a| 
cloneID
 a| 
L'identifiant du clone pour le volume nouvellement cloné.
 a| 
entier



 a| 
courbe
 a| 
Les valeurs de la courbe QoS appliquées au clone.
 a| 
objet JSON



 a| 
volume
 a| 
Un objet contenant des informations sur le volume nouvellement cloné.
 a| 
xref:reference_element_api_volume.adoc[volume]



 a| 
volumeID
 a| 
ID du volume pour le volume nouvellement cloné.
 a| 
entier

|===


== Exemple de demande

Les requêtes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
   "method": "CloneVolume",
   "params": {
      "volumeID" : 5,
      "name"  : "mysqldata-snapshot1",
      "access" : "readOnly"
   },
   "id" : 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
  "id": 1,
  "result": {
      "asyncHandle": 42,
      "cloneID": 37,
      "volume": {
          "access": "readOnly",
          "accountID": 1,
          "attributes": {},
          "blockSize": 4096,
          "createTime": "2016-03-31T22:26:03Z",
          "deleteTime": "",
          "enable512e": true,
          "iqn": "iqn.2010-01.com.solidfire:jyay.mysqldata-snapshot1.680",
          "name": "mysqldata-snapshot1",
          "purgeTime": "",
          "qos": {
              "burstIOPS": 100,
              "burstTime": 60,
              "curve": {
                  "4096": 100,
                  "8192": 160,
                  "16384": 270,
                  "32768": 500,
                  "65536": 1000,
                  "131072": 1950,
                  "262144": 3900,
                  "524288": 7600,
                  "1048576": 15000
              },
              "maxIOPS": 100,
              "minIOPS": 50
          },
          "scsiEUIDeviceID": "6a796179000002a8f47acc0100000000",
          "scsiNAADeviceID": "6f47acc1000000006a796179000002a8",
          "sliceCount": 0,
          "status": "init",
          "totalSize": 1000341504,
          "virtualVolumeID": null,
          "volumeAccessGroups": [],
          "volumeID": 680,
          "volumePairs": []
      },
      "volumeID": 680
  }
}
----


== Nouveautés depuis la version

9,6



== Trouver plus d'informations

* xref:reference_element_api_getasyncresult.adoc[GetAsyncResult]
* xref:reference_element_api_listsyncjobs.adoc[ListSyncJobs]
* xref:reference_element_api_modifyvolume.adoc[Modifier le volume]

