---
permalink: api/reference_element_api_deleteauthsessionsbyusername.html 
sidebar: sidebar 
keywords: auth sessions,username,delete,authentication sessions 
summary: 'Vous pouvez utiliser la méthode DeleteAuthSessionsByUsername pour supprimer toutes les sessions d"authentification d"un ou plusieurs utilisateurs donnés.  Un utilisateur n"appartenant pas au groupe d"accès ClusterAdmins/Administrateur ne peut supprimer que ses propres sessions.  Un appelant disposant des privilèges ClusterAdmins/Administrateur peut supprimer les sessions appartenant à n"importe quel utilisateur.  Pour afficher la liste des sessions pouvant être supprimées, utilisez ListAuthSessionsByUsername avec les mêmes paramètres.  Pour afficher la liste des sessions susceptibles d"être supprimées, utilisez la méthode ListAuthSessionsByUsername avec le même paramètre.' 
---
= Supprimer les sessions d'authentification par nom d'utilisateur
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `DeleteAuthSessionsByUsername` méthode permettant de supprimer toutes les sessions d'authentification pour un ou plusieurs utilisateurs donnés.  Un appelant n'appartenant pas au groupe d'accès ClusterAdmins/Administrateur ne peut supprimer que ses propres sessions.  Un appelant disposant des privilèges ClusterAdmins/Administrateur peut supprimer les sessions appartenant à n'importe quel utilisateur.  Pour consulter la liste des sessions pouvant être supprimées, utilisez `ListAuthSessionsByUsername` avec les mêmes paramètres.  Pour consulter la liste des sessions susceptibles d'être supprimées, utilisez le `ListAuthSessionsByUsername` méthode avec le même paramètre.



== Paramètres

Cette méthode possède les paramètres d'entrée suivants :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
méthode d'authentification
 a| 
Méthode d'authentification des sessions utilisateur à supprimer.  Seul un appelant appartenant au groupe d'accès ClusterAdmins/Administrator peut fournir ce paramètre.  Les valeurs possibles sont :

* *authMethod=Cluster* spécifie le nom d'utilisateur ClusterAdmin.
* *authMethod=Ldap* spécifie le DN LDAP de l'utilisateur.
* *authMethod=Idp* spécifie soit l'UUID ou le NameID du fournisseur d'identité de l'utilisateur.  Si le fournisseur d'identité n'est pas configuré pour renvoyer l'une ou l'autre option, ceci spécifie un UUID aléatoire émis lors de la création de la session.

 a| 
méthode d'authentification
 a| 
Aucune
 a| 
Non



 a| 
nom d'utilisateur
 a| 
Identifiant unique de l'utilisateur.
 a| 
chaîne
 a| 
Aucune
 a| 
Non

|===


== Valeurs de retour

Cette méthode a la valeur de retour suivante :

|===


| Nom | Description | Type 


 a| 
séances
 a| 
Informations de session pour les sessions d'authentification supprimées.
 a| 
link:reference_element_api_authsessioninfo.html["authSessionInfo"]

|===


== Exemple de demande

Les requêtes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
  "method": "DeleteAuthSessionsByUsername",
  "params": {
    "authMethod": "Cluster",
    "username": "admin"
  }
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
"sessions": [
      {
        "accessGroupList": [
          "administrator"
        ],
        "authMethod": "Cluster",
        "clusterAdminIDs": [
          1
        ],
        "finalTimeout": "2020-03-14T19:21:24Z",
        "idpConfigVersion": 0,
        "lastAccessTimeout": "2020-03-11T19:51:24Z",
        "sessionCreationTime": "2020-03-11T19:21:24Z",
        "sessionID": "b12bfc64-f233-44df-8b9f-6fb6c011abf7",
        "username": "admin"
      }
    ]
}
----


== Nouveautés depuis la version

12,0
