---
permalink: api/reference_element_api_getpatchinfo.html 
sidebar: sidebar 
keywords: get,patch,info,patches,getpatchinfo 
summary: Vous pouvez utiliser la méthode GetPatchInfo pour obtenir des informations sur les correctifs installés sur un nœud. 
---
= GetPatchInfo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `GetPatchInfo` Méthode permettant d'obtenir des informations sur les correctifs logiciels Element installés sur un nœud de stockage.



== Paramètres

Cette méthode possède les paramètres d'entrée suivants :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


| `force`  a| 
Forcer l'exécution de la méthode sur tous les nœuds du cluster de stockage.  Vous n'en avez besoin que lorsque vous utilisez l'API sur une adresse IP de cluster plutôt que sur un seul nœud. Valeurs possibles :

* `true`
* `false`

| booléen | `false` | Non 
|===


== Valeurs de retour

Cette méthode renvoie les valeurs suivantes :

|===
| Nom | Description | Type 


| patchs | Objet contenant des informations sur les correctifs installés sur ce nœud. | objet JSON 
|===


== Exemple de demande

Les requêtes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
   "method": "GetPatchInfo",
   "params": {
      "force": false,
      },
   "id": 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
    "id": 1,
    "result": {
        "patches": {
          "SUST936": {
          "date": "Wed 09 Dec 2020 10:41:59 PM UTC",
          "description": "BMC fixes",
          "newFiles": [
              "None"
          ],
          "patchedFiles": [
              "Patched_file_1.bin",
              "Patched_file_2.dat",
              "Patched_file_3.tgz"
          ]
          }
        }
    }
}

----


== Nouveautés depuis la version

12,3
