---
permalink: api/reference_element_api_deletevolume.html 
sidebar: sidebar 
keywords: volume,volumes,delete,deleting,DeleteVolume 
summary: 'Vous pouvez utiliser la méthode DeleteVolume pour marquer un volume actif en vue de sa suppression.  Lorsqu"il est marqué, le volume est purgé (supprimé définitivement) une fois l"intervalle de nettoyage écoulé.' 
---
= Supprimer le volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `DeleteVolume` Méthode permettant de marquer un volume actif en vue de sa suppression.  Lorsqu'il est marqué, le volume est purgé (supprimé définitivement) une fois l'intervalle de nettoyage écoulé.

Après une demande de suppression de volume, toutes les connexions iSCSI actives vers ce volume sont immédiatement interrompues et aucune autre connexion n'est autorisée tant que le volume est dans cet état.  Un volume marqué n'est pas renvoyé dans les requêtes de découverte de cible.

Les instantanés d'un volume marqué pour suppression ne sont pas affectés.  Les instantanés sont conservés jusqu'à ce que le volume soit purgé du système.  Si un volume est marqué pour suppression et qu'une opération de lecture ou d'écriture en masse est en cours, cette opération est arrêtée.

Si le volume que vous supprimez est apparié à un autre volume, la réplication entre les volumes appariés est suspendue et aucune donnée n'est transférée vers ou depuis ce volume tant qu'il est supprimé.  Le volume distant auquel le volume supprimé était associé passe à l'état PausedMiconfigured et aucune donnée n'est plus envoyée vers lui ni depuis le volume supprimé.  Tant que le volume supprimé n'est pas purgé, il peut être restauré et les transferts de données peuvent reprendre.  Si le volume supprimé est purgé du système, le volume auquel il était associé passe à l'état Arrêté/Mal configuré et l'état d'association des volumes est supprimé.  Le volume purgé devient définitivement indisponible.



== Paramètre

Cette méthode possède le paramètre d'entrée suivant :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
volumeID
 a| 
L'identifiant du volume à supprimer.
 a| 
entier
 a| 
Aucune
 a| 
Oui

|===


== Valeurs de retour

Cette méthode renvoie les valeurs suivantes :

|===


| Nom | Description | Type 


 a| 
volume
 a| 
Objet contenant des informations sur le volume supprimé.
 a| 
xref:reference_element_api_volume.adoc[volume]



 a| 
volumeID
 a| 
L'identifiant du volume supprimé.
 a| 
entier



 a| 
courbe
 a| 
La courbe est un ensemble de paires clé-valeur.  Les clés correspondent aux tailles d'E/S en octets.  Les valeurs représentent le coût d'exécution d'une opération d'E/S à une taille d'E/S spécifique.  La courbe est calculée par rapport à une opération de 4096 octets fixée à 100 IOPS.
 a| 
objet JSON

|===


== Exemple de demande

Les requêtes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
   "method": "DeleteVolume",
   "params": {
      "volumeID"  : 5
   },
   "id" : 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
  "id": 1,
  "result": {
    "volume": {
      "access": "readWrite",
      "accountID": 1,
      "attributes": {
        "name1": "value1",
        "name2": "value2",
        "name3": "value3"
      },
      "blockSize": 4096,
      "createTime": "2016-03-28T16:16:13Z",
      "deleteTime": "2016-03-31T22:59:42Z",
      "enable512e": true,
      "iqn": "iqn.2010-01.com.solidfire:jyay.1459181777648.5",
      "name": "1459181777648",
      "purgeTime": "2016-04-01T06:59:42Z",
      "qos": {
        "burstIOPS": 150,
        "burstTime": 60,
        "curve": {
          "4096": 100,
          "8192": 160,
          "16384": 270,
          "32768": 500,
          "65536": 1000,
          "131072": 1950,
          "262144": 3900,
          "524288": 7600,
          "1048576": 15000
        },
        "maxIOPS": 100,
        "minIOPS": 60
      },
      "scsiEUIDeviceID": "6a79617900000005f47acc0100000000",
      "scsiNAADeviceID": "6f47acc1000000006a79617900000005",
      "sliceCount": 1,
      "status": "deleted",
      "totalSize": 1000341504,
      "virtualVolumeID": null,
      "volumeAccessGroups": [
        1
      ],
      "volumeID": 5,
      "volumePairs": []
    }
  }
}
----


== Nouveautés depuis la version

9,6
