---
permalink: api/reference_element_api_modifykeyserverkmip.html 
sidebar: sidebar 
keywords: KMIP,key server,modifying,modify,change,edit 
summary: 'Vous pouvez utiliser la méthode ModifyKeyServerKmip pour modifier un serveur de clés KMIP (Key Management Interoperability Protocol) existant selon les attributs spécifiés.  Bien que le seul paramètre requis soit le keyServerID, une requête ne contenant que le keyServerID ne fera rien et ne renverra aucune erreur.  Tout autre paramètre que vous spécifiez remplacera les valeurs existantes pour le serveur de clés par l"identifiant keyServerID spécifié.  Le serveur clé est contacté pendant l"opération afin de s"assurer de son bon fonctionnement.  Vous pouvez fournir plusieurs noms d"hôtes ou adresses IP avec le paramètre kmipKeyServerHostnames, mais uniquement si les serveurs de clés sont configurés en cluster.' 
---
= ModifierKeyServerKmip
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `ModifyKeyServerKmip` méthode permettant de modifier un serveur de clés KMIP (Key Management Interoperability Protocol) existant selon les attributs spécifiés.  Bien que le seul paramètre requis soit le keyServerID, une requête ne contenant que le keyServerID ne fera rien et ne renverra aucune erreur.  Tout autre paramètre que vous spécifiez remplacera les valeurs existantes pour le serveur de clés par l'identifiant keyServerID spécifié.  Le serveur clé est contacté pendant l'opération afin de s'assurer de son bon fonctionnement.  Vous pouvez fournir plusieurs noms d'hôtes ou adresses IP avec le paramètre kmipKeyServerHostnames, mais uniquement si les serveurs de clés sont configurés en cluster.



== Paramètres

Cette méthode possède les paramètres d'entrée suivants :

|===


| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
ID du serveur de clés
 a| 
L'identifiant du serveur de clés KMIP à modifier.
 a| 
entier
 a| 
Aucune
 a| 
Oui



 a| 
kmipCaCertificate
 a| 
Le certificat de clé publique de l'autorité de certification racine du serveur de clés externe.  Cela servira à vérifier le certificat présenté par le serveur de clés externe dans la communication TLS.  Pour les clusters de serveurs critiques où chaque serveur utilise une autorité de certification différente, fournissez une chaîne concaténée contenant les certificats racine de toutes les autorités de certification.
 a| 
chaîne
 a| 
Aucune
 a| 
Non



 a| 
Certificat client kmip
 a| 
Un certificat X.509 PKCS#10 au format PEM encodé en Base64 utilisé par le client Solidfire KMIP.
 a| 
chaîne
 a| 
Aucune
 a| 
Non



 a| 
Noms d'hôte du serveur de clés kmip
 a| 
Tableau des noms d'hôtes ou des adresses IP associés à ce serveur de clés KMIP.  Plusieurs noms d'hôtes ou adresses IP ne doivent être fournis que si les serveurs clés sont configurés en cluster.
 a| 
tableau de chaînes
 a| 
Aucune
 a| 
Non



 a| 
Nom du serveur de clés kmip
 a| 
Le nom du serveur de clés KMIP.  Ce nom est utilisé uniquement à des fins d'affichage et n'a pas besoin d'être unique.
 a| 
chaîne
 a| 
Aucune
 a| 
Non



 a| 
kmipKeyServerPort
 a| 
Le numéro de port associé à ce serveur de clés KMIP (généralement 5696).
 a| 
entier
 a| 
Aucune
 a| 
Non

|===


== Valeurs de retour

Cette méthode renvoie les valeurs suivantes :

|===


| Nom | Description | Type 


 a| 
kmipKeyServer
 a| 
Un objet contenant des informations sur le serveur de clés nouvellement modifié.
 a| 
link:reference_element_api_keyserverkmip.html["KeyServerKmip"]

|===


== Exemple de demande

Les requêtes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
  "method": "ModifyKeyServerKmip",
  "params": {
    "keyServerID": 15
    "kmipCaCertificate": "CPDCCAaUCEDyRMcsf9tAbDpq40ES/E...",
    "kmipClientCertificate": "kirWmnWXbj9T/UWZYB2oK0z5...",
    "kmipKeyServerHostnames" : ["server1.hostname.com", "server2.hostname.com"],
    "kmipKeyServerName" : "keyserverName",
    "kmipKeyServerPort" : 5696
  },
"id": 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
   "id": 1,
   "result":
      {
        "kmipKeyServer": {
            "kmipCaCertificate":"CPDCCAaUCEDyRMcsf9tAbDpq40ES/E...",
            "kmipKeyServerHostnames":[
                "server1.hostname.com", "server2.hostname.com"
            ],
            "keyProviderID":1,
            "kmipKeyServerName":"keyserverName",
            "keyServerID":1
            "kmipKeyServerPort":1,
            "kmipClientCertificate":"kirWmnWXbj9T/UWZYB2oK0z5...",
            "kmipAssignedProviderIsActive":true
        }
    }
}
----


== Nouveautés depuis la version

11,7
