---
permalink: api/reference_element_api_listvolumestatsbyaccount.html 
sidebar: sidebar 
keywords: volumes,volume,stats,list,listing,account,listvolumestatsbyaccount,activity 
summary: 'Vous pouvez utiliser la méthode ListVolumeStatsByAccount pour lister les mesures d"activité de volume de haut niveau pour chaque compte.  Les valeurs sont la somme de tous les volumes détenus par le compte.' 
---
= Lister les statistiques de volume par compte
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `ListVolumeStatsByAccount` méthode permettant de répertorier les mesures d'activité de volume de haut niveau pour chaque compte.  Les valeurs sont la somme de tous les volumes détenus par le compte.



== Paramètres

Cette méthode possède les paramètres d'entrée suivants :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
inclure les volumes virtuels
 a| 
Les volumes virtuels sont inclus par défaut dans la réponse.  Pour exclure les volumes virtuels, définissez la valeur sur false.
 a| 
booléen
 a| 
true
 a| 
Non



 a| 
comptes
 a| 
Liste des identifiants de compte pour lesquels des statistiques de volume doivent être renvoyées.  Si cette option est omise, les statistiques de tous les comptes sont renvoyées.
 a| 
tableau d'entiers
 a| 
Aucune
 a| 
Non

|===


== valeur de retour

Cette méthode a la valeur de retour suivante :

|===


| Nom | Description | Type 


 a| 
statistiques de volume
 a| 
Liste des informations relatives à l'activité de volume pour chaque compte. *Remarque :* Le membre volumeID est égal à 0 pour chaque entrée, car les valeurs représentent la somme de tous les volumes détenus par le compte.
 a| 
xref:reference_element_api_volumestats.adoc[statistiques de volume]tableau

|===


== Exemple de demande

Les requêtes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
"method": "ListVolumeStatsByAccount",
  "params": {"accounts": [3]},
  "id": 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
  "id": 1,
  "result": {
    "volumeStats": [
      {
        "accountID": 3,
        "nonZeroBlocks": 155040175,
        "readBytes": 3156273328128,
        "readBytesLastSample": 0,
        "readOps": 770574543,
        "readOpsLastSample": 0,
        "samplePeriodMSec": 500,
        "timestamp": "2016-10-17T20:42:26.231661Z",
        "unalignedReads": 0,
        "unalignedWrites": 0,
        "volumeAccessGroups": [],
        "volumeID": 0,
        "volumeSize": 1127428915200,
        "writeBytes": 1051988406272,
        "writeBytesLastSample": 0,
        "writeOps": 256833107,
        "writeOpsLastSample": 0,
        "zeroBlocks": 120211025
      }
    ]
  }
}
----


== Nouveautés depuis la version

9,6
