---
permalink: api/reference_element_api_purgedeletedvolumes.html 
sidebar: sidebar 
keywords: volume,volumes,purge,purging,multiple,deleted,purgedeletedvolumes 
summary: Vous pouvez utiliser la méthode PurgeDeletedVolumes pour purger immédiatement et définitivement les volumes qui ont été supprimés ; vous pouvez utiliser cette méthode pour purger jusqu’à 500 volumes à la fois. 
---
= PurgeDeletedVolumes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `PurgeDeletedVolumes` Méthode permettant de purger immédiatement et définitivement les volumes supprimés ; vous pouvez utiliser cette méthode pour purger jusqu’à 500 volumes à la fois.

Vous devez supprimer les volumes en utilisant `DeleteVolumes` avant qu'ils puissent être purgés.  Les volumes sont purgés automatiquement après un certain temps, l'utilisation de cette méthode n'est donc généralement pas nécessaire.


NOTE: Si vous purgez un grand nombre de volumes en même temps, ou si les volumes que vous purgez ont chacun de nombreux instantanés associés, la méthode peut échouer et renvoyer l'erreur « xDBConnectionLoss ».  Si cela se produit, réessayez l'appel de méthode avec des volumes inférieurs.



== Paramètres

Cette méthode possède les paramètres d'entrée suivants :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


| ID de volume | Liste des identifiants de volume des volumes à purger du système. | tableau d'entiers | Non | Non 


| identifiants de compte | Liste des identifiants de compte.  Tous les volumes de tous les comptes spécifiés sont purgés du système. | tableau d'entiers | Non | Non 


| ID de groupe d'accès au volume | Liste des ID de groupe d'accès aux volumes.  Tous les volumes de tous les groupes d'accès aux volumes spécifiés sont purgés du système. | tableau d'entiers | Non | Non 
|===
*Remarque :* Vous ne pouvez spécifier qu’un seul des paramètres ci-dessus par appel de méthode.  Spécifier plus d'un élément, ou aucun, entraîne une erreur.



== Valeurs de retour

Cette méthode ne renvoie aucune valeur.



== Exemple de demande

Les requêtes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
   "method": "PurgeDeletedVolumes",
   "params": {
      "accountIDs" : [1, 2, 3]
   },
   "id" : 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
  "id" : 1,
  "result": {}
}
----


== Nouveautés depuis la version

9,6



== Trouver plus d'informations

xref:reference_element_api_deletevolumes.adoc[Supprimer les volumes]
