---
permalink: api/reference_element_api_listallnodes.html 
sidebar: sidebar 
keywords: cluster,list,listing,node,nodes,all,listallnodes 
summary: Vous pouvez utiliser la méthode ListAllNodes pour lister les nœuds actifs et en attente dans le cluster. 
---
= Lister tous les nœuds
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `ListAllNodes` Méthode permettant de lister les nœuds actifs et en attente dans le cluster.



== Paramètres

Cette méthode ne requiert aucun paramètre d'entrée.



== Valeurs de retour

Cette méthode renvoie les valeurs suivantes :

|===
| Nom | Description | Type 


 a| 
nœuds
 a| 
Liste des objets décrivant les nœuds actifs du cluster.
 a| 
xref:reference_element_api_node.adoc[nœud]



 a| 
nœuds actifs en attente
 a| 
Liste des objets décrivant les nœuds actifs en attente pour le cluster.
 a| 
xref:reference_element_api_pendingactivenode.adoc[en attenteNœudActif]tableau



 a| 
nœuds en attente
 a| 
Liste des objets décrivant les nœuds en attente pour le cluster.
 a| 
xref:reference_element_api_pendingnode.adoc[nœud en attente]tableau

|===


== Exemple de demande

Les requêtes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
   "method": "ListAllNodes",
   "params": {},
   "id" : 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
	"id": 1,
	"result": {
		"nodes": [
			{
				"associatedFServiceID": 0,
				"associatedMasterServiceID": 1,
				"attributes": {},
				"chassisName": "CT5TV12",
				"cip": "10.1.1.1",
				"cipi": "Bond10G",
				"fibreChannelTargetPortGroup": null,
				"mip": "10.1.1.1",
				"mipi": "Bond1G",
				"name": "NLABP0704",
				"nodeID": 1,
				"nodeSlot": "",
				"platformInfo": {
					"chassisType": "R620",
					"cpuModel": "Intel",
					"nodeMemoryGB": 72,
					"nodeType": "SF3010",
					"platformConfigVersion": "0.0.0.0"
				},
				"sip": "10.1.1.1",
				"sipi": "Bond10G",
				"softwareVersion": "11.0",
				"uuid": "4C4C4544-0054",
				"virtualNetworks": []
			}
		],
		"pendingActiveNodes": [],
		"pendingNodes": []
	}
}
----


== Nouveautés depuis la version

9,6
