---
permalink: api/reference_element_api_resetdrives.html 
sidebar: sidebar 
keywords: drive,drives,remove,removing,data,reset,resetting,resetdrives,erase 
summary: Vous pouvez utiliser la méthode ResetDrives pour initialiser proactivement les disques et supprimer toutes les données actuellement présentes sur un disque.  Le disque peut alors être réutilisé dans un nœud existant ou utilisé dans un nœud mis à niveau. 
---
= Réinitialiser les disques
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `ResetDrives` Méthode permettant d'initialiser proactivement les disques et de supprimer toutes les données actuellement présentes sur un disque.  Le disque peut alors être réutilisé dans un nœud existant ou utilisé dans un nœud mis à niveau.



== Paramètres

Cette méthode possède les paramètres d'entrée suivants :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
lecteurs
 a| 
Liste des noms de périphériques (et non des identifiants de lecteur) à réinitialiser.
 a| 
chaîne
 a| 
Aucune
 a| 
Oui



 a| 
forcer
 a| 
Définissez cette option sur « vrai » pour réinitialiser le lecteur.
 a| 
booléen
 a| 
Aucune
 a| 
Oui

|===


== valeur de retour

Cette méthode a la valeur de retour suivante :

|===
| Nom | Description | Type 


 a| 
détails
 a| 
Détails des disques en cours de réinitialisation.
 a| 
tableau d'objets JSON

|===


== Exemple de demande

Les requêtes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
   "method": "ResetDrives",
   "params": {
      "drives" : "slot3",
      "force" : true
   },
   "id" : 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
  "id": 1,
  "result": {
   "details": {
    "drives": [
    {
      "drive": "slot3",
      "returnCode": 0,
      "stderr": " * Unlocking /dev/slot9 .[ ok ]\ * Setting master password /dev/slot9 .[ ok ]\ * Secure erasing /dev/slot9 (hdparm) [tries=0/1] ...........................[ ok ]",
      "stdout": ""
    }
   ]
  },
  "duration": "00:00:28.501269",
  "result": "Passed"
  }
}
----


== Nouveautés depuis la version

9,6
