---
permalink: api/reference_element_api_network_bonded_interfaces.html 
sidebar: sidebar 
keywords: object,objects,network 
summary: 'L"objet réseau (interfaces liées) contient des informations de configuration pour les interfaces réseau liées sur un nœud de stockage.  Vous pouvez utiliser les méthodes GetConfig et GetNetworkConfig pour obtenir ces informations pour un nœud de stockage.' 
---
= réseau (interfaces liées)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'objet réseau (interfaces agrégées) contient des informations de configuration pour les interfaces réseau agrégées sur un nœud de stockage.  Vous pouvez utiliser le `GetConfig` et `GetNetworkConfig` méthodes pour obtenir ces informations pour un nœud de stockage.



== membres de l'objet

Cet objet contient les membres suivants :

|===


| Nom | Description | Type 


 a| 
adresse
 a| 
L'adresse IPv4 attribuée à cette interface sur le nœud.
 a| 
chaîne



 a| 
addressV6
 a| 
L'adresse de gestion IPv6 attribuée à l'interface Bond1G sur le nœud.
 a| 
chaîne



 a| 
retard de baisse des obligations
 a| 
Temps d'attente, en millisecondes, avant de désactiver un esclave après la détection d'une défaillance de liaison.
 a| 
chaîne



 a| 
bond-fail_over_mac
 a| 
Configuration de l'adresse MAC de l'interface réseau.
 a| 
chaîne



 a| 
lien-miimon
 a| 
La fréquence, en millisecondes, à laquelle l'état de la liaison MII est inspecté pour détecter les défaillances de liaison.
 a| 
chaîne



 a| 
mode de liaison
 a| 
Le mode de liaison. Valeurs possibles :

* Actif/Passif (Par défaut)
* ALB
* LACP (Recommandé)

 a| 
chaîne



 a| 
resélection de bond-primaire
 a| 
Spécifie quand l'esclave de liaison principal est choisi comme esclave actif. Valeurs possibles :

* Toujours
* Mieux
* Échec

 a| 
chaîne



 a| 
esclaves
 a| 
Liste des interfaces esclaves pour la liaison.
 a| 
chaîne



 a| 
taux de liaison
 a| 
Lorsque le mode Bond est LACP, le taux peut changer pour prendre l'une des valeurs suivantes :

* LACP Rapide (Par défaut)
* LACP lent

 a| 
chaîne



 a| 
retard de mise en place des liens
 a| 
Le temps, en millisecondes, à attendre avant d'activer un esclave après la détection d'une liaison.
 a| 
chaîne



 a| 
serveurs de noms DNS
 a| 
Liste d'adresses utilisées pour les services de noms de domaine, séparées par une virgule ou un espace.
 a| 
chaîne



 a| 
recherche DNS
 a| 
Liste de domaines de recherche DNS séparés par des espaces ou des virgules.
 a| 
chaîne



 a| 
famille
 a| 
Famille d'adresses que l'interface est configurée pour utiliser.  Actuellement, le protocole « inet » pour IPv4 est pris en charge.
 a| 
chaîne



 a| 
porte
 a| 
L'adresse réseau du routeur IPv4 utilisée pour envoyer le trafic depuis le réseau local.
 a| 
chaîne



 a| 
gatewayV6
 a| 
L'adresse réseau du routeur IPv6 utilisée pour envoyer le trafic depuis le réseau local Bond1G.
 a| 
chaîne



 a| 
ipV6PrefixLength
 a| 
Longueur du préfixe de sous-réseau pour les routes statiques de type « net » pour le trafic IPv6 sur le réseau Bond1G.
 a| 
chaîne



 a| 
adresse MAC
 a| 
L'adresse MAC réelle attribuée à l'interface et observée par le réseau.
 a| 
chaîne



 a| 
adresse MAC permanente
 a| 
L'adresse MAC immuable attribuée par le fabricant à l'interface.
 a| 
chaîne



 a| 
méthode
 a| 
La méthode utilisée pour configurer l'interface. Valeurs possibles :

* Bouclage : Utilisé pour définir l'interface de bouclage IPv4.
* manuel : Permet de définir les interfaces qui ne sont pas configurées automatiquement.
* DHCP : Permet d’obtenir une adresse IP via DHCP.
* statique : Utilisé pour définir des interfaces Ethernet avec des adresses IPv4 allouées statiquement.

 a| 
chaîne



 a| 
mtu
 a| 
La taille maximale des paquets (en octets) que l'interface peut transmettre.  Doit être supérieur ou égal à 1500 ; jusqu'à 9000 est pris en charge.
 a| 
chaîne



 a| 
masque de sous-réseau
 a| 
Le masque de bits qui spécifie le sous-réseau de l'interface.
 a| 
chaîne



 a| 
réseau
 a| 
Indique où commence la plage d'adresses IP en fonction du masque de sous-réseau.
 a| 
chaîne



 a| 
itinéraires
 a| 
Tableau de chaînes de routage séparées par des virgules à appliquer à la table de routage.
 a| 
tableau de chaînes



 a| 
statut
 a| 
L'état de l'interface. Valeurs possibles :

* En bas : L'interface est inactive.
* En haut : L'interface est prête, mais n'a pas de connexion.
* Opérationnel : L'interface est prête et une connexion est établie.

 a| 
chaîne



 a| 
Règles de routage symétriques
 a| 
Les règles de routage symétriques configurées sur le nœud.
 a| 
tableau de chaînes



 a| 
opérationnel
 a| 
Indique si l'interface est prête et dispose d'une connexion.
 a| 
booléen



 a| 
VirtualNetworkTag
 a| 
L'identifiant de réseau virtuel de l'interface (étiquette VLAN).
 a| 
chaîne

|===


== modifiabilité des membres et états des nœuds

Ce tableau indique si les paramètres de l'objet peuvent être modifiés à chaque état possible du nœud.

|===


| Nom du membre | État disponible | État en attente | État actif 


 a| 
adresse
 a| 
Oui
 a| 
Oui
 a| 
Non



 a| 
addressV6
 a| 
Oui
 a| 
Oui
 a| 
Non



 a| 
retard de baisse des obligations
 a| 
Configuré par le système
 a| 
S/O
 a| 
S/O



 a| 
bond-fail_over_mac
 a| 
Configuré par le système
 a| 
S/O
 a| 
S/O



 a| 
lien-miimon
 a| 
Configuré par le système
 a| 
S/O
 a| 
S/O



 a| 
mode de liaison
 a| 
Oui
 a| 
Oui
 a| 
Oui



 a| 
resélection de bond-primaire
 a| 
Configuré par le système
 a| 
S/O
 a| 
S/O



 a| 
esclaves
 a| 
Configuré par le système
 a| 
S/O
 a| 
S/O



 a| 
taux de liaison
 a| 
Oui
 a| 
Oui
 a| 
Oui



 a| 
retard de mise en place des liens
 a| 
Configuré par le système
 a| 
S/O
 a| 
S/O



 a| 
serveurs de noms DNS
 a| 
Oui
 a| 
Oui
 a| 
Oui



 a| 
recherche DNS
 a| 
Oui
 a| 
Oui
 a| 
Oui



 a| 
famille
 a| 
Non
 a| 
Non
 a| 
Non



 a| 
porte
 a| 
Oui
 a| 
Oui
 a| 
Oui



 a| 
gatewayV6
 a| 
Oui
 a| 
Oui
 a| 
Oui



 a| 
ipV6PrefixLength
 a| 
Oui
 a| 
Oui
 a| 
Oui



 a| 
adresse MAC
 a| 
Configuré par le système
 a| 
S/O
 a| 
S/O



 a| 
adresse MAC permanente
 a| 
Configuré par le système
 a| 
S/O
 a| 
S/O



 a| 
méthode
 a| 
Non
 a| 
Non
 a| 
Non



 a| 
mtu
 a| 
Oui
 a| 
Oui
 a| 
Oui



 a| 
masque de sous-réseau
 a| 
Oui
 a| 
Oui
 a| 
Oui



 a| 
réseau
 a| 
Non
 a| 
Non
 a| 
Non



 a| 
itinéraires
 a| 
Oui
 a| 
Oui
 a| 
Oui



 a| 
statut
 a| 
Oui
 a| 
Oui
 a| 
Oui



 a| 
Règles de routage symétriques
 a| 
Configuré par le système
 a| 
S/O
 a| 
S/O



 a| 
opérationnel
 a| 
Configuré par le système
 a| 
S/O
 a| 
S/O



 a| 
VirtualNetworkTag
 a| 
Oui
 a| 
Oui
 a| 
Oui

|===


== Trouver plus d'informations

* xref:reference_element_api_getconfig.adoc[GetConfig]
* xref:reference_element_api_getnetworkconfig.adoc[Obtenir la configuration réseau]

