---
permalink: api/reference_element_api_snapmirrorendpoint.html 
sidebar: sidebar 
keywords: object,objects,snapMirrorEndpoint 
summary: 'L"objet snapMirrorEndpoint contient des informations sur les systèmes de stockage SnapMirror distants communiquant avec le cluster de stockage Element.  Vous pouvez récupérer ces informations avec la méthode API ListSnapMirrorEndpoints.' 
---
= snapMirrorEndpoint
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'objet snapMirrorEndpoint contient des informations sur les systèmes de stockage SnapMirror distants communiquant avec le cluster de stockage Element.  Vous pouvez récupérer ces informations avec la méthode API ListSnapMirrorEndpoints.



== membres de l'objet

Cet objet contient les membres suivants :

|===
| Nom | Description | Type 


 a| 
snapMirrorEndpointID
 a| 
L'identifiant unique de l'objet dans le cluster local.
 a| 
entier



 a| 
gestionIP
 a| 
Adresse IP de gestion du cluster du point de terminaison.
 a| 
chaîne



 a| 
nom du cluster
 a| 
Le nom du cluster ONTAP .  Cette valeur est automatiquement renseignée avec la valeur de « `clusterName` » provenant de l’objet snapMirrorClusterIdentity.
 a| 
chaîne



 a| 
nom d'utilisateur
 a| 
Nom d'utilisateur de gestion pour le système ONTAP .
 a| 
chaîne



 a| 
Adresses IP
 a| 
Liste des adresses IP de stockage inter-cluster pour tous les nœuds du cluster.  Vous pouvez obtenir ces adresses IP avec la méthode ListSnapMirrorNetworkInterfaces.
 a| 
tableau de chaînes



 a| 
est connecté
 a| 
État de la connectivité de la liaison de contrôle au cluster ONTAP .
 a| 
booléen

|===