---
permalink: api/reference_element_api_getdrivestats.html 
sidebar: sidebar 
keywords: drive,drives,stats,get,getting,getdrivestats 
summary: 'Vous pouvez utiliser la méthode GetDriveStats pour obtenir des mesures d"activité de haut niveau pour un seul lecteur.  Les valeurs sont cumulatives à partir de l"ajout du disque au cluster.  Certaines valeurs sont spécifiques aux disques de stockage par blocs.  Cette méthode renvoie des données statistiques pour les lecteurs de type bloc ou métadonnées.' 
---
= GetDriveStats
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `GetDriveStats` méthode pour obtenir des mesures d'activité de haut niveau pour un seul disque dur.  Les valeurs sont cumulatives à partir de l'ajout du disque au cluster.  Certaines valeurs sont spécifiques aux disques de stockage par blocs.  Cette méthode renvoie des données statistiques pour les lecteurs de type bloc ou métadonnées.



== Paramètre

Cette méthode possède le paramètre d'entrée suivant :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
ID du lecteur
 a| 
Identifiant du lecteur pour la requête.
 a| 
entier
 a| 
Aucune
 a| 
Oui

|===


== valeur de retour

Cette méthode a la valeur de retour suivante :

|===
| Nom | Description | Type 


 a| 
driveStats
 a| 
Informations sur l'activité du lecteur pour l'identifiant de lecteur spécifié.
 a| 
xref:reference_element_api_drivestats.adoc[driveStats]

|===


== Exemple de demande

Les requêtes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
   "method": "GetDriveStats",
   "params": {
     "driveID": 3
   },
   "id" : 1
}
----


== Exemple de réponse (lecteur bloc)

Cette méthode renvoie une réponse similaire à l'exemple suivant pour un disque dur par blocs :

[listing]
----
{
  "id": 1,
  "result": {
    "driveStats": {
      "driveID": 10,
      "failedDieCount": 0,
      "lifeRemainingPercent": 99,
      "lifetimeReadBytes": 26471661830144,
      "lifetimeWriteBytes": 13863852441600,
      "powerOnHours": 33684,
      "readBytes": 10600432105,
      "readOps": 5101025,
      "reallocatedSectors": 0,
      "reserveCapacityPercent": 100,
      "timestamp": "2016-10-17T20:23:45.456834Z",
      "totalCapacity": 300069052416,
      "usedCapacity": 6112226545,
      "usedMemory": 114503680,
      "writeBytes": 53559500896,
      "writeOps": 25773919
    }
  }
}
----


== Exemple de réponse (lecteur de métadonnées de volume)

Cette méthode renvoie une réponse similaire à l'exemple suivant pour un lecteur de métadonnées de volume :

[listing]
----
{
  "id": 1,
  "result": {
    "driveStats": {
      "activeSessions": 8,
      "driveID": 12,
      "failedDieCount": 0,
      "lifeRemainingPercent": 100,
      "lifetimeReadBytes": 2308544921600,
      "lifetimeWriteBytes": 1120986464256,
      "powerOnHours": 16316,
      "readBytes": 1060152152064,
      "readOps": 258826209,
      "reallocatedSectors": 0,
      "reserveCapacityPercent": 100,
      "timestamp": "2016-10-17T20:34:52.456130Z",
      "totalCapacity": 134994670387,
      "usedCapacity": null,
      "usedMemory": 22173577216,
      "writeBytes": 353346510848,
      "writeOps": 86266238
    }
  }
}
----


== Nouveautés depuis la version

9,6



== Trouver plus d'informations

xref:reference_element_api_listdrives.adoc[ListDrives]
