---
permalink: api/reference_element_api_setremotelogginghosts.html 
sidebar: sidebar 
keywords: remote,logging,host,hosts,set,setting,setremotelogginghosts 
summary: 'Vous pouvez utiliser la méthode SetRemoteLoggingHosts pour configurer la journalisation à distance des nœuds du cluster de stockage vers un ou plusieurs serveurs de journalisation centralisés.  La journalisation à distance est effectuée via TCP en utilisant le port par défaut 514.  Cette API ne s"ajoute pas aux serveurs de journalisation existants.  Elle remplace plutôt les valeurs existantes par de nouvelles valeurs spécifiées par cette méthode API.  Vous pouvez utiliser GetRemoteLoggingHosts pour déterminer quels sont les hôtes de journalisation actuels, puis utiliser SetRemoteLoggingHosts pour définir la liste souhaitée des hôtes de journalisation actuels et nouveaux.' 
---
= Définir les hôtes de journalisation à distance
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `SetRemoteLoggingHosts` méthode permettant de configurer la journalisation à distance des nœuds du cluster de stockage vers un ou plusieurs serveurs de journalisation centralisés.  La journalisation à distance est effectuée via TCP en utilisant le port par défaut 514.  Cette API ne s'ajoute pas aux serveurs de journalisation existants.  Elle remplace plutôt les valeurs existantes par de nouvelles valeurs spécifiées par cette méthode API.  Vous pouvez utiliser `GetRemoteLoggingHosts` pour déterminer quels sont les hôtes de journalisation actuels, puis utiliser `SetRemoteLoggingHosts` pour définir la liste souhaitée des hôtes de journalisation actuels et nouveaux.



== Paramètre

Cette méthode possède le paramètre d'entrée suivant :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
hôtes distants
 a| 
Liste des hôtes qui reçoivent des messages de journalisation.
 a| 
xref:reference_element_api_loggingserver.adoc[serveur de journalisation]tableau
 a| 
Aucune
 a| 
Oui

|===


== Valeurs de retour

Cette méthode ne renvoie aucune valeur.



== Exemple de demande

Les requêtes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
   "id": 1,
   "method": "SetRemoteLoggingHosts",
   "params": {
     "remoteHosts": [
        {
          "host": "172.16.1.20",
          "port": 10514
        },
        {
          "host": "172.16.1.25"
        }
      ]
   }
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
    "id" : 1,
    "result" : {}
}
----


== Nouveautés depuis la version

9,6



== Trouver plus d'informations

xref:reference_element_api_getremotelogginghosts.adoc[GetRemoteLoggingHosts]
