---
permalink: api/reference_element_api_createclustersupportbundle.html 
sidebar: sidebar 
keywords: CreateClusterSupportBundle,create,cluster,support,bundle,creating 
summary: 'Vous pouvez utiliser la commande CreateClusterSupportBundle sur le nœud de gestion pour rassembler les bundles de support de tous les nœuds d"un cluster.  Lorsqu"un paquet est créé, il est stocké sur le nœud sous forme de fichier .tar.gz.  Cette méthode ne peut être exécutée que sur un nœud de gestion ; elle ne fonctionne pas lorsqu"elle est exécutée sur un nœud de stockage.' 
---
= CréerClusterSupportBundle
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `CreateClusterSupportBundle` sur le nœud de gestion pour rassembler les ensembles de support de tous les nœuds d'un cluster.  Les modules de support individuels des nœuds sont compressés sous forme de fichiers tar.gz.  Le bundle de support de cluster est un fichier tar contenant les bundles de support de nœud.  Cette méthode ne peut être exécutée que sur un nœud de gestion ; elle ne fonctionne pas lorsqu'elle est exécutée sur un nœud de stockage.



== Paramètres


NOTE: Vous devez appeler cette méthode sur le nœud de gestion. Par exemple:

[listing]
----
https://<management node IP>:442/json-rpc/10.0
----
Cette méthode possède les paramètres d'entrée suivants :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
autoriserIncomplet
 a| 
Permet au script de continuer à s'exécuter si les paquets ne peuvent pas être collectés à partir d'un ou plusieurs nœuds.
 a| 
booléen
 a| 
Aucune
 a| 
Non



 a| 
nom du bundle
 a| 
Nom unique pour chaque pack de support créé.  Si aucun nom n'est fourni, alors « supportbundle » et le nom du nœud sont utilisés comme nom de fichier.
 a| 
chaîne
 a| 
Aucune
 a| 
Non



 a| 
VIP
 a| 
Le MVIP du cluster.  Les paquets sont collectés à partir de tous les nœuds du cluster.  Ce paramètre est obligatoire si le paramètre « nodes » n’est pas spécifié.
 a| 
chaîne
 a| 
Aucune
 a| 
Oui



 a| 
nœuds
 a| 
Les adresses IP des nœuds à partir desquels collecter les paquets.  Utilisez soit nodes, soit mvip, mais pas les deux, pour spécifier les nœuds à partir desquels collecter les paquets.  Ce paramètre est obligatoire si mvip n'est pas spécifié.
 a| 
tableau de chaînes
 a| 
Aucune
 a| 
Oui



 a| 
mot de passe
 a| 
Le mot de passe de l'administrateur du cluster.  *Remarque :* Ce mot de passe s’affiche sous forme de texte lorsqu’il est saisi.
 a| 
chaîne
 a| 
Aucune
 a| 
Oui



 a| 
nom d'utilisateur
 a| 
Nom d'utilisateur de l'administrateur du cluster.
 a| 
chaîne
 a| 
Aucune
 a| 
Oui

|===


== Valeurs de retour

Cette méthode ne renvoie aucune valeur.



== Exemple de demande

Les requêtes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
"method": "CreateClusterSupportBundle",
"params": {
          "bundlename": "clusterbundle",
          "mvip": "132.119.120.100"
     }
   },
 "id": 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
  "id":1,
  "result":{
   "details":{
      "bundleName":"clusterbundle",
      "extraArgs":"",
      "files":[
          "/tmp/supportbundles/clusterbundle.cl-4SD5.tar"
      ],
      "output":"timeout -s KILL 1790s /usr/local/bin/sfclustersupportbundle --quiet --name=\"clusterbundle\" --target-directory=\"/tmp/solidfire-dtemp.MM7f0m\" --user=\"admin\" --pass=\"admin\" --mvip=132.119.120.100"
       },
       "duration":"00:00:24.938127",
       "result":"Passed"
    }
}
----


== Nouveautés depuis la version

9,6
