---
permalink: api/reference_element_api_listvolumestats.html 
sidebar: sidebar 
keywords: volumes,volume,stats,list,listing,listvolumestats,activity 
summary: 'Vous pouvez utiliser la méthode ListVolumeStats pour obtenir des mesures d"activité de haut niveau pour un seul volume, une liste de volumes ou tous les volumes (si vous omettez le paramètre volumeIDs).  Les valeurs de mesure sont cumulatives depuis la création du volume.' 
---
= ListVolumeStats
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `ListVolumeStats` méthode pour obtenir des mesures d'activité de haut niveau pour un seul volume, une liste de volumes ou tous les volumes (si vous omettez le paramètre volumeIDs).  Les valeurs de mesure sont cumulatives depuis la création du volume.



== Paramètres

Cette méthode possède les paramètres d'entrée suivants :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
inclure les volumes virtuels
 a| 
Les volumes virtuels sont inclus par défaut dans la réponse.  Pour exclure les volumes virtuels, définissez la valeur sur false.
 a| 
booléen
 a| 
true
 a| 
Non



 a| 
ID de volume
 a| 
Liste des volumes à partir desquels extraire les informations relatives à l'activité.
 a| 
tableau d'entiers
 a| 
Non
 a| 
Non

|===


== valeur de retour

Cette méthode a la valeur de retour suivante :

|===


| Nom | Description | Type 


 a| 
statistiques de volume
 a| 
Liste des informations relatives à l'activité volumétrique.
 a| 
xref:reference_element_api_volumestats.adoc[statistiques de volume]tableau

|===


== Exemple de demande

Les requêtes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
  "method": "ListVolumeStats",
    "params": {
        "volumeIDs": [1]
    },
    "id": 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
  "id": 1,
  "result": {
    "volumeStats": [
      {
        "accountID": 1,
        "actualIOPS": 0,
        "asyncDelay": null,
        "averageIOPSize": 0,
        "burstIOPSCredit": 30000,
        "clientQueueDepth": 0,
        "desiredMetadataHosts": null,
        "latencyUSec": 0,
        "metadataHosts": {
          "deadSecondaries": [],
          "liveSecondaries": [
            47
          ],
          "primary": 33
        },
        "nonZeroBlocks": 22080699,
        "readBytes": 657262370816,
        "readBytesLastSample": 0,
        "readLatencyUSec": 0,
        "readOps": 160464446,
        "readOpsLastSample": 0,
        "samplePeriodMSec": 500,
        "throttle": 0,
        "timestamp": "2016-03-09T19:39:15.771697Z",
        "unalignedReads": 0,
        "unalignedWrites": 0,
        "volumeAccessGroups": [
          1
        ],
        "volumeID": 1,
        "volumeSize": 107374182400,
        "volumeUtilization": 0,
        "writeBytes": 219117547520,
        "writeBytesLastSample": 0,
        "writeLatencyUSec": 0,
        "writeOps": 53495495,
        "writeOpsLastSample": 0,
        "zeroBlocks": 4133701
      }
    ]
  }
}
----


== Nouveautés depuis la version

9,6
