---
permalink: api/reference_element_api_getnetworkinterface.html 
sidebar: sidebar 
keywords: nodes,node,network,interface,get,getting,getnetworkinterface 
summary: Vous pouvez utiliser la méthode GetNetworkInterface pour obtenir des informations sur une interface réseau sur un nœud. 
---
= Obtenir l'interface réseau
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `GetNetworkInterface` méthode pour obtenir des informations sur une interface réseau sur un nœud.



== Paramètres

Cette méthode possède les paramètres d'entrée suivants :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
interface
 a| 
Le nom de l'interface pour laquelle obtenir des informations pour chaque nœud. Valeurs possibles :

* Bond1G
* Bond10G

 a| 
chaîne
 a| 
Aucune
 a| 
Non



 a| 
forcer
 a| 
Définissez ce paramètre sur « true » pour exécuter le programme sur tous les nœuds du cluster.
 a| 
booléen
 a| 
FAUX
 a| 
Non

|===


== valeur de retour

Cette méthode a la valeur de retour suivante :

|===
| Nom | Description | Type 


 a| 
nœuds
 a| 
Un tableau d'objets décrivant l'interface de chaque nœud de stockage du cluster de stockage.  Chaque objet du tableau contient les éléments suivants :

* nodeID : (entier) L’ID du nœud de stockage dans le cluster de stockage auquel s’appliquent les informations d’interface.
* résultat: (xref:reference_element_api_networkinterface.adoc[interface réseau] ) Informations de configuration d'interface pour ce nœud de stockage.

 a| 
tableau d'objets JSON

|===


== Exemple de demande

Les requêtes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
	"method": "GetNetworkInterface",
	"params": {
		"interface": "Bond1G",
		"force": true
		},
	"id": 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
	"id": 1,
	"result": {
		"nodes": [
			{
				"nodeID": 1,
				"result": {
					"interface": {
						"address": "10.117.64.32",
						"addressV6": "::",
						"broadcast": "10.117.79.255",
						"macAddress": "90:b1:1c:42:e0:1e",
						"mtu": 1500,
						"name": "Bond1G",
						"namespace": false,
						"netmask": "255.255.240.0",
						"status": "UpAndRunning",
						"type": "BondMaster",
						"virtualNetworkTag": 0
					}
				}
			},
			{
				"nodeID": 2,
				"result": {
					"interface": {
						"address": "10.117.64.35",
						"addressV6": "::",
						"broadcast": "10.117.79.255",
						"macAddress": "d4:ae:52:7a:ae:23",
						"mtu": 1500,
						"name": "Bond1G",
						"namespace": false,
						"netmask": "255.255.240.0",
						"status": "UpAndRunning",
						"type": "BondMaster",
						"virtualNetworkTag": 0
					}
				}
			},
			{
				"nodeID": 3,
				"result": {
					"interface": {
						"address": "10.117.64.39",
						"addressV6": "::",
						"broadcast": "10.117.79.255",
						"macAddress": "c8:1f:66:f0:9d:17",
						"mtu": 1500,
						"name": "Bond1G",
						"namespace": false,
						"netmask": "255.255.240.0",
						"status": "UpAndRunning",
						"type": "BondMaster",
						"virtualNetworkTag": 0
					}
				}
			},
			{
				"nodeID": 4,
				"result": {
					"interface": {
						"address": "10.117.64.107",
						"addressV6": "::",
						"broadcast": "10.117.79.255",
						"macAddress": "b8:ca:3a:f5:24:f8",
						"mtu": 1500,
						"name": "Bond1G",
						"namespace": false,
						"netmask": "255.255.240.0",
						"status": "UpAndRunning",
						"type": "BondMaster",
						"virtualNetworkTag": 0
					}
				}
			}
		]
	}
}
----


== Nouveautés depuis la version

9,6
