---
permalink: api/reference_element_api_disablefeature.html 
sidebar: sidebar 
keywords: SNMP,disable,disabling,DisableFeature,vvols,virtual volumes 
summary: Vous pouvez utiliser la méthode DisableFeature pour désactiver VolumeLoadBalanceOnActualIOPS. 
---
= Désactiver la fonctionnalité
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `DisableFeature` méthode pour désactiver la `VolumeLoadBalanceOnActualIOPS` fonctionnalité. `VolumeLoadBalanceOnActualIOPS` est désactivé par défaut.

[NOTE]
====
Si vous essayez de désactiver une autre fonctionnalité, telle que VVols, le message d'erreur suivant s'affiche :

[listing]
----
{"error":{"code":500,"message":"VolumeLoadBalanceOnActualIOPS is the only feature that can be disabled","name":"xAPINotPermitted"},"id":null}
----
====


== Paramètre

Cette méthode possède le paramètre d'entrée suivant.

[cols="1a,3a,1a,1a,1a"]
|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
fonctionnalité
 a| 
Désactiver une fonctionnalité de cluster.  Valeur possible :

* `VolumeLoadBalanceOnActualIOPS`Désactiver l'équilibrage des tranches sur les IOPS réelles plutôt que sur les IOPS minimales.

 a| 
chaîne
 a| 
Aucune
 a| 
Oui

|===


== valeur de retour

Cette méthode ne renvoie aucune valeur.



== Exemple de demande

Les requêtes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
  "method": "DisableFeature",
    "params": {
        "feature" : "VolumeLoadBalanceOnActualIOPS"
    },
    "id": 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
  "id": 1,
  "result": {}
}
----


== Nouveautés depuis la version

12,8
