---
permalink: api/reference_element_api_listclusterfaults.html 
sidebar: sidebar 
keywords: cluster,list,listing,fault,faults,listclusterfaults,error,errors 
summary: Vous pouvez utiliser la méthode ListClusterFaults pour obtenir des informations sur toutes les pannes détectées sur le cluster.  Cette méthode permet de lister à la fois les pannes actuelles et celles qui ont été résolues.  Le système met en cache les erreurs toutes les 30 secondes. 
---
= ListClusterFaults
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `ListClusterFaults` méthode permettant de lister les informations relatives aux défauts détectés sur le cluster.  Cette méthode permet de lister à la fois les pannes actuelles et celles qui ont été résolues.  Le système met en cache les erreurs toutes les 30 secondes.



== Paramètres

Cette méthode possède les paramètres d'entrée suivants :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
meilleures pratiques
 a| 
Inclure les défauts déclenchés par une configuration système sous-optimale. Valeurs possibles :

* true
* FAUX

 a| 
booléen
 a| 
Aucune
 a| 
Non



 a| 
types de défauts
 a| 
Détermine les types de défauts renvoyés. Valeurs possibles :

* Actuel : Liste des pannes actives et non résolues.
* résolu : Liste des défauts précédemment détectés et résolus.
* Tous : Liste des défauts actuels et résolus.  Vous pouvez consulter l'état de la panne dans le membre « `resolved` » de l'objet panne.

 a| 
chaîne
 a| 
tous
 a| 
Non

|===


== valeur de retour

Cette méthode a la valeur de retour suivante :

|===


| Nom | Description | Type 


 a| 
défauts
 a| 
Un objet décrivant les défauts du cluster demandés.
 a| 
xref:reference_element_api_fault.adoc[faute]

|===


== Exemple de demande

Les requêtes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
  "method": "ListClusterFaults",
    "params": {
      "faultTypes": "current",
      "bestPractices": true
    },
    "id": 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
  "id": 1,
  "result": {
    "faults": [
      {
        "blocksUpgrade": false,
        "clusterFaultID": 3,
        "code": "driveAvailable",
        "data": null,
        "date": "2024-04-03T22:22:56.660275Z",
        "details": "Node ID 1 has 6 available drive(s).",
        "driveID": 0,
        "driveIDs": [],
        "externalSource": "",
        "networkInterface": "",
        "nodeHardwareFaultID": 0,
        "nodeID": 1,
        "resolved": true,
        "resolvedDate": "2024-04-03T22:24:54.598693Z",
        "serviceID": 0,
        "severity": "warning",
        "type": "drive"
      },
      {
        "clusterFaultID": 9,
        "code": "disconnectedClusterPair",
        "data": null,
        "date": "2016-04-26T20:40:08.736597Z",
        "details": "One of the clusters in a pair may have become misconfigured or disconnected.  Remove the local pairing and retry pairing the clusters. Disconnected Cluster Pairs: []. Misconfigured Cluster Pairs: [3]",
        "driveID": 0,
        "driveIDs": [],
        "nodeHardwareFaultID": 0,
        "nodeID": 0,
        "resolved": false,
        "resolvedDate": "",
        "serviceID": 0,
        "severity": "warning",
        "type": "cluster"
      }
    ]
  }
}
----


== Nouveautés depuis la version

9,6
