---
permalink: api/reference_element_api_completeclusterpairing.html 
sidebar: sidebar 
keywords: CompleteClusterPairing,cluster,pair,pairing,complete,completing 
summary: 'La méthode CompleteClusterPairing est la deuxième étape du processus d"appariement des clusters.  Utilisez cette méthode avec la clé encodée reçue de la méthode StartClusterPairing pour terminer le processus d"appariement des clusters.' 
---
= Appariement complet du cluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le `CompleteClusterPairing` Cette méthode constitue la deuxième étape du processus d'appariement des clusters.  Utilisez cette méthode avec la clé encodée reçue de la `StartClusterPairing` méthode pour achever le processus d'appariement des clusters.



== Paramètres

Cette méthode possède le paramètre d'entrée suivant :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
clé d'appariement de cluster
 a| 
Une chaîne de caractères renvoyée parxref:reference_element_api_startclusterpairing.adoc[Début de l'appairage du cluster] Méthode API.
 a| 
chaîne
 a| 
Aucune
 a| 
Oui

|===


== valeur de retour

Cette méthode a la valeur de retour suivante :

|===


| Nom | Description | Type 


 a| 
clusterPairID
 a| 
Identifiant unique pour la paire de clusters.
 a| 
entier

|===


== Exemple de demande

Les requêtes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
   "method": "CompleteClusterPairing",
   "params": {
        "clusterPairingKey" : "7b22636c7573746572506169724944223a312c22636c75737465725061697255554944223a2231636561313336322d346338662d343631612d626537322d373435363661393533643266222c22636c7573746572556e697175654944223a2278736d36222c226d766970223a223139322e3136382e3133392e313232222c226e616d65223a224175746f54657374322d63307552222c2270617373776f7264223a22695e59686f20492d64774d7d4c67614b222c22727063436f6e6e656374696f6e4944223a3931333134323634392c22757365726e616d65223a225f5f53465f706169725f50597a796647704c7246564432444a42227d"
   },
   "id" : 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
   "id" : 1,
   "result" : {
       "clusterPairID" : 1
   }
}
----


== Nouveautés depuis la version

9,6



== Trouver plus d'informations

xref:reference_element_api_startclusterpairing.adoc[Début de l'appairage du cluster]
