---
permalink: api/reference_element_api_disablebmccoldreset.html 
sidebar: sidebar 
keywords: BMC cold reset,BMC reset,disable BMC 
summary: 'Vous pouvez utiliser la méthode DisableBmcColdReset pour désactiver la tâche en arrière-plan qui réinitialise périodiquement le contrôleur de gestion de la carte mère (BMC) pour tous les nœuds du cluster.' 
---
= DésactiverBmcColdReset
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `DisableBmcColdReset` méthode pour désactiver la tâche en arrière-plan qui réinitialise périodiquement le contrôleur de gestion de la carte mère (BMC) pour tous les nœuds du cluster.



== Paramètre

Cette méthode ne comporte aucun paramètre d'entrée.



== Valeurs de retour

Cette méthode a la valeur de retour suivante :

|===
| Nom | Description | Type 


 a| 
cBmcResetDurationMinutes
 a| 
Renvoie le temps écoulé entre les intervalles de réinitialisation.  L'intervalle doit toujours être égal à 0 une fois la commande terminée.
 a| 
entier

|===


== Exemple de demande

Les requêtes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
  "method": "DisableBmcColdReset",
  "params": {},
  "id" : 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
    "id": 1,
    "result": {
        "cBmcResetDurationMinutes": 0
    }
}
----


== Nouveautés depuis la version

12,0
