---
permalink: api/reference_element_api_deletekeyproviderkmip.html 
sidebar: sidebar 
keywords: KMIP,key provider,deleting,delete 
summary: 'Vous pouvez utiliser la méthode DeleteKeyProviderKmip pour supprimer le fournisseur de clés KMIP (Key Management Interoperability Protocol) inactif spécifié.' 
---
= DeleteKeyProviderKmip
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `DeleteKeyProviderKmip` méthode pour supprimer le fournisseur de clés KMIP (Key Management Interoperability Protocol) inactif spécifié.



== Paramètres

Cette méthode possède les paramètres d'entrée suivants :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
ID du fournisseur de clés
 a| 
L'identifiant du fournisseur de clés à supprimer.
 a| 
entier
 a| 
Aucune
 a| 
Oui

|===


== Valeurs de retour

Cette méthode ne renvoie aucune valeur.  L'opération de suppression est considérée comme réussie tant qu'aucune erreur ne survient.



== Exemple de demande

Les requêtes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
  "method": "DeleteKeyProviderKmip",
  "params": {
    "keyProviderID": "1"
    },
"id": 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
   "id": 1,
   "result":
      {}
}
----


== Nouveautés depuis la version

11,7
