---
permalink: api/reference_element_api_getprotectiondomainlayout.html 
sidebar: sidebar 
keywords: layout,custom,protection domain,protection domains,retrieve protection domains 
summary: 'Vous pouvez utiliser la méthode GetProtectionDomainLayout pour obtenir toutes les informations relatives au domaine de protection d"un cluster, notamment le châssis et le domaine de protection personnalisé auxquels appartient chaque nœud.' 
---
= ObtenirProtectionDomainLayout
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `GetProtectionDomainLayout` méthode permettant de renvoyer toutes les informations relatives au domaine de protection d'un cluster, y compris le châssis et le domaine de protection personnalisé auxquels appartient chaque nœud.



== Paramètre

Cette méthode ne nécessite aucun paramètre d'entrée.



== valeur de retour

Cette méthode a la valeur de retour suivante :

|===
| Nom | Description | Type 


 a| 
protectionDomainLayout
 a| 
Liste des nœuds, chacun avec ses domaines de protection associés.
 a| 
Liste JSON delink:reference_element_api_nodeprotectiondomains.html["Domaines de protection des nœuds"] objets.

|===


== Exemple de demande

Les requêtes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
  "method": "GetProtectionDomainLayout",
  "params": {},
  "id" : 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----

{
  "id": 1,
  "result": {
    "protectionDomainLayout": [
      {
        "nodeID": 1,
        "protectionDomains": [
          {
            "protectionDomainName": "QTFCR2914008D",
            "protectionDomainType": "chassis"
          },
          {
            "protectionDomainName": "Rack-1",
            "protectionDomainType": "custom"
          }
        ]
      },
      {
        "nodeID": 2,
        "protectionDomains": [
          {
            "protectionDomainName": "QTFCR291500EA",
            "protectionDomainType": "chassis"
          },
          {
            "protectionDomainName": "Rack-1",
            "protectionDomainType": "custom"
          }
        ]
      },
      {
        "nodeID": 3,
        "protectionDomains": [
          {
            "protectionDomainName": "QTFCR291500C3",
            "protectionDomainType": "chassis"
          },
          {
            "protectionDomainName": "Rack-2",
            "protectionDomainType": "custom"
          }
        ]
      },
      {
        "nodeID": 4,
        "protectionDomains": [
          {
            "protectionDomainName": "QTFCR291400E6",
            "protectionDomainType": "chassis"
          },
          {
            "protectionDomainName": "Rack-2",
            "protectionDomainType": "custom"
          }
        ]
      }
    ]
  }
}
----


== Nouveautés depuis la version

12,0
