---
permalink: api/reference_element_api_setntpinfo.html 
sidebar: sidebar 
keywords: ntp,info,set,setting,setntpinfo 
summary: 'Vous pouvez utiliser la méthode SetNtpInfo pour configurer NTP sur les nœuds du cluster.  Les valeurs que vous définissez avec cette interface s"appliquent à tous les nœuds du cluster.  Si un serveur de diffusion NTP diffuse périodiquement des informations horaires sur votre réseau, vous pouvez éventuellement configurer les nœuds en tant que clients de diffusion.' 
---
= DéfinirNtpInfo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `SetNtpInfo` Méthode de configuration NTP sur les nœuds du cluster.  Les valeurs que vous définissez avec cette interface s'appliquent à tous les nœuds du cluster.  Si un serveur de diffusion NTP diffuse périodiquement des informations horaires sur votre réseau, vous pouvez éventuellement configurer les nœuds en tant que clients de diffusion.



== Paramètres


NOTE: Veillez à utiliser des serveurs NTP internes à votre réseau, plutôt que les serveurs par défaut de l'installation.

Cette méthode possède les paramètres d'entrée suivants :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
serveurs
 a| 
Liste des serveurs NTP à ajouter à la configuration NTP de chaque nœud.
 a| 
tableau de chaînes
 a| 
Aucune
 a| 
Oui



 a| 
client de diffusion
 a| 
Permet à chaque nœud du cluster de fonctionner comme client de diffusion.
 a| 
booléen
 a| 
FAUX
 a| 
Non

|===


== Valeurs de retour

Cette méthode ne renvoie aucune valeur.



== Exemple de demande

Les requêtes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
   "method": "SetNtpInfo",
   "params": {
     "servers"  : [
       "ntpserver1.example.org",
       "ntpserver2.example.org",
       "ntpserver3.example.org"
     ],
     "broadcastclient" : false
   },
   "id" : 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
    "id" : 1,
    "result" : {}
}
----


== Nouveautés depuis la version

9,6
