---
permalink: api/reference_element_api_deletekeyserverkmip.html 
sidebar: sidebar 
keywords: KMIP,key server,deleting,delete 
summary: 'Vous pouvez utiliser la méthode DeleteKeyServerKmip pour supprimer un serveur de clés KMIP (Key Management Interoperability Protocol) existant.  Vous pouvez supprimer un serveur de clés, sauf s"il s"agit du dernier serveur attribué à son fournisseur et que ce fournisseur fournit des clés actuellement utilisées.' 
---
= SupprimerKeyServerKmip
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `DeleteKeyServerKmip` méthode pour supprimer un serveur de clés KMIP (Key Management Interoperability Protocol) existant.  Vous pouvez supprimer un serveur de clés, sauf s'il s'agit du dernier serveur attribué à son fournisseur et que ce fournisseur fournit des clés actuellement utilisées.



== Paramètres

Cette méthode possède les paramètres d'entrée suivants :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
ID du serveur de clés
 a| 
L'identifiant du serveur de clés KMIP à supprimer.
 a| 
entier
 a| 
Aucune
 a| 
Oui

|===


== Valeurs de retour

Cette méthode ne renvoie aucune valeur.  L'opération de suppression est considérée comme réussie en l'absence d'erreurs.



== Exemple de demande

Les requêtes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
  "method": "DeleteKeyServerKmip",
  "params": {
     "keyServerID": 15
  },
"id": 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
   "id": 1,
   "result":
      {}
}
----


== Nouveautés depuis la version

11,7
