---
permalink: api/reference_element_api_listdrivestats.html 
sidebar: sidebar 
keywords: cluster,list,listing,drive,drives,stats,statistics,listdrivestats 
summary: 'Vous pouvez utiliser la méthode ListDriveStats pour lister les mesures d"activité de haut niveau pour plusieurs disques du cluster.  Par défaut, cette méthode renvoie des statistiques pour tous les disques du cluster, et ces mesures sont cumulatives depuis l"ajout du disque au cluster.  Certaines valeurs renvoyées par cette méthode sont spécifiques aux disques de blocs, et d"autres aux disques de métadonnées.' 
---
= ListDriveStats
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `ListDriveStats` méthode permettant de lister les mesures d'activité de haut niveau pour plusieurs disques du cluster.  Par défaut, cette méthode renvoie des statistiques pour tous les disques du cluster, et ces mesures sont cumulatives depuis l'ajout du disque au cluster.  Certaines valeurs renvoyées par cette méthode sont spécifiques aux disques de blocs, et d'autres aux disques de métadonnées.



== Paramètre

Cette méthode possède le paramètre d'entrée suivant :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
lecteurs
 a| 
Liste des identifiants de lecteur (driveID) pour lesquels renvoyer des statistiques de lecteur.  Si vous omettez ce paramètre, les mesures de tous les disques sont renvoyées.
 a| 
tableau d'entiers
 a| 
Aucune
 a| 
Non

|===


== Valeurs de retour

Cette méthode renvoie les valeurs suivantes :

|===


| Nom | Description | Type 


 a| 
driveStats
 a| 
Liste des informations relatives à l'activité de chaque lecteur.
 a| 
xref:reference_element_api_drivestats.adoc[driveStats]tableau



 a| 
erreurs
 a| 
Cette liste contient l'identifiant du lecteur et le message d'erreur associé.  Il est toujours présent, et vide s'il n'y a pas d'erreurs.
 a| 
tableau d'objets JSON

|===


== Exemple de demande

Les requêtes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
  "id": 1,
  "method": "ListDriveStats",
  "params": {
    "drives":[22,23]
  }
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
  "id": 1,
  "result": {
    "driveStats": [
      {
        "driveID": 22,
        "failedDieCount": 0,
        "lifeRemainingPercent": 84,
        "lifetimeReadBytes": 30171004403712,
        "lifetimeWriteBytes": 103464755527680,
        "powerOnHours": 17736,
        "readBytes": 14656542,
         "readOps": 3624,
        "reallocatedSectors": 0,
        "reserveCapacityPercent": 100,
        "timestamp": "2016-03-01T00:19:24.782735Z",
        "totalCapacity": 300069052416,
        "usedCapacity": 1783735635,
        "usedMemory": 879165440,
        "writeBytes": 2462169894,
        "writeOps": 608802
      }
    ],
    "errors": [
      {
        "driveID": 23,
        "exception": {
          "message": "xStatCheckpointDoesNotExist",
          "name": "xStatCheckpointDoesNotExist"
        }
      }
    ]
  }
}
----


== Nouveautés depuis la version

9,6



== Trouver plus d'informations

xref:reference_element_api_getdrivestats.adoc[GetDriveStats]
