---
permalink: api/reference_element_api_cancelgroupclone.html 
sidebar: sidebar 
keywords:  
summary: 'Vous pouvez utiliser la méthode CancelGroupClone pour interrompre un processus de clonage en cours sur un groupe de volumes.  Lorsque vous annulez une opération de clonage de groupe, le système termine et supprime l"asyncHandle associé à l"opération.' 
---
= AnnulerGroupClone
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `CancelGroupClone` Méthode permettant d'arrêter un processus de clonage en cours sur un groupe de volumes.  Lorsque vous annulez une opération de clonage de groupe, le système termine et supprime l'asyncHandle associé à l'opération.



== Paramètre

Cette méthode possède le paramètre d'entrée suivant :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
groupCloneID
 a| 
L'identifiant du clone pour le processus de clonage en cours.
 a| 
entier
 a| 
Aucune
 a| 
Oui

|===


== Valeurs de retour

Cette méthode ne renvoie aucune valeur.



== Exemple de demande

Les requêtes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
   "method": "CancelGroupClone",
   "params": {
      "cloneID" : 5,
   },
   "id" : 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
  "id" : 1,
  "result" : {}
}
----


== Nouveautés depuis la version

9,6
