---
permalink: api/reference_element_api_testaddressavailability.html 
sidebar: sidebar 
keywords: ip,address,availability,test,testing,ensemble,cluster,testaddressavailability 
summary: Vous pouvez utiliser la méthode TestAddressAvailability pour vérifier si une adresse IP donnée est utilisée sur une interface au sein du cluster de stockage. 
---
= Disponibilité de l'adresse de test
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `TestAddressAvailability` méthode permettant de vérifier si une adresse IP donnée est utilisée sur une interface au sein du cluster de stockage.



== Paramètres

Cette méthode possède les paramètres d'entrée suivants :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
interface
 a| 
L'interface réseau cible (telle que eth0, Bond10G, etc.).
 a| 
chaîne
 a| 
Aucune
 a| 
Oui



 a| 
adresse
 a| 
L'adresse IP à rechercher sur l'interface cible.
 a| 
chaîne
 a| 
Aucune
 a| 
Oui



 a| 
VirtualNetworkTag
 a| 
L'ID du VLAN cible.
 a| 
entier
 a| 
Aucune
 a| 
Non



 a| 
temps mort
 a| 
Délai d'attente en secondes pour le test de l'adresse cible.
 a| 
entier
 a| 
5
 a| 
Non

|===


== Valeurs de retour

Cette méthode renvoie les valeurs suivantes :

|===


| Nom | Description | Type 


 a| 
adresse
 a| 
L'adresse IP testée.
 a| 
chaîne



 a| 
disponible
 a| 
Vrai si l'adresse IP demandée est utilisée, faux sinon.
 a| 
booléen

|===


== Exemple de demande

Les requêtes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
	"method": "TestAddressAvailability",
	"params": {
		"interface": "Bond10G",
		"address": "10.0.0.1",
		"virtualNetworkTag": 1234
	}
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
	"id": 1,
	"result": {
		"address":"10.0.0.1",
		"available": true
	}
}
----


== Nouveautés depuis la version

11,0
