---
permalink: api/reference_element_api_getclusterconfig.html 
sidebar: sidebar 
keywords: cluster,configuration,get,getting,config,getclusterconfig 
summary: 'Vous pouvez utiliser la méthode d"API GetClusterConfig pour obtenir des informations sur la configuration du cluster que le nœud utilise pour communiquer avec son cluster.' 
---
= Obtenir la configuration du cluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `GetClusterConfig` Méthode API permettant de renvoyer des informations sur la configuration du cluster que le nœud utilise pour communiquer avec son cluster.



== Paramètres

Cette méthode ne requiert aucun paramètre d'entrée.



== valeur de retour

Cette méthode a la valeur de retour suivante :

|===
| Nom | Description | Type 


 a| 
grappe
 a| 
Informations de configuration du cluster utilisées par le nœud pour communiquer avec le cluster.
 a| 
xref:reference_element_api_cluster.adoc[grappe]

|===


== Exemple de demande

Les requêtes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
   "method": "GetClusterConfig",
   "params": {},
   "id" : 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
  "id": 1,
  "result": {
    "cluster": {
      "cipi": "Bond10G",
      "cluster": "ClusterName",
      "ensemble": [
        "1:10.30.65.139",
        "2:10.30.65.140",
        "3:10.30.65.141"
      ],
      "fipsDriveConfiguration": true,
      "mipi": "Bond1G",
      "name": "xxx-en142",
      "nodeID": 4,
      "pendingNodeID": 0,
      "role": "Storage",
      "sipi": "Bond10G",
      "state": "Active",
      "version": "9.1.0"
    }
  }
}
----


== Nouveautés depuis la version

9,6
