---
permalink: api/reference_element_api_setloginbanner.html 
sidebar: sidebar 
keywords: terms,use,banner,configure,set,setting,setloginbanner,login 
summary: 'Vous pouvez utiliser la méthode SetLoginBanner pour configurer la bannière des conditions d"utilisation que les utilisateurs voient lorsqu"ils se connectent à l"interface web d"Element.' 
---
= Définir la bannière de connexion
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `SetLoginBanner` Méthode permettant de configurer la bannière des conditions d'utilisation que les utilisateurs voient lorsqu'ils se connectent à l'interface web d'Element.



== Paramètres

Cette méthode possède les paramètres d'entrée suivants :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
bannière
 a| 
Texte souhaité pour la bannière des conditions d'utilisation.  La longueur maximale autorisée est de 4 096 caractères.
 a| 
chaîne
 a| 
Aucune
 a| 
Non



 a| 
activé
 a| 
Statut de la bannière des conditions d'utilisation. Valeurs possibles :

* `true`La bannière des conditions d'utilisation s'affiche lors de la connexion à l'interface web.
* `false`La bannière des conditions d'utilisation ne s'affiche pas lors de la connexion à l'interface web.

 a| 
booléen
 a| 
Aucune
 a| 
Non

|===


== Valeurs de retour

Cette méthode renvoie les valeurs suivantes :

|===
| Nom | Description | Type 


 a| 
bannière
 a| 
Texte actuel de la bannière des conditions d'utilisation.  Cette valeur peut contenir du texte même lorsque la bannière est désactivée.
 a| 
chaîne



 a| 
activé
 a| 
Statut de la bannière des conditions d'utilisation. Valeurs possibles :

* Vrai : La bannière des conditions d’utilisation s’affiche lors de la connexion à l’interface Web.
* Faux : La bannière des conditions d'utilisation ne s'affiche pas lors de la connexion à l'interface Web.

 a| 
booléen

|===


== Exemple de demande

Les requêtes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
  "id": 3920,
  "method": "SetLoginBanner",
  "params": {
    "banner": "Welcome to NetApp!",
    "enabled": true
  }
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
  "id": 3920,
  "result": {
    "loginBanner": {
      "banner": "Welcome to NetApp!",
      "enabled": true
    }
  }
}
----


== Nouveautés depuis la version

10,0
