---
permalink: api/reference_element_api_creategroupsnapshot.html 
sidebar: sidebar 
keywords: volume,volumes,snapshot,snapshots,CreateGroupSnapshot,group,create,creating 
summary: 'Vous pouvez utiliser CreateGroupSnapshot pour créer une copie à un instant donné d"un groupe de volumes.' 
---
= Créer un instantané de groupe
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser `CreateGroupSnapshot` créer une copie à un instant donné d'un groupe de volumes.

Vous pouvez utiliser cet instantané ultérieurement comme sauvegarde ou restauration pour garantir la cohérence des données sur le groupe de volumes au moment où vous avez créé l'instantané.

*CLUSTER_FULLNESS*


NOTE: Vous pouvez créer des instantanés si le niveau de remplissage du cluster est à l'étape 1, 2 ou 3.  Vous ne pouvez pas créer d'instantanés lorsque le niveau de remplissage du cluster atteint le stade 4 ou 5.



== Paramètres

Cette méthode possède les paramètres d'entrée suivants :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
`attributes`
 a| 
Liste de paires nom-valeur au format objet JSON.
 a| 
objet JSON
 a| 
Aucune
 a| 
Non



 a| 
`enableRemoteReplication`
 a| 
Indique si l'instantané sera répliqué ou non sur un stockage distant. Valeurs possibles :

* `true`L'instantané sera répliqué sur un stockage distant.
* `false`L'instantané ne sera pas répliqué sur le stockage distant.

 a| 
booléen
 a| 
FAUX
 a| 
Non



| `ensureSerialCreation`  a| 
Indique que le snapshot ne doit pas être créé si une réplication de snapshot précédente est en cours.  Les valeurs possibles sont :

* `true`Cela garantit qu'une seule capture d'écran est répliquée à la fois.  La création d'un nouvel instantané échouera si une réplication d'un instantané précédent est toujours en cours.
* `false`: Défaut.  La création de cet instantané est autorisée même si une autre réplication d'instantané est toujours en cours.

| booléen | `false` | Non 


 a| 
`expirationTime`
 a| 
Spécifiez la durée après laquelle l'instantané peut être supprimé.  Ne peut pas être utilisé avec `retention` .  Si aucun des deux `expirationTime` , ou `retention` Si les paramètres sont spécifiés, l'instantané n'expirera pas.  Le format de l'heure est une chaîne de date ISO 8601 pour une expiration basée sur le temps ; sinon, elle n'expirera pas.  Une valeur de `null` permet de conserver l'instantané de manière permanente.  Une valeur de `fifo` permet de conserver l'instantané selon le principe du premier entré, premier sorti (FIFO), par rapport aux autres instantanés FIFO sur le volume.  L'API échouera si aucun espace FIFO n'est disponible.
 a| 
Chaîne de date ISO 8601
 a| 
Aucune
 a| 
Non



 a| 
`name`
 a| 
Nom de l'instantané de groupe.  Si aucun nom n'est saisi, la date et l'heure de la prise de vue du groupe seront utilisées.  La longueur maximale autorisée pour un nom est de 255 caractères.
 a| 
chaîne
 a| 
Aucune
 a| 
Non



 a| 
`retention`
 a| 
Ce paramètre est identique à celui-ci. `expirationTime` paramètre, sauf que le format de l'heure est HH:mm:ss.  Si aucun des deux `expirationTime` ni `retention` Si les paramètres sont spécifiés, l'instantané n'expirera pas.
 a| 
chaîne
 a| 
Aucune
 a| 
Non



 a| 
`snapMirrorLabel`
 a| 
Étiquette utilisée par le logiciel SnapMirror pour spécifier la politique de conservation des instantanés sur un point de terminaison SnapMirror .
 a| 
chaîne
 a| 
Aucune
 a| 
Non



 a| 
`volumes`
 a| 
Identifiant unique de l'image du volume à copier.
 a| 
tableau volumeID
 a| 
Aucune
 a| 
Oui

|===


== Valeurs de retour

Cette méthode renvoie les valeurs suivantes :

|===


| Nom | Description | Type 


 a| 
membres
 a| 
Liste des sommes de contrôle, des ID de volume et des ID d'instantané pour chaque membre du groupe.  Valeurs valides :

* Somme de contrôle : une courte chaîne de caractères représentant les données de l’instantané enregistré.  Cette somme de contrôle peut être utilisée ultérieurement pour comparer d'autres instantanés afin de détecter les erreurs dans les données.  (chaîne)
* snapshotID : Identifiant unique d’un instantané à partir duquel le nouvel instantané est créé.  L'identifiant de l'instantané doit provenir d'un instantané du volume spécifié.  (entier)
* volumeID : L’identifiant du volume source pour l’instantané.  (entier)

 a| 
tableau d'objets JSON



 a| 
groupSnapshotID
 a| 
Identifiant unique du nouvel instantané de groupe.
 a| 
ID de l'instantané du groupe



 a| 
groupSnapshot
 a| 
Objet contenant des informations sur l'instantané de groupe nouvellement créé.
 a| 
xref:reference_element_api_groupsnapshot.adoc[groupSnapshot]

|===


== Exemple de demande

Les requêtes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
   "method": "CreateGroupSnapshot",
   "params": {
      "volumes": [1,2]
   },
   "id": 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
  "id": 1,
  "result": {
    "groupSnapshot": {
      "attributes": {},
      "createTime": "2016-04-04T22:43:29Z",
      "groupSnapshotID": 45,
      "groupSnapshotUUID": "473b78a3-ef85-4541-9438-077306b2d3ca",
      "members": [
        {
          "attributes": {},
          "checksum": "0x0",
          "createTime": "2016-04-04T22:43:29Z",
          "enableRemoteReplication": false,
          "expirationReason": "None",
          "expirationTime": null,
          "groupID": 45,
          "groupSnapshotUUID": "473b78a3-ef85-4541-9438-077306b2d3ca",
          "name": "2016-04-04T22:43:29Z",
          "snapshotID": 3323,
          "snapshotUUID": "7599f200-0092-4b41-b362-c431551937d1",
          "status": "done",
          "totalSize": 5000658944,
          "virtualVolumeID": null,
          "volumeID": 1
        },
        {
          "attributes": {},
          "checksum": "0x0",
          "createTime": "2016-04-04T22:43:29Z",
          "enableRemoteReplication": false,
          "expirationReason": "None",
          "expirationTime": null,
          "groupID": 45,
          "groupSnapshotUUID": "473b78a3-ef85-4541-9438-077306b2d3ca",
          "name": "2016-04-04T22:43:29Z",
          "snapshotID": 3324,
          "snapshotUUID": "a0776a48-4142-451f-84a6-5315dc37911b",
          "status": "done",
          "totalSize": 6001000448,
          "virtualVolumeID": null,
          "volumeID": 2
        }
      ],
      "name": "2016-04-04T22:43:29Z",
      "status": "done"
    },
    "groupSnapshotID": 45,
    "members": [
      {
        "checksum": "0x0",
        "snapshotID": 3323,
        "snapshotUUID": "7599f200-0092-4b41-b362-c431551937d1",
        "volumeID": 1
      },
      {
        "checksum": "0x0",
        "snapshotID": 3324,
        "snapshotUUID": "a0776a48-4142-451f-84a6-5315dc37911b",
        "volumeID": 2
      }
    ]
  }
}
----


== Nouveautés depuis la version

9,6
