---
permalink: api/reference_element_api_listevents.html 
sidebar: sidebar 
keywords: cluster,list,listing,event,events,listevents 
summary: Vous pouvez utiliser la méthode ListEvents pour lister les événements détectés sur le cluster, triés du plus ancien au plus récent. 
---
= ListEvents
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `ListEvents` Méthode permettant de lister les événements détectés sur le cluster, triés du plus ancien au plus récent.



== Paramètres

Cette méthode possède les paramètres d'entrée suivants :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
ID du lecteur
 a| 
Indique que seuls les événements associés à cet ID de lecteur seront renvoyés.
 a| 
entier
 a| 
0
 a| 
Non



 a| 
endEventID
 a| 
Identifie la fin d'une plage d'identifiants d'événements à renvoyer.
 a| 
entier
 a| 
(illimité)
 a| 
Non



 a| 
fin de la publication
 a| 
Indique que seuls les événements publiés avant cette heure seront renvoyés.
 a| 
chaîne
 a| 
0
 a| 
Non



 a| 
fin du rapport
 a| 
Indique que seuls les événements signalés avant cette heure seront renvoyés.
 a| 
chaîne
 a| 
0
 a| 
Non



 a| 
type d'événement
 a| 
Spécifie le type d'événements à renvoyer.  Voirxref:reference_element_api_event.adoc[événement] pour les types d'événements possibles.
 a| 
chaîne
 a| 
0
 a| 
Non



 a| 
maxEvents
 a| 
Spécifie le nombre maximal d'événements à renvoyer.
 a| 
entier
 a| 
(illimité)
 a| 
Non



 a| 
ID du nœud
 a| 
Indique que seuls les événements ayant cet ID de nœud seront renvoyés.
 a| 
entier
 a| 
 a| 



 a| 
serviceID
 a| 
Indique que seuls les événements associés à cet ID de service seront renvoyés.
 a| 
 a| 
 a| 



 a| 
ID d'événement de démarrage
 a| 
Identifie le début d'une série d'événements à venir.
 a| 
entier
 a| 
0
 a| 
Non



 a| 
heure de début de publication
 a| 
Indique que seuls les événements publiés après cette heure seront renvoyés.
 a| 
chaîne
 a| 
0
 a| 
Non



 a| 
heure de début du rapport
 a| 
Indique que seuls les événements signalés après cette heure seront renvoyés.
 a| 
chaîne
 a| 
0
 a| 
Non

|===


== valeur de retour

Cette méthode a la valeur de retour suivante :

|===


| Nom | Description | Type 


 a| 
événements
 a| 
Liste des événements.
 a| 
xref:reference_element_api_event.adoc[événement]tableau

|===


== Exemple de demande

Les requêtes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
   "method": "ListEvents",
   "params": {
   },
   "id" : 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
  "id":1,
  "result":{
    "events":[
       {
          "details":
            {
              "paramGCGeneration":1431550800,
              "paramServiceID":2
            },
          "driveID":0,
          "eventID":2131,
          "eventInfoType":"gcEvent",
          "message":"GC Cluster Coordination Complete",
          "nodeID":0,
          "serviceID":2,
          "severity":0,
          "timeOfPublish":"2015-05-13T21:00:02.361354Z",
          "timeOfReport":"2015-05-13T21:00:02.361269Z"
       },{
          "details":
               {
                  "eligibleBS":[5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,24,25,26,27,28,29,30,31,40,41,42,43,44,45,46,47,52,53,54,55,56,57,58,59,60],
                  "generation":1431550800,
                  "participatingSS":[23,35,39,51]
               },
          "driveID":0,
          "eventID":2130,
          "eventInfoType":"gcEvent",
          "message":"GCStarted",
          "nodeID":0,
          "serviceID":2,
          "severity":0,
          "timeOfPublish":"2015-05-13T21:00:02.354128Z",
          "timeOfReport":"2015-05-13T21:00:02.353894Z"
       },{
          "details":"",
          "driveID":0,
          "eventID":2129,
          "eventInfoType":"tSEvent",
          "message":"return code:2 t:41286 tt:41286 qcc:1 qd:1 qc:1 vrc:1 tt:2 ct:Write etl:524288",
          "nodeID":0,
          "serviceID":0,
          "severity":0,
          "timeOfPublish":"2015-05-13T20:45:21.586483Z",
          "timeOfReport":"2015-05-13T20:45:21.586311Z"
       }
     ]
   }
}
----


== Nouveautés depuis la version

9,6
