---
permalink: api/reference_element_api_getnodestats.html 
sidebar: sidebar 
keywords: node,get,getting,stats,getnodestats 
summary: 'Vous pouvez utiliser la méthode GetNodeStats pour récupérer les mesures d"activité de haut niveau d"un nœud unique.' 
---
= GetNodeStats
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `GetNodeStats` méthode pour récupérer les mesures d'activité de haut niveau pour un nœud unique.



== Paramètre

Cette méthode possède le paramètre d'entrée suivant :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
ID du nœud
 a| 
Spécifie l'identifiant du nœud pour lequel des statistiques seront renvoyées.
 a| 
entier
 a| 
Aucune
 a| 
Oui

|===


== valeur de retour

Cette méthode a la valeur de retour suivante :

|===
| Nom | Description | Type 


 a| 
statistiques des nœuds
 a| 
Informations sur l'activité du nœud.
 a| 
xref:reference_element_api_nodestats.adoc[statistiques des nœuds]

|===


== Exemple de demande

Les requêtes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
   "method": "GetNodeStats",
   "params": {
     "nodeID": 5
   },
   "id": 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
   "id" : 1,
   "result" : {
     "nodeStats": {
       "cBytesIn": 1579657943924,
       "cBytesOut": 1683056745816,
       "count": 119529,
       "cpu": 0,
       "cpuTotal": 56289,
       "mBytesIn": 475476878,
       "mBytesOut": 269270423,
       "networkUtilizationCluster": 0,
       "networkUtilizationStorage": 0,
       "nodeHeat": {
         "primaryTotalHeat": 0.00098,
         "recentPrimaryTotalHeat": 0.00099,
         "recentTotalHeat": 0.00099,
         "totalHeat": 0.00098
       },
       "readLatencyUSecTotal": 10125300382,
       "readOps": 15640075,
       "sBytesIn": 1579657943924,
       "sBytesOut": 1683056745816,
       "ssLoadHistogram": {
         "Bucket0": 4873,
         "Bucket1To19": 6301620,
         "Bucket20To39": 396452,
         "Bucket40To59": 142,
         "Bucket60To79": 0,
         "Bucket80To100": 0
       },
       "timestamp": "2024-03-04T20:13:22.105428Z",
       "usedMemory": 106335510528,
       "writeLatencyUSecTotal": 7314512535,
       "writeOps": 59154830
     }
   }
}
----


== Nouveautés depuis la version

9,6
