---
permalink: api/reference_element_api_listnetworkinterfaces.html 
sidebar: sidebar 
keywords: network,interface,interfaces,list,listing,listnetworkinterfaces 
summary: 'Vous pouvez utiliser la méthode ListNetworkInterfaces pour lister les informations relatives à chaque interface réseau d"un nœud.  Cette méthode API est destinée à être utilisée sur des nœuds individuels ; l’authentification par identifiant et mot de passe est requise pour accéder à chaque nœud.  Toutefois, vous pouvez utiliser cette méthode sur le cluster si le paramètre force reçoit la valeur true lors de l"appel de la méthode.  Lorsque ce paramètre est utilisé sur le cluster, toutes les interfaces sont listées.' 
---
= Lister les interfaces réseau
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `ListNetworkInterfaces` méthode permettant de lister les informations relatives à chaque interface réseau d'un nœud.  Cette méthode API est destinée à être utilisée sur des nœuds individuels ; l’authentification par identifiant et mot de passe est requise pour accéder à chaque nœud.  Toutefois, vous pouvez utiliser cette méthode sur le cluster si le paramètre force reçoit la valeur true lors de l'appel de la méthode.  Lorsque ce paramètre est utilisé sur le cluster, toutes les interfaces sont listées.



== Paramètre

Cette méthode possède le paramètre d'entrée suivant :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
forcer
 a| 
Valeurs possibles :

* Vrai : Les informations concernant toutes les interfaces réseau du cluster sont renvoyées.
* Faux : Aucune information n'est renvoyée.

 a| 
booléen
 a| 
Aucune
 a| 
Non

|===


== valeur de retour

Cette méthode a la valeur de retour suivante :

|===


| Nom | Description | Type 


 a| 
interfaces
 a| 
Une liste d'informations de configuration pour chaque interface réseau du nœud de stockage (ou de l'ensemble du cluster de stockage, si force = `true` ).
 a| 
xref:reference_element_api_networkinterface.adoc[interface réseau]tableau

|===


== Exemple de demande

Les requêtes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
"method": "ListNetworkInterfaces",
"params": {},
"id" : 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
	"id": 1,
	"result": {
		"nodes": [
			{
				"nodeID": 1,
				"result": {
					"interfaces": [
						{
							"address": "10.117.80.32",
							"addressV6": "::",
							"broadcast": "10.117.95.255",
							"macAddress": "90:b1:1c:42:e0:1a",
							"mtu": 9000,
							"name": "Bond10G",
							"namespace": false,
							"netmask": "255.255.240.0",
							"status": "UpAndRunning",
							"type": "BondMaster",
							"virtualNetworkTag": 0
						},
						{
							"address": "10.117.64.32",
							"addressV6": "::",
							"broadcast": "10.117.79.255",
							"macAddress": "90:b1:1c:42:e0:1e",
							"mtu": 1500,
							"name": "Bond1G",
							"namespace": false,
							"netmask": "255.255.240.0",
							"status": "UpAndRunning",
							"type": "BondMaster",
							"virtualNetworkTag": 0
						},
						{
							"address": "0.0.0.0",
							"addressV6": "::",
							"broadcast": "0.0.0.0",
							"macAddress": "90:b1:1c:42:e0:1a",
							"mtu": 9000,
							"name": "eth0",
							"namespace": false,
							"netmask": "0.0.0.0",
							"status": "UpAndRunning",
							"type": "BondSlave",
							"virtualNetworkTag": 0
						},
						{
							"address": "127.0.0.1",
							"addressV6": "::",
							"broadcast": "0.0.0.0",
							"macAddress": "00:00:00:00:00:00",
							"mtu": 0,
							"name": "lo",
							"namespace": false,
							"netmask": "0.0.0.0",
							"status": "UpAndRunning",
							"type": "Loopback",
							"virtualNetworkTag": 0
						}
					]
				}
			}
		]
	}
}
----


== Nouveautés depuis la version

9,6
