---
permalink: api/reference_element_api_listdeletedvolumes.html 
sidebar: sidebar 
keywords: volume,volumes,marked,delete,deleted,deletion,list,listing,listdeletedvolumes 
summary: Vous pouvez utiliser la méthode ListDeletedVolumes pour récupérer la liste des volumes qui ont été marqués pour suppression et purgés du système. 
---
= Liste des volumes supprimés
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `ListDeletedVolumes` Méthode permettant de récupérer la liste des volumes marqués pour suppression et purgés du système.



== Paramètre

Cette méthode possède le paramètre d'entrée suivant :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
inclure les volumes virtuels
 a| 
Les volumes virtuels sont inclus par défaut dans la réponse.  Pour exclure les volumes virtuels, définissez la valeur sur false.
 a| 
booléen
 a| 
true
 a| 
Non

|===


== valeur de retour

Cette méthode a la valeur de retour suivante :

|===
| Nom | Description | Type 


 a| 
volumes
 a| 
Liste des volumes supprimés.
 a| 
xref:reference_element_api_volume.adoc[volume]tableau

|===


== Exemple de demande

Les requêtes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
   "method": "ListDeletedVolumes",
   "params": {},
   "id" : 1
}
----


== Exemple de réponse

Les réponses pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
    "id": 1,
    "result": {
        "volumes": [
            {
                "access": "readWrite",
                "accountID": 2,
                "attributes": {},
                "blockSize": 4096,
                "createTime": "2018-06-24T03:13:13Z",
                "deleteTime": "2018-07-22T16:12:39Z",
                "enable512e": true,
                "iqn": "iqn.2010-01.com.solidfire:0oto.deletethis.23",
                "name": "deleteThis",
                "purgeTime": "2016-07-23T00:12:39Z",
                "qos": {
                    "burstIOPS": 15000,
                    "burstTime": 60,
                    "curve": {
                        "4096": 100,
                        "8192": 160,
                        "16384": 270,
                        "32768": 500,
                        "65536": 1000,
                        "131072": 1950,
                        "262144": 3900,
                        "524288": 7600,
                        "1048576": 15000
                    },
                    "maxIOPS": 15000,
                    "minIOPS": 50
                },
                "scsiEUIDeviceID": "306f746f00000017f47acc0100000000",
                "scsiNAADeviceID": "6f47acc100000000306f746f00000017",
                "sliceCount": 1,
                "status": "deleted",
                "totalSize": 1396703232,
                "virtualVolumeID": null,
                "volumeAccessGroups": [],
                "volumeID": 23,
                "volumePairs": []
            }
        ]
    }
}
----


== Nouveautés depuis la version

9,6
