---
permalink: api/reference_element_api_setsnmpacl.html 
sidebar: sidebar 
keywords: setsnmpACL,set,setting,snmp,acl,permissions,access,control,list 
summary: 'Vous pouvez utiliser la méthode SetSnmpACL pour configurer les autorisations d"accès SNMP sur les nœuds du cluster.  Les valeurs que vous définissez avec cette interface s"appliquent à tous les nœuds du cluster, et les valeurs transmises remplacent toutes les valeurs définies lors d"un appel précédent à SetSnmpACL.  Notez également que les valeurs définies avec cette interface remplacent toutes les valeurs réseau ou usmUsers définies avec SetSnmpInfo.' 
---
= Définir la liste de contrôle d'accès SNMP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `SetSnmpACL` Méthode de configuration des autorisations d'accès SNMP sur les nœuds du cluster.  Les valeurs que vous définissez avec cette interface s'appliquent à tous les nœuds du cluster, et les valeurs transmises remplacent toutes les valeurs définies lors d'un appel précédent à `SetSnmpACL` .  Notez également que les valeurs définies avec cette interface remplacent toutes les valeurs réseau ou usmUsers définies avec `SetSnmpInfo` méthode.



== Paramètres

Cette méthode possède les paramètres d'entrée suivants :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
réseaux
 a| 
Liste des réseaux et du type d'accès dont ils disposent aux serveurs SNMP exécutés sur les nœuds du cluster.  Consultez l'objet réseau SNMP pour connaître les valeurs de réseau possibles.  Ce paramètre est requis si SNMP v3 est désactivé.
 a| 
xref:reference_element_api_network_snmp.adoc[réseau]
 a| 
Aucune
 a| 
Non



 a| 
utilisateurs américains
 a| 
Liste des utilisateurs et du type d'accès dont ils disposent aux serveurs SNMP exécutés sur les nœuds du cluster.  Ce paramètre est requis si SNMP v3 est activé.
 a| 
xref:reference_element_api_usmuser.adoc[utilisateur usm]
 a| 
Aucune
 a| 
Non

|===


== Valeurs de retour

Cette méthode ne renvoie aucune valeur.



== Exemple de demande

Les requêtes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
  "method": "SetSnmpACL",
  "params": {
    "usmUsers"  : [
      {
         "name": "jdoe",
         "access": "rouser",
         "secLevel": "priv",
         "password": "mypassword",
         "passphrase": "mypassphrase",
      }
    ]
  },
  "id" : 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
  "id" : 1,
  "result" : {}
}
----


== Nouveautés depuis la version

9,6



== Trouver plus d'informations

xref:reference_element_api_setsnmpinfo.adoc[Définir les informations SNMP]
