---
permalink: api/reference_element_api_getaccountbyid.html 
sidebar: sidebar 
keywords: accounts,account,get,getting,GetAccountByID,ID 
summary: 'Vous pouvez utiliser GetAccountByID pour obtenir des informations sur un compte spécifique, à partir de son identifiant de compte (accountID).' 
---
= ObtenirCompteParID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser `GetAccountByID` pour obtenir des détails sur un compte spécifique, à partir de son identifiant de compte.



== Paramètres

Cette méthode possède les paramètres d'entrée suivants :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
identifiant de compte
 a| 
L'identifiant du compte pour lequel obtenir des informations.
 a| 
entier
 a| 
Aucune
 a| 
Oui

|===


== valeur de retour

Cette méthode a la valeur de retour suivante :

|===
| Nom | Description | Type 


 a| 
compte
 a| 
Détails du compte.
 a| 
xref:reference_element_api_account.adoc[compte]

|===


== Exemple de demande

Les requêtes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
   "method": "GetAccountByID",
   "params": {
     "accountID"  : 3
   },
   "id" : 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
    "account": {
        "attributes": {},
        "username": "account3",
        "targetSecret": "targetsecret",
        "volumes": [],
        "enableChap": true,
        "status": "active",
        "accountID": 3,
        "storageContainerID": "abcdef01-1234-5678-90ab-cdef01234567",
        "initiatorSecret": "initiatorsecret"
    }
}
----


== Nouveautés depuis la version

9,6
