---
permalink: api/reference_element_api_getsnmpstate.html 
sidebar: sidebar 
keywords: snmp,state,get,getting,getsnmpstate 
summary: 'Vous pouvez utiliser la méthode GetSnmpState pour obtenir l"état actuel de la fonctionnalité SNMP.' 
---
= Obtenir l'état SNMP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `GetSnmpState` méthode pour obtenir l'état actuel de la fonctionnalité SNMP.



== Paramètres

Cette méthode ne requiert aucun paramètre d'entrée.



== Valeurs de retour

Cette méthode renvoie les valeurs suivantes :

|===
| Nom | Description | Type 


 a| 
activé
 a| 
Valeurs possibles :

* true
* FAUX


La valeur par défaut est faux. Renvoie vrai si les nœuds du cluster sont configurés pour SNMP.
 a| 
booléen



 a| 
snmpV3Enabled
 a| 
Valeurs possibles :

* true
* FAUX


La valeur par défaut est faux. Renvoie vrai si les nœuds du cluster sont configurés pour SNMP v3.
 a| 
booléen

|===


== Exemple de demande

Les requêtes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
  "method": "GetSnmpState",
  "params": {},
  "id" : 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
  "id" : 1,
  "result" : {
   "enabled": true,
   "snmpV3Enabled": false
   }
}
----


== Nouveautés depuis la version

9,6



== Trouver plus d'informations

xref:reference_element_api_setsnmpacl.adoc[Définir la liste de contrôle d'accès SNMP]
