---
permalink: api/reference_element_api_addinitiatorstovolumeaccessgroup.html 
sidebar: sidebar 
keywords: addinitiatorstovolumeaccessgroup,add,adding,initiators,initiator,volume,access,group 
summary: 'Vous pouvez utiliser la méthode AddInitiatorsToVolumeAccessGroup pour ajouter des initiateurs à un groupe d"accès aux volumes spécifié.' 
---
= Ajouter les initiateurs au groupe d'accès au volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `AddInitiatorsToVolumeAccessGroup` Méthode permettant d'ajouter des initiateurs à un groupe d'accès au volume spécifié.

Le format accepté d'un IQN d'initiateur est iqn.yyyy-mm, où y et m sont des chiffres, suivis d'un texte qui ne doit contenir que des chiffres, des caractères alphabétiques minuscules, un point (.), deux-points (:) ou un tiret (-). Voir l’exemple suivant :

[listing]
----
iqn.2010-01.com.solidfire:17oi.solidfire-0.1
----
Le format accepté d'un WWPN d'initiateur Fibre Channel est Aa:bB:CC:dd:11:22:33:44, ou AabBCCdd11223344. Voir l’exemple suivant :

[listing]
----
21:00:00:0e:1e:11:f1:81
----


== Paramètres

Cette méthode possède les paramètres d'entrée suivants :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
initiateurs
 a| 
Liste des identifiants ou noms d'initiateurs (IQN et WWPN) à inclure dans le groupe d'accès au volume.  Si vous transmettez une liste de noms d'initiateurs, ces derniers sont créés s'ils n'existent pas déjà.  Si vous transmettez une liste d'identifiants d'initiateurs, la méthode renvoie une erreur si l'un des initiateurs n'existe pas déjà.

Il est déconseillé de transmettre les noms des initiateurs ; vous devez utiliser les identifiants des initiateurs chaque fois que cela est possible.
 a| 
tableau d'entiers ou tableau de chaînes de caractères (obsolète)
 a| 
 a| 
Oui



 a| 
volumeAccessGroupID
 a| 
L'identifiant du groupe d'accès au volume auquel ajouter l'initiateur.
 a| 
entier
 a| 
Aucune
 a| 
Oui

|===


== valeur de retour

Cette méthode a la valeur de retour suivante :

|===


| Nom | Description | Type 


 a| 
volumeAccessGroup
 a| 
Un objet contenant des informations sur le groupe d'accès aux volumes nouvellement modifié.
 a| 
xref:reference_element_api_volumeaccessgroup.adoc[volumeAccessGroup]

|===


== Exemple de demande

Les requêtes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
  "id": 13171,
  "method": "AddInitiatorsToVolumeAccessGroup",
  "params": {
    "initiators": [116,117],
    "volumeAccessGroupID": 96
  }
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
  "id": 13171,
  "result": {
    "volumeAccessGroup": {
      "attributes": {},
      "deletedVolumes": [
        327
      ],
      "initiatorIDs": [
        116,
        117
      ],
      "initiators": [
        "iqn.1993-08.org.debian:01:181324777",
        "iqn.1993-08.org.debian:01:181324888"
      ],
      "name": "northbanktest",
      "volumeAccessGroupID": 96,
      "volumes": [
        346
      ]
    }
  }
}
----


== Nouveautés depuis la version

9,6
