---
permalink: api/reference_element_api_listsnapmirroraggregates.html 
sidebar: sidebar 
keywords: snapmirror,aggregate,aggregates,list,listing,listsnapmirroraggregates 
summary: 'L"interface utilisateur Web du logiciel Element utilise la méthode ListSnapMirrorAggregates pour lister tous les agrégats SnapMirror disponibles sur le système ONTAP distant.  Un agrégat décrit un ensemble de ressources de stockage physique.' 
---
= ListSnapMirrorAggregates
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'interface utilisateur Web du logiciel Element utilise `ListSnapMirrorAggregates` Méthode permettant de lister tous les agrégats SnapMirror disponibles sur le système ONTAP distant.  Un agrégat décrit un ensemble de ressources de stockage physique.



== Paramètre

Cette méthode possède le paramètre d'entrée suivant :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
snapMirrorEndpointID
 a| 
Ne renvoyez que les agrégats associés à l'ID de point de terminaison spécifié.  Si aucun identifiant de point de terminaison n'est fourni, le système liste les agrégats de tous les points de terminaison SnapMirror connus.
 a| 
entier
 a| 
Aucune
 a| 
Non

|===


== valeur de retour

Cette méthode a la valeur de retour suivante :

|===


| Nom | Description | Type 


 a| 
snapMirrorAggregates
 a| 
Liste des agrégats disponibles sur le système de stockage ONTAP .
 a| 
xref:reference_element_api_snapmirroraggregate.adoc[snapMirrorAggregate]tableau

|===


== Nouveautés depuis la version

10,1
