---
permalink: api/reference_element_api_createidpconfiguration.html 
sidebar: sidebar 
keywords: IdP,idp,configuration,create,creating 
summary: 'Vous pouvez utiliser la méthode CreateIpdConfiguration pour créer une relation de confiance potentielle pour l"authentification à l"aide d"un fournisseur d"identité tiers (IdP) pour le cluster.  Un certificat de fournisseur de services SAML est requis pour la communication avec le fournisseur d"identité.  Ce certificat est généré conformément aux exigences et renvoyé par cet appel API.' 
---
= Créer une configuration Idp
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `CreateIpdConfiguration` méthode pour créer une relation de confiance potentielle pour l'authentification utilisant un fournisseur d'identité tiers (IdP) pour le cluster.  Un certificat de fournisseur de services SAML est requis pour la communication avec le fournisseur d'identité.  Ce certificat est généré conformément aux exigences et renvoyé par cet appel API.



== Paramètres

Cette méthode possède les paramètres d'entrée suivants :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
Métadonnées idp
 a| 
Métadonnées IdP à stocker.
 a| 
chaîne
 a| 
Aucune
 a| 
Oui



 a| 
Nom idp
 a| 
Nom utilisé pour identifier un fournisseur d'identité (IdP) pour l'authentification unique SAML 2.0.
 a| 
chaîne
 a| 
Aucune
 a| 
Oui

|===


== Valeurs de retour

Cette méthode a la valeur de retour suivante :

|===


| Nom | Description | Type 


 a| 
idpConfigInfo
 a| 
Informations concernant la configuration du fournisseur d'identité tiers (IdP).
 a| 
link:reference_element_api_idpconfiginfo.html["idpConfigInfo"]

|===


== Exemple de demande

Les requêtes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
    "method": "CreateIdpConfiguration",
    "params": {
        "idpMetadata": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>
             <EntityDescriptor
               xmlns=\"urn:oasis:names:tc:SAML:2.0:metadata\"
               xmlns:ds=\"http://www.w3.org/2000/09/xmldsig#\"
               xmlns:shibmd=\"urn:mace:shibboleth:metadata:1.0\"
               xmlns:xml=\"http://www.w3.org/XML/1998/namespace\"
               ...</Organization>
             </EntityDescriptor>",
        "idpName": "https://provider.name.url.com"
    },
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
    "result": {
        "idpConfigInfo": {
        "enabled": false,
        "idpConfigurationID": "f983c602-12f9-4c67-b214-bf505185cfed",
        "idpMetadata": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\r\n
        <EntityDescriptor xmlns=\"urn:oasis:names:tc:SAML:2.0:metadata\"\r\n
        xmlns:ds=\"http://www.w3.org/2000/09/xmldsig#\"\r\n
        xmlns:shibmd=\"urn:mace:shibboleth:metadata:1.0\"\r\n
        xmlns:xml=\"http://www.w3.org/XML/1998/namespace\"\r\n
        ... </Organization>\r\n
        </EntityDescriptor>",
        "idpName": "https://privider.name.url.com",
        "serviceProviderCertificate": "-----BEGIN CERTIFICATE-----\n
        MIID...SlBHi\n
        -----END CERTIFICATE-----\n",
        "spMetadataUrl": "https://10.193.100.100/auth/ui/saml2"
        }
    }
}
----


== Nouveautés depuis la version

12,0
