---
permalink: api/reference_element_api_getnodehardwareinfo.html 
sidebar: sidebar 
keywords: node,hardware,info,get,getting,getnodehardwareinfo 
summary: 'Vous pouvez utiliser la méthode GetNodeHardwareInfo pour obtenir toutes les informations matérielles et l"état du nœud spécifié.  Cela inclut généralement les fabricants, les fournisseurs, les versions et autres informations d"identification matérielle associées.' 
---
= GetNodeHardwareInfo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `GetNodeHardwareInfo` Méthode permettant de renvoyer toutes les informations matérielles et l'état du nœud spécifié.  Cela inclut généralement les fabricants, les fournisseurs, les versions et autres informations d'identification matérielle associées.



== Paramètre

Cette méthode possède le paramètre d'entrée suivant :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
ID du nœud
 a| 
L'identifiant du nœud pour lequel des informations matérielles sont demandées.  Des informations concernant un nœud Fibre Channel sont renvoyées si un nœud Fibre Channel est spécifié.
 a| 
entier
 a| 
Aucune
 a| 
Oui

|===


== valeur de retour

Cette méthode a la valeur de retour suivante :

|===
| Nom | Description | Type 


 a| 
Informations sur le matériel du nœud
 a| 
Informations matérielles pour l'identifiant de nœud spécifié.  Chaque objet de cette sortie est étiqueté avec l'identifiant du nœud donné.
 a| 
xref:reference_element_api_hardwareinfo.adoc[Informations matérielles]

|===


== Exemple de demande

Les requêtes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
   "method": "GetNodeHardwareInfo",
   "params": {
     "nodeID": 1
   },
"id" : 1
}
----


== Exemple de réponse

En raison de sa longueur, cet exemple de réponse est documenté dans un sujet supplémentaire.



== Nouveautés depuis la version

9,6



== Trouver plus d'informations

xref:reference_element_api_response_example_getnodehardwareinfo_fibre_channel.adoc[GetNodeHardwareInfo (sortie pour les nœuds Fibre Channel)]

xref:reference_element_api_response_example_getnodehardwareinfo.adoc[GetNodeHardwareInfo (sortie pour iSCSI)]
