---
permalink: api/reference_element_api_getclustercapacity.html 
sidebar: sidebar 
keywords: cluster,capacity,getting,get,measurements,measure,deduplication,GetClusterCapacity 
summary: 'Vous pouvez utiliser GetClusterCapacity pour obtenir des mesures de capacité de haut niveau pour un cluster de stockage entier.  Cette méthode renvoie des champs que vous pouvez utiliser pour calculer les taux d"efficacité affichés dans l"interface utilisateur Web d"Element.  Vous pouvez utiliser les calculs d"efficacité dans les scripts pour obtenir les taux d"efficacité du provisionnement fin, de la déduplication, de la compression et de l"efficacité globale.' 
---
= Obtenir la capacité du cluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `GetClusterCapacity` renvoyer des mesures de capacité de haut niveau pour un cluster de stockage entier.  Cette méthode renvoie des champs que vous pouvez utiliser pour calculer les taux d'efficacité affichés dans l'interface utilisateur Web d'Element.  Vous pouvez utiliser les calculs d'efficacité dans les scripts pour obtenir les taux d'efficacité du provisionnement fin, de la déduplication, de la compression et de l'efficacité globale.



== Calculs d'efficacité

Utilisez les équations suivantes pour calculer le provisionnement fin, la déduplication et la compression.  Ces équations s'appliquent à l'élément 8.2 et aux suivants.

* Facteur d'approvisionnement fin = (blocs non nuls + blocs nuls) / blocs non nuls
* Facteur de déduplication = (blocs non nuls + blocs non nuls de l'instantané) / blocs uniques
* Facteur de compression = (blocs uniques * 4096) / (espace utilisé par les blocs uniques * 0,93)




== calcul du taux d'efficacité global

Utilisez l'équation suivante pour calculer l'efficacité globale du cluster à partir des résultats des calculs d'efficacité de l'allocation fine, de la déduplication et de la compression.

* Facteur d'efficacité = Facteur d'approvisionnement fin * Facteur de déduplication * Facteur de compression




== Paramètres

Cette méthode ne requiert aucun paramètre d'entrée.



== valeur de retour

Cette méthode a la valeur de retour suivante :

|===
| Nom | Description | Type 


 a| 
capacité du cluster
 a| 
Mesures de capacité pour le cluster de stockage.
 a| 
xref:reference_element_api_clustercapacity.adoc[capacité du cluster]

|===


== Exemple de demande

Les requêtes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
   "method": "GetClusterCapacity",
   "params": {},
   "id" : 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
  "id": 1,
  "result": {
    "clusterCapacity": {
      "activeBlockSpace": 236015557096,
      "activeSessions": 20,
      "averageIOPS": 0,
      "clusterRecentIOSize": 0,
      "currentIOPS": 0,
      "maxIOPS": 150000,
      "maxOverProvisionableSpace": 259189767127040,
      "maxProvisionedSpace": 51837953425408,
      "maxUsedMetadataSpace": 404984011161,
      "maxUsedSpace": 12002762096640,
      "nonZeroBlocks": 310080350,
      "peakActiveSessions": 20,
      "peakIOPS": 0,
      "provisionedSpace": 1357931085824,
      "snapshotNonZeroBlocks": 0,
      "timestamp": "2016-10-17T21:24:36Z",
      "totalOps": 1027407650,
      "uniqueBlocks": 108180156,
      "uniqueBlocksUsedSpace": 244572686901,
      "usedMetadataSpace": 8745762816,
      "usedMetadataSpaceInSnapshots": 8745762816,
      "usedSpace": 244572686901,
      "zeroBlocks": 352971938
    }
  }
}
----


== Nouveautés depuis la version

9,6
