---
permalink: api/reference_element_api_listauthsessionbyusername.html 
sidebar: sidebar 
keywords: username,sessions,authentication sessions,list 
summary: 'Vous pouvez utiliser la méthode ListAuthSessionsByUsername pour lister toutes les sessions d"authentification de l"utilisateur spécifié.  Un appelant ne faisant pas partie du groupe d"accès ClusterAdmins / Administrateur ne peut lister que ses propres sessions.  Un appelant disposant des privilèges ClusterAdmins / Administrateur peut lister les sessions appartenant à n"importe quel utilisateur.' 
---
= ListAuthSessionsByUsername
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `ListAuthSessionsByUsername` Méthode permettant de lister toutes les sessions d'authentification pour l'utilisateur spécifié.  Un appelant ne faisant pas partie du groupe d'accès ClusterAdmins / Administrateur ne peut lister que ses propres sessions.  Un appelant disposant des privilèges ClusterAdmins / Administrateur peut lister les sessions appartenant à n'importe quel utilisateur.



== Paramètres

Cette méthode possède les paramètres d'entrée suivants :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
méthode d'authentification
 a| 
Méthode d'authentification des sessions utilisateur à lister.  Seul un appelant appartenant au groupe d'accès ClusterAdmins/Administrator peut fournir ce paramètre.  Les valeurs possibles sont :

* *authMethod=Cluster* spécifie le nom d'utilisateur ClusterAdmin.
* *authMethod=Ldap* spécifie le DN LDAP de l'utilisateur.
* *authMethod=Idp* spécifie soit l'UUID ou le NameID du fournisseur d'identité de l'utilisateur.  Si le fournisseur d'identité n'est pas configuré pour renvoyer l'une ou l'autre option, ceci spécifie un UUID aléatoire émis lors de la création de la session.

 a| 
méthode d'authentification
 a| 
Aucune
 a| 
Oui



 a| 
nom d'utilisateur
 a| 
Identifiant unique de l'utilisateur.
 a| 
chaîne
 a| 
Aucune
 a| 
Oui

|===


== Valeurs de retour

Cette méthode a la valeur de retour suivante :

|===


| Nom | Description | Type 


 a| 
séances
 a| 
Liste des informations de session pour les sessions d'authentification.
 a| 
link:reference_element_api_authsessioninfo.html["authSessionInfo"]

|===


== Exemple de demande

Les requêtes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
    "method": "ListAuthSessionsByUsername",
    "authMethod": "Cluster",
    "username": "admin"
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
"sessions": [
      {
        "accessGroupList": [
          "administrator"
        ],
        "authMethod": "Cluster",
        "clusterAdminIDs": [
          1
        ],
        "finalTimeout": "2020-03-14T19:21:24Z",
        "idpConfigVersion": 0,
        "lastAccessTimeout": "2020-03-11T19:51:24Z",
        "sessionCreationTime": "2020-03-11T19:21:24Z",
        "sessionID": "b12bfc64-f233-44df-8b9f-6fb6c011abf7",
        "username": "admin"
      }
    ]
}
----


== Nouveautés depuis la version

12,0
