---
permalink: api/reference_element_api_iscsiauthentication.html 
sidebar: sidebar 
keywords: ISCSIAuthentication,iscsi,authentication 
summary: 'L"objet ISCSIAuthentication contient des informations d"authentification concernant une session ISCSI.' 
---
= Authentification ISCSI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'objet ISCSIAuthentication contient des informations d'authentification concernant une session ISCSI.



== membres de l'objet

Cet objet contient les membres suivants :

|===
| Nom | Description | Type 


 a| 
méthode d'authentification
 a| 
La méthode d'authentification utilisée lors de la connexion à une session iSCSI, par exemple CHAP ou Aucune.
 a| 
chaîne



 a| 
chapAlgorithme
 a| 
L'algorithme CHAP utilisé, par exemple, MD5, SHA1*, SHA-256* ou SHA3-256*
 a| 
chaîne



 a| 
Nom d'utilisateur du chapitre
 a| 
Le nom d'utilisateur CHAP spécifié par l'initiateur lors de la connexion à une session iSCSI.
 a| 
chaîne



 a| 
direction
 a| 
Le sens de l'authentification, par exemple unidirectionnel (initiateur uniquement) ou bidirectionnel (initiateur et cible).
 a| 
chaîne

|===
* Disponible à partir de l'élément 12.7.

