---
permalink: api/reference_element_api_listpendingactivenodes.html 
sidebar: sidebar 
keywords: cluster,list,listing,pending,active,node,nodes,listpendingactivenodes 
summary: 'Vous pouvez utiliser la méthode ListPendingActiveNodes pour lister les nœuds du cluster qui se trouvent dans l"état PendingActive, entre les états en attente et actif.  Les nœuds dans cet état sont réinitialisés à l"image d"usine.' 
---
= Liste des nœuds actifs en attente
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `ListPendingActiveNodes` méthode permettant de lister les nœuds du cluster qui se trouvent dans l'état PendingActive, entre les états en attente et actif.  Les nœuds dans cet état sont réinitialisés à l'image d'usine.



== Paramètres

Cette méthode ne requiert aucun paramètre d'entrée.



== valeur de retour

Cette méthode a la valeur de retour suivante :

|===
| Nom | Description | Type 


 a| 
nœuds actifs en attente
 a| 
Liste des objets détaillant les informations relatives à tous les nœuds PendingActive du système.
 a| 
xref:reference_element_api_pendingactivenode.adoc[en attenteNœudActif]tableau

|===


== Exemple de demande

Les requêtes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
   "method": "ListPendingActiveNodes",
   "params": {},
   "id" : 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
  id: null,
  result: {
    pendingActiveNodes: [
    {
      activeNodeKey: "5rPHP3lTAO",
      assignedNodeID: 5,
      asyncHandle: 2,
      cip: "10.10.5.106",
      mip: "192.168.133.106",
      pendingNodeID: 1,
      platformInfo: {
        chassisType: "R620",
        cpuModel: "Intel(R) Xeon(R) CPU E5-2640 0 @ 2.50GHz",
        nodeMemoryGB: 72,
        nodeType: "SF3010"
      },
     sip: "10.10.5.106",
     softwareVersion: "9.0.0.1077"
    }
    ]
  }
}
----


== Nouveautés depuis la version

9,6
