---
permalink: api/reference_element_api_listvolumes.html 
sidebar: sidebar 
keywords: volume,volumes,list,listing,listvolumes 
summary: Vous pouvez utiliser la méthode ListVolumes pour obtenir la liste des volumes qui se trouvent dans un cluster.  Vous pouvez spécifier les volumes que vous souhaitez renvoyer dans la liste en utilisant les paramètres disponibles. 
---
= Liste des volumes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `ListVolumes` méthode pour obtenir la liste des volumes appartenant à un cluster.  Vous pouvez spécifier les volumes que vous souhaitez renvoyer dans la liste en utilisant les paramètres disponibles.



== Paramètres

Cette méthode possède les paramètres d'entrée suivants :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
comptes
 a| 
Seuls les volumes appartenant aux comptes que vous spécifiez ici sont renvoyés.  Incompatible avec le paramètre volumeIDs.
 a| 
tableau d'entiers
 a| 
Aucune
 a| 
Non



 a| 
inclure les volumes virtuels
 a| 
Les volumes virtuels sont inclus par défaut dans la réponse.  Pour exclure les volumes virtuels, définissez la valeur sur false.
 a| 
booléen
 a| 
true
 a| 
Non



 a| 
estPairé
 a| 
Renvoie les volumes appariés ou non appariés. Valeurs possibles :

* vrai : Renvoie tous les volumes appariés.
* false : Renvoie tous les volumes non appariés.

 a| 
booléen
 a| 
Aucune
 a| 
Non



 a| 
limite
 a| 
Permet de définir le nombre maximal de résultats de volume renvoyés.  Incompatible avec le paramètre volumeIDs.
 a| 
entier
 a| 
10000
 a| 
Non



 a| 
ID de volume de départ
 a| 
Seuls les volumes dont l'identifiant est supérieur ou égal à cette valeur sont renvoyés.  Incompatible avec le paramètre volumeIDs.
 a| 
entier
 a| 
Aucune
 a| 
Non



 a| 
ID de volume
 a| 
Liste des identifiants de volume.  Si vous spécifiez ce paramètre, les autres paramètres ne s'appliqueront qu'à cet ensemble de volumes.  Mutuellement exclusif avec les paramètres accounts, startVolumeID et limit.
 a| 
tableau d'entiers
 a| 
Non
 a| 
Non



 a| 
nom_du_volume
 a| 
Seules les informations relatives à l'objet volume correspondant au nom du volume sont renvoyées.
 a| 
chaîne
 a| 
Non
 a| 
Non



 a| 
État du volume
 a| 
Seuls les volumes dont le statut est égal à la valeur de statut sont renvoyés. Valeurs possibles :

* création
* prise de photos
* actif
* supprimé

 a| 
chaîne
 a| 
Non
 a| 
Non

|===


== valeur de retour

Cette méthode a la valeur de retour suivante :

|===


| Nom | Description | Type 


 a| 
volumes
 a| 
Liste des volumes.
 a| 
xref:reference_element_api_volume.adoc[volume]tableau

|===


== Exemple de demande

Les requêtes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
  "method": "ListVolumes",
    "params": {
        "volumeIDs": [1],
        "volumeStatus": "active",
        "isPaired": "false"
    },
    "id": 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
    "id": 1,
    "result": {
        "volumes": [
            {
                "access": "readWrite",
                "accountID": 1,
                "attributes": {},
                "blockSize": 4096,
                "createTime": "2016-03-28T14:39:05Z",
                "deleteTime": "",
                "enable512e": true,
                "iqn": "iqn.2010-01.com.solidfire:testvolume1.1",
                "name": "testVolume1",
                "purgeTime": "",
                "qos": {
                    "burstIOPS": 15000,
                    "burstTime": 60,
                    "curve": {
                        "4096": 100,
                        "8192": 160,
                        "16384": 270,
                        "32768": 500,
                        "65536": 1000,
                        "131072": 1950,
                        "262144": 3900,
                        "524288": 7600,
                        "1048576": 15000
                    },
                    "maxIOPS": 15000,
                    "minIOPS": 50
                },
                "scsiEUIDeviceID": "6a79617900000001f47acc0100000000",
                "scsiNAADeviceID": "6f47acc1000000006a79617900000001",
                "sliceCount": 1,
                "status": "active",
                "totalSize": 5000658944,
                "virtualVolumeID": null,
                "volumeAccessGroups": [],
                "volumeID": 1,
                "volumePairs": []
            }
        ]
    }
}
----


== Nouveautés depuis la version

9,6
