---
permalink: api/reference_element_api_disableencryptionatrest.html 
sidebar: sidebar 
keywords: element, api, encryption, disable, disabling, at rest, rest, DisableEncryptionAtRest 
summary: 'Vous pouvez utiliser la méthode DisableEncryptionAtRest pour supprimer le chiffrement qui a été précédemment appliqué au cluster à l"aide de la méthode EnableEncryptionAtRest.  Cette méthode de désactivation est asynchrone et renvoie une réponse avant que le chiffrement ne soit désactivé.  Vous pouvez utiliser la méthode GetClusterInfo pour interroger le système et voir quand le processus est terminé.' 
---
= Désactiver le chiffrement au repos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `DisableEncryptionAtRest` méthode pour supprimer le chiffrement qui était précédemment appliqué au cluster en utilisant la `EnableEncryptionAtRest` méthode.  Cette méthode de désactivation est asynchrone et renvoie une réponse avant que le chiffrement ne soit désactivé.  Vous pouvez utiliser le `GetClusterInfo` méthode permettant d'interroger le système pour savoir quand le processus est terminé.

[NOTE]
====
* Cette méthode ne permet pas de désactiver le chiffrement logiciel au repos.  Pour désactiver le chiffrement logiciel au repos, vous devezlink:reference_element_api_createcluster.html["créer un nouveau cluster"] avec le chiffrement logiciel au repos désactivé.
* Pour consulter l'état actuel du chiffrement au repos, du chiffrement logiciel au repos ou des deux sur le cluster, utilisez link:../api/reference_element_api_getclusterinfo.html["méthode d'obtention d'informations sur le cluster"]. Vous pouvez utiliser le `GetSoftwareEncryptionAtRestInfo` link:../api/reference_element_api_getsoftwareencryptionatrestinfo.html["méthode pour obtenir des informations sur la manière dont le cluster chiffre les données au repos"].


====


== Paramètres

Cette méthode ne requiert aucun paramètre d'entrée.



== Valeurs de retour

Cette méthode ne renvoie aucune valeur.



== Exemple de demande

Les requêtes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
   "method": "DisableEncryptionAtRest",
   "params": {},
   "id": 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
   "id" : 1,
  "result" : {}
}
----


== Nouveautés depuis la version

9,6

[discrete]
== Trouver plus d'informations

* link:../api/reference_element_api_getclusterinfo.html["Obtenir les informations du cluster"]
* https://docs.netapp.com/us-en/element-software/index.html["Documentation logicielle SolidFire et Element"]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["Documentation relative aux versions antérieures des produits NetApp SolidFire et Element"^]

