---
permalink: api/reference_element_api_setdefaultqos.html 
sidebar: sidebar 
keywords: qos,value,configure,configuring,default,set,setting,setdefaultqos 
summary: 'Vous pouvez utiliser la méthode SetDefaultQoS pour configurer les valeurs de qualité de service (QoS) par défaut (mesurées en entrées et sorties par seconde, ou IOPS) pour un volume.' 
---
= Définir la QoS par défaut
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `SetDefaultQoS` méthode permettant de configurer les valeurs de qualité de service (QoS) par défaut (mesurées en entrées et sorties par seconde, ou IOPS) pour un volume.



== Paramètres

Cette méthode possède les paramètres d'entrée suivants :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
minIOPS
 a| 
Le nombre minimal d'IOPS soutenues fournies par le cluster à un volume.
 a| 
entier
 a| 
Aucune
 a| 
Non



 a| 
maxIOPS
 a| 
Le nombre maximal d'IOPS soutenues fournies par le cluster à un volume.
 a| 
entier
 a| 
Aucune
 a| 
Non



 a| 
burstIOPS
 a| 
Le nombre maximal d'IOPS autorisé dans un scénario de rafale courte.
 a| 
entier
 a| 
Aucune
 a| 
Non

|===


== Valeurs de retour

Cette méthode renvoie les valeurs suivantes :

|===
| Nom | Description | Type 


 a| 
minIOPS
 a| 
Le nombre minimal d'IOPS soutenues fournies par le cluster à un volume.
 a| 
entier



 a| 
maxIOPS
 a| 
Le nombre maximal d'IOPS soutenues fournies par le cluster à un volume.
 a| 
entier



 a| 
burstIOPS
 a| 
Le nombre maximal d'IOPS autorisé dans un scénario de rafale courte.
 a| 
entier

|===


== Exemple de demande

Les requêtes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
   "method": "SetDefaultQoS",
    "params": {
        "burstIOPS":8000,
        "maxIOPS":1000,
        "minIOPS":200
    },
    "id": 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
    "id":1,
    "result": {
        "burstIOPS":8000,
        "maxIOPS":1000,
        "minIOPS":200
    ​}
}
----


== Nouveautés depuis la version

9,6
