---
permalink: api/reference_element_api_disableldapauthentication.html 
sidebar: sidebar 
keywords: LDAP,authentication,auth,disable,disabling,DisableLdapAuthentication 
summary: 'Vous pouvez utiliser la méthode DisableLdapAuthentication pour désactiver l"authentification LDAP et supprimer tous les paramètres de configuration LDAP.  Cette méthode ne supprime aucun compte d"administrateur de cluster configuré pour les utilisateurs ou les groupes.  Une fois l"authentification LDAP désactivée, les administrateurs de cluster configurés pour utiliser cette authentification ne pourront plus accéder au cluster.' 
---
= Désactiver l'authentification LDAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `DisableLdapAuthentication` Méthode permettant de désactiver l'authentification LDAP et de supprimer tous les paramètres de configuration LDAP.  Cette méthode ne supprime aucun compte d'administrateur de cluster configuré pour les utilisateurs ou les groupes.  Une fois l'authentification LDAP désactivée, les administrateurs de cluster configurés pour utiliser cette authentification ne pourront plus accéder au cluster.



== Paramètres

Cette méthode ne requiert aucun paramètre d'entrée.



== Valeurs de retour

Cette méthode ne renvoie aucune valeur.



== Exemple de demande

Les requêtes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
  "method": "DisableLdapAuthentication",
  "params": {},
"id": 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
"id": 1,
"result": {}
}
----


== Nouveautés depuis la version

9,6
