---
permalink: api/reference_element_api_getcurrentclusteradmin.html 
sidebar: sidebar 
keywords: cluster,admin,get,getting,current,getcurrentclusteradmin 
summary: 'Vous pouvez utiliser la méthode GetCurrentClusterAdmin pour obtenir des informations sur l"administrateur de cluster principal actuel.  L"administrateur principal du cluster a été créé lors de la création du cluster.' 
---
= GetClusterAdmin actuel
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `GetCurrentClusterAdmin` méthode permettant de renvoyer des informations pour l'administrateur principal du cluster actuel.  L'administrateur principal du cluster a été créé lors de la création du cluster.



== Paramètres

Cette méthode ne requiert aucun paramètre d'entrée.



== valeur de retour

Cette méthode a la valeur de retour suivante :

|===
| Nom | Description | Type 


 a| 
Administrateur de cluster
 a| 
Informations concernant l'administrateur du cluster.
 a| 
xref:reference_element_api_clusteradmin.adoc[Administrateur de cluster]

|===


== Exemple de demande

Les requêtes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
"method": "GetCurrentClusterAdmin",
"id" : 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
"id": 1,
"result": {
    "clusterAdmin":
        "access": [
           "administrator"
        ],
         "attributes": null,
         "authMethod": "Cluster"
         "clusterAdminID": 1,
         "username": "admin"
     }
   }
}
----


== Nouveautés depuis la version

10,0
