---
permalink: api/reference_element_api_removeaccount.html 
sidebar: sidebar 
keywords: account,accounts,remove,removing,deleting,delete,purge,volume,volumes,removeaccount 
summary: 'Vous pouvez utiliser la méthode RemoveAccount pour supprimer un compte existant.  Vous devez supprimer et purger tous les volumes associés au compte à l"aide de DeleteVolume avant de pouvoir supprimer le compte.  Si des volumes du compte sont toujours en attente de suppression, vous ne pouvez pas utiliser RemoveAccount pour supprimer le compte.' 
---
= Supprimer le compte
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `RemoveAccount` méthode pour supprimer un compte existant.  Vous devez supprimer et purger tous les volumes associés au compte en utilisant `DeleteVolume` avant de pouvoir supprimer le compte.  Si des volumes du compte sont toujours en attente de suppression, vous ne pouvez pas utiliser `RemoveAccount` supprimer le compte.



== Paramètre

Cette méthode possède le paramètre d'entrée suivant :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
identifiant de compte
 a| 
L'identifiant du compte à supprimer.
 a| 
entier
 a| 
Aucune
 a| 
Oui

|===


== valeur de retour

Cette méthode ne renvoie aucune valeur.



== Exemple de demande

Les requêtes pour cette méthode sont similaires à l'exemple suivant.

[listing]
----
{
   "method": "RemoveAccount",
   "params": {
     "accountID"  : 25
   },
   "id" : 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----

{
 "id" : 1,
 "result" : { }
}
----


== Nouveautés depuis la version

9,6



== Trouver plus d'informations

xref:reference_element_api_deletevolume.adoc[Supprimer le volume]
