---
permalink: api/reference_element_api_deletestoragecontainers.html 
sidebar: sidebar 
keywords: virtual,volume,storage,container,delete,deleting,vvol,DeleteStorageContainers 
summary: 'Vous pouvez utiliser la méthode DeleteStorageContainers pour supprimer jusqu"à 2000 conteneurs de stockage Virtual Volume (VVol) du système en une seule fois.  Les conteneurs de stockage que vous retirez ne doivent contenir aucun VVol.' 
---
= Supprimer les conteneurs de stockage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `DeleteStorageContainers` méthode permettant de supprimer jusqu'à 2000 conteneurs de stockage de volumes virtuels (VVol) du système en une seule fois.  Les conteneurs de stockage que vous retirez ne doivent contenir aucun VVol.



== Paramètres

Cette méthode possède le paramètre d'entrée suivant :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
ID des conteneurs de stockage
 a| 
Liste des identifiants des conteneurs de stockage à supprimer.  Vous pouvez spécifier jusqu'à 2000 identifiants dans la liste.
 a| 
tableau UUID
 a| 
Aucune
 a| 
Oui

|===


== Valeurs de retour

Cette méthode ne renvoie aucune valeur.



== Exemple de demande

Les requêtes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
  "method": "DeleteStorageContainers",
    "params": {
        "storageContainerIDs" : ["a9ec1138-e386-4a44-90d7-b9acbbc05176"]
    },
    "id": 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
  "id": 1,
  "result": {}
}
----


== Nouveautés depuis la version

9,6
