---
permalink: api/reference_element_api_listsnapmirrornetworkinterfaces.html 
sidebar: sidebar 
keywords: snapmirror,interface,interfaces,list,listing,listsnapmirrornetworkinterfaces,ontap 
summary: 'L"interface utilisateur Web du logiciel Element utilise la méthode ListSnapMirrorNetworkInterfaces pour lister toutes les interfaces SnapMirror disponibles sur un système ONTAP distant.' 
---
= ListSnapMirrorNetworkInterfaces
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'interface utilisateur Web du logiciel Element utilise `ListSnapMirrorNetworkInterfaces` Méthode permettant de lister toutes les interfaces SnapMirror disponibles sur un système ONTAP distant.



== Paramètre

Cette méthode possède les paramètres d'entrée suivants :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
snapMirrorEndpointID
 a| 
Ne renvoyez que les interfaces réseau associées à l'ID de point de terminaison spécifié.  Si aucun identifiant de point de terminaison n'est fourni, le système liste les interfaces de tous les points de terminaison SnapMirror connus.
 a| 
entier
 a| 
Aucune
 a| 
Non



 a| 
rôle d'interface
 a| 
N'afficher que l'interface réseau assurant le rôle spécifié.
 a| 
chaîne
 a| 
Aucune
 a| 
Non

|===


== valeur de retour

Cette méthode a la valeur de retour suivante :

|===
| Nom | Description | Type 


 a| 
snapMirrorNetworkInterfaces
 a| 
Liste des interfaces réseau SnapMirror disponibles sur le système de stockage ONTAP distant.
 a| 
xref:reference_element_api_snapmirrornetworkinterface.adoc[snapMirrornetworkInterface]tableau

|===


== Nouveautés depuis la version

10,1
