---
permalink: api/reference_element_api_listprotectiondomainlevels.html 
sidebar: sidebar 
keywords: list,listing,protection,domain,levels,level,listprotectiondomainlevels 
summary: Vous pouvez utiliser la méthode ListProtectionDomainLevels pour lister les niveaux de tolérance et de résilience du cluster de stockage.  Les niveaux de tolérance indiquent la capacité du cluster à continuer à lire et à écrire des données en cas de panne, et les niveaux de résilience indiquent la capacité du cluster de stockage à se réparer automatiquement après une ou plusieurs pannes. 
---
= Niveaux de protection de liste
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `ListProtectionDomainLevels` méthode pour lister les niveaux de tolérance et de résilience du cluster de stockage.  Les niveaux de tolérance indiquent la capacité du cluster à continuer à lire et à écrire des données en cas de panne, et les niveaux de résilience indiquent la capacité du cluster de stockage à se réparer automatiquement après une ou plusieurs pannes.



== Paramètre

Cette méthode ne comporte aucun paramètre d'entrée.



== Valeurs de retour

Cette méthode renvoie les valeurs suivantes :

|===
| Nom | Description | Type 


 a| 
niveaux de domaine de protection
 a| 
Liste des différents niveaux de domaine de protection, chacun fournissant des informations sur la tolérance et la résilience du cluster de stockage.
 a| 
xref:reference_element_api_protectiondomainlevel.adoc[niveau de domaine de protection]

|===


== Exemple de demande

Les requêtes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
  "method": "ListProtectionDomainLevels",
  "params": {},
  "id" : 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
	"id": 1,
	"result": {
		"protectionDomainLevels": [
			{
				"protectionDomainType": "node",
				"resiliency": {
					"protectionSchemeResiliencies": [
							{
								"protectionScheme": "doubleHelix",
								"sustainableFailuresForBlockData": 0,
								"sustainableFailuresForMetadata": 1
							}
					],
					"singleFailureThresholdBytesForBlockData": 0,
					"sustainableFailuresForEnsemble": 1
				},
				"tolerance": {
					"protectionSchemeTolerances": [
							{
								"protectionScheme": "doubleHelix",
								"sustainableFailuresForBlockData": 0,
								"sustainableFailuresForMetadata": 1
							}
					],
					"sustainableFailuresForEnsemble": 1
				}
			},
			{
				"protectionDomainType": "chassis",
				"resiliency": {
					"protectionSchemeResiliencies": [
							{
								"protectionScheme": "doubleHelix",
								"sustainableFailuresForBlockData": 0,
								"sustainableFailuresForMetadata": 1
							}
					],
					"singleFailureThresholdBytesForBlockData": 0,
					"sustainableFailuresForEnsemble": 1
				},
				"tolerance": {
					"protectionSchemeTolerances": [
							{
								"protectionScheme": "doubleHelix",
								"sustainableFailuresForBlockData": 0,
								"sustainableFailuresForMetadata": 1
							}
					],
					"sustainableFailuresForEnsemble": 1
				}
			}
		]
	}
}
----


== Nouveautés depuis la version

11,0
