---
permalink: api/reference_element_api_getconfig.html 
sidebar: sidebar 
keywords: node,get,getting,info,config,configuration,getconfig 
summary: 'Vous pouvez utiliser la méthode API GetConfig pour obtenir toutes les informations de configuration d"un nœud.  Cette méthode API inclut les mêmes informations que celles disponibles dans les méthodes API GetClusterConfig et GetNetworkConfig.' 
---
= GetConfig
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `GetConfig` Méthode API permettant d'obtenir toutes les informations de configuration d'un nœud.  Cette méthode API inclut les mêmes informations disponibles dans les deux `GetClusterConfig` et `GetNetworkConfig` Méthodes API.



== Paramètres

Cette méthode ne requiert aucun paramètre d'entrée.



== Valeurs de retour

Cette méthode a la valeur de retour suivante :

|===
| Nom | Description | Type 


 a| 
configuration
 a| 
Détails de configuration du cluster.  Cet objet contient :

* xref:reference_element_api_cluster.adoc[grappe]Informations de cluster indiquant comment le nœud de stockage communique avec le cluster de stockage auquel il est associé.
* xref:reference_element_api_network_all_interfaces.adoc[réseau (toutes les interfaces)]: Types de connexion réseau et paramètres actuels pour chaque interface réseau du nœud.

 a| 
objet JSON

|===


== Exemple de demande

Les requêtes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
   "method": "GetConfig",
   "params": {},
   "id" : 1
}
----


== Exemple de réponse

En raison de sa longueur, cet exemple de réponse est documenté dans un sujet supplémentaire.



== Nouveautés depuis la version

9,6



== Trouver plus d'informations

* xref:reference_element_api_getclusterconfig.adoc[Obtenir la configuration du cluster]
* xref:reference_element_api_getnetworkconfig.adoc[Obtenir la configuration réseau]
* xref:reference_element_api_response_example_getconfig.adoc[GetConfig]

