---
permalink: api/reference_element_api_getschedule.html 
sidebar: sidebar 
keywords: snapshot,schedule,get,getting,getschedule 
summary: Vous pouvez utiliser GetSchedule pour obtenir des informations sur un instantané planifié. 
---
= Obtenir le calendrier
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser `GetSchedule` pour obtenir des informations sur une capture d'écran programmée.

Vous pouvez consulter les informations relatives à un planning spécifique s'il existe de nombreux plannings instantanés dans le système.  Cette méthode vous permet également de récupérer des informations sur plusieurs plannings en spécifiant des identifiants supplémentaires dans le paramètre scheduleID.



== Paramètre

Cette méthode possède le paramètre d'entrée suivant :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
ID de planification
 a| 
Identifiant unique du ou des horaires à afficher.
 a| 
entier
 a| 
Aucune
 a| 
Oui

|===


== valeur de retour

Cette méthode a la valeur de retour suivante :

|===
| Nom | Description | Type 


 a| 
calendrier
 a| 
Un tableau d'attributs de planification.
 a| 
xref:reference_element_api_schedule.adoc[calendrier]tableau

|===


== Exemple de demande

Les requêtes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
"method": "GetSchedule",
  "params": {
              "scheduleID" : 2
      },
   "id" : 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
  "id": 1,
  "result": {
    "schedule": {
      "attributes": {
        "frequency": "Time Interval"
      },
       "hasError": false,
       "hours": 0,
       "lastRunStatus": "Success",
       "lastRunTimeStarted": "2015-03-23T21:25:00Z",
       "minutes": 2,
       "monthdays": [],
       "paused": false,
       "recurring": true,
       "runNextInterval": false,
       "scheduleID": 2,
       "scheduleInfo": {
          "name": "MCA2",
          "volumeID": "3"
       },
       "scheduleName": "MCAsnapshot2",
       "scheduleType": "Snapshot",
       "startingDate": "2015-03-23T19:28:57Z",
       "toBeDeleted": false,
       "weekdays": []
      }
   }
}
----


== Nouveautés depuis la version

9,6
