---
permalink: api/reference_element_api_createkeyserverkmip.html 
sidebar: sidebar 
keywords: KMIP,key server,creating,create 
summary: 'Vous pouvez utiliser la méthode CreateKeyServerKmip pour créer un serveur de clés KMIP (Key Management Interoperability Protocol) avec les attributs spécifiés.  Lors de la création, le serveur n"est pas contacté ; il n"est pas nécessaire qu"il existe avant d"utiliser cette méthode.  Pour les configurations de serveurs de clés en cluster, vous devez fournir les noms d"hôte ou les adresses IP de tous les nœuds du serveur dans le paramètre kmipKeyServerHostnames.  Vous pouvez utiliser la méthode TestKeyServerKmip pour tester un serveur de clés.' 
---
= CréerKeyServerKmip
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `CreateKeyServerKmip` méthode pour créer un serveur de clés KMIP (Key Management Interoperability Protocol) avec les attributs spécifiés.  Lors de la création, le serveur n'est pas contacté ; il n'est pas nécessaire qu'il existe avant d'utiliser cette méthode.  Pour les configurations de serveurs de clés en cluster, vous devez fournir les noms d'hôte ou les adresses IP de tous les nœuds du serveur dans le paramètre kmipKeyServerHostnames.  Vous pouvez utiliser le `TestKeyServerKmip` méthode pour tester un serveur de clés.



== Paramètres

Cette méthode possède les paramètres d'entrée suivants :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
kmipCaCertificate
 a| 
Le certificat de clé publique de l'autorité de certification racine du serveur de clés externe.  Cela servira à vérifier le certificat présenté par le serveur de clés externe dans la communication TLS.  Pour les clusters de serveurs critiques où chaque serveur utilise une autorité de certification différente, fournissez une chaîne concaténée contenant les certificats racine de toutes les autorités de certification.
 a| 
chaîne
 a| 
Aucune
 a| 
Oui



 a| 
Certificat client kmip
 a| 
Un certificat X.509 PKCS#10 au format PEM encodé en Base64 utilisé par le client Solidfire KMIP.
 a| 
chaîne
 a| 
Aucune
 a| 
Oui



 a| 
Noms d'hôte du serveur de clés kmip
 a| 
Tableau des noms d'hôtes ou des adresses IP associés à ce serveur de clés KMIP.  Plusieurs noms d'hôtes ou adresses IP ne doivent être fournis que si les serveurs clés sont configurés en cluster.
 a| 
tableau de chaînes
 a| 
Aucune
 a| 
Oui



 a| 
Nom du serveur de clés kmip
 a| 
Le nom du serveur de clés KMIP.  Ce nom est utilisé uniquement à des fins d'affichage et n'a pas besoin d'être unique.
 a| 
chaîne
 a| 
Aucune
 a| 
Oui



 a| 
kmipKeyServerPort
 a| 
Le numéro de port associé à ce serveur de clés KMIP (généralement 5696).
 a| 
entier
 a| 
Aucune
 a| 
Non

|===


== Valeurs de retour

Cette méthode renvoie les valeurs suivantes :

|===


| Nom | Description | Type 


 a| 
kmipKeyServer
 a| 
Un objet contenant des informations sur le serveur de clés nouvellement créé.
 a| 
link:reference_element_api_keyserverkmip.html["KeyServerKmip"]

|===


== Exemple de demande

Les requêtes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
  "method": "CreateKeyServerKmip",
  "params": {
    "kmipCaCertificate": "MIICPDCCAaUCEDyRMcsf9tAbDpq40ES/E...",
    "kmipClientCertificate": "dKkkirWmnWXbj9T/UWZYB2oK0z5...",
    "kmipKeyServerHostnames" : ["server1.hostname.com", "server2.hostname.com"],
    "kmipKeyServerName" : "keyserverName",
    "kmipKeyServerPort" : 5696
  },
"id": 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
   "id": 1,
   "result":
      {
        "kmipKeyServer": {
            "kmipCaCertificate":"MIICPDCCAaUCEDyRMcsf9tAbDpq40ES/E...",
            "kmipKeyServerHostnames":[
                "server1.hostname.com", "server2.hostname.com"
            ],
            "keyProviderID":1,
            "kmipKeyServerName":"keyserverName",
            "keyServerID":1
            "kmipKeyServerPort":1,
            "kmipClientCertificate":"dKkkirWmnWXbj9T/UWZYB2oK0z5...",
            "kmipAssignedProviderIsActive":true
        }
    }
}
----


== Nouveautés depuis la version

11,7
