---
permalink: api/reference_element_api_listnetworkinterfacestats.html 
sidebar: sidebar 
keywords: network,interface,stats,statistics,interfaces,list,listing,listnetworkinterfacestats 
summary: 'Vous pouvez utiliser la méthode ListNetworkInterfaceStats pour afficher les statistiques relatives à chaque interface réseau d"un nœud.  Cette méthode API est destinée à être utilisée sur des nœuds individuels ; l’authentification par identifiant et mot de passe est requise pour accéder à chaque nœud.  Toutefois, vous pouvez utiliser cette méthode sur le cluster si le paramètre force reçoit la valeur true lors de l"appel de la méthode.  Lorsque ce paramètre est utilisé sur le cluster, toutes les interfaces sont listées.' 
---
= Lister les statistiques de l'interface réseau
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `ListNetworkInterfaceStats` méthode permettant de lister des statistiques telles que le nombre de paquets perdus et divers types d'erreurs pour chaque interface réseau d'un nœud.  Cette méthode API est destinée à être utilisée sur des nœuds individuels ; l’authentification par identifiant et mot de passe est requise pour accéder à chaque nœud.  Toutefois, vous pouvez utiliser cette méthode sur le cluster si le paramètre force reçoit la valeur true lors de l'appel de la méthode.  Lorsque ce paramètre est utilisé sur le cluster, les statistiques réseau de toutes les interfaces sont affichées.



== Paramètre

Cette méthode ne requiert aucun paramètre d'entrée.



== valeur de retour

Cette méthode a la valeur de retour suivante :

|===
| Nom | Description | Type 


| statistiques d'interface réseau | Une liste d'informations statistiques sur le réseau, telles que le nombre de paquets perdus et divers types d'erreurs réseau, pour chaque interface réseau d'un nœud de stockage. | xref:reference_element_api_networkinterfacestats.adoc[statistiques d'interface réseau]tableau 
|===


== Exemple de demande

Les requêtes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
"method": "ListNetworkInterfaceStats",
"params": {},
"id" : 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
    "networkInterfaceStats": [
        {
            "rxErrors": 1,
            "rxPackets": 1,
            "txErrors": 1,
            "rxDropped": 1,
            "txCarrierErrors": 1,
            "rxOverErrors": 1,
            "rxMissedErrors": 1,
            "txPackets": 1,
            "name": "if_name",
            "rxLengthErrors": 1,
            "collisions": 1,
            "rxFifoErrors": 1,
            "txBytes": 1,
            "rxBytes": 1,
            "rxFrameErrors": 1,
            "rxCrcErrors": 1,
            "txFifoErrors": 1
        }
    ]
}
----


== Nouveautés depuis la version

12,3
