---
permalink: api/reference_element_api_modifystoragecontainer.html 
sidebar: sidebar 
keywords: virtual,volume,storage,container,vvol,modify,modifying,change,changing,edit,editing 
summary: Vous pouvez utiliser la méthode ModifyStorageContainer pour apporter des modifications à un conteneur de stockage de volume virtuel existant. 
---
= Modifier le conteneur de stockage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `ModifyStorageContainer` méthode permettant de modifier un conteneur de stockage de volume virtuel existant.



== Paramètres

Cette méthode possède les paramètres d'entrée suivants :

|===


| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
ID du conteneur de stockage
 a| 
L'identifiant unique du conteneur de stockage de volume virtuel à modifier.
 a| 
UUID
 a| 
Aucune
 a| 
Oui



 a| 
initiateurSecret
 a| 
Le nouveau secret de l'authentification CHAP pour l'initiateur.
 a| 
chaîne
 a| 
Aucune
 a| 
Non



 a| 
cible secrète
 a| 
Le nouveau secret de l'authentification CHAP pour la cible.
 a| 
chaîne
 a| 
Aucune
 a| 
Non

|===


== Valeurs de retour

Cette méthode a la valeur de retour suivante :

|===


| Nom | Description | Type 


 a| 
conteneur de stockage
 a| 
Informations concernant le conteneur de stockage nouvellement créé.
 a| 
xref:reference_element_api_storagecontainer.adoc[conteneur de stockage]

|===


== Exemple de demande

Les requêtes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
  "method": "ModifyStorageContainer",
    "params": {
      "storageContainerID": "6c95e24f-9f0b-4793-affb-5a4bc6c3d7e1",
      "targetSecret": "O,IM;tOQdn9$JJ*8"
    },
    "id": 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
  "id": 1,
  "result": {
    "storageContainer": {
      "accountID": 8,
      "initiatorSecret": "T$|5TO>2IY5sk4@k",
      "name": "doctest1",
      "protocolEndpointType": "SCSI",
      "status": "active",
      "storageContainerID": "6c95e24f-9f0b-4793-affb-5a4bc6c3d7e1",
      "targetSecret": "O,IM;tOQdn9$JJ*8"
    }
  }
}
----


== Nouveautés depuis la version

9,6
