---
permalink: api/reference_element_api_enableidpauthentication.html 
sidebar: sidebar 
keywords: IdP,idp,authentication,enable 
summary: 'Vous pouvez utiliser la méthode EnableIdpAuthentication pour activer la prise en charge de l"authentification à l"aide de fournisseurs d"identité tiers pour le cluster.  Une fois l"authentification IdP activée, les administrateurs LDAP et de cluster ne peuvent plus accéder au cluster via les interfaces utilisateur prises en charge et toutes les sessions authentifiées actives sont invalidées/déconnectées.  Seuls les utilisateurs authentifiés par des fournisseurs d"identité tiers peuvent accéder au cluster via les interfaces utilisateur prises en charge.' 
---
= Activer l'authentification Idp
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `EnableIdpAuthentication` méthode permettant de prendre en charge l'authentification à l'aide de fournisseurs d'identité tiers pour le cluster.  Une fois l'authentification IdP activée, les administrateurs LDAP et de cluster ne peuvent plus accéder au cluster via les interfaces utilisateur prises en charge et toutes les sessions authentifiées actives sont invalidées/déconnectées.  Seuls les utilisateurs authentifiés par des fournisseurs d'identité tiers peuvent accéder au cluster via les interfaces utilisateur prises en charge.



== Paramètres

Cette méthode possède le paramètre d'entrée suivant :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
ID de configuration idp
 a| 
UUID pour la configuration du fournisseur d'identité tiers.  S'il n'existe qu'une seule configuration IdP, c'est cette configuration qui sera activée par défaut.  Si vous n'avez qu'une seule configuration IdpConfiguration, vous n'avez pas besoin de fournir le paramètre idpConfigurationID.
 a| 
UUID
 a| 
Aucune
 a| 
Non

|===


== Valeurs de retour

Cette méthode ne renvoie aucune valeur.



== Exemple de demande

Les requêtes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
  "method": "EnableIdpAuthentication",
  "params": {
    "idpConfigurationID": "f983c602-12f9-4c67-b214-bf505185cfed",
  }
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
"result": {}
}
----


== Nouveautés depuis la version

12,0
