---
permalink: api/reference_element_api_disableidpauthentication.html 
sidebar: sidebar 
keywords: IdP,idp,authentication,disable 
summary: 'Vous pouvez utiliser la méthode DisableIdpAuthentication pour désactiver la prise en charge de l"authentification à l"aide de fournisseurs d"identité tiers pour le cluster.  Une fois désactivée, l"authentification des utilisateurs par des fournisseurs d"identité tiers les empêche d"accéder au cluster et toutes les sessions authentifiées actives sont invalidées/déconnectées.  Les administrateurs LDAP et de cluster peuvent accéder au cluster via les interfaces utilisateur prises en charge.' 
---
= Désactiver l'authentification Idp
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `DisableIdpAuthentication` Méthode permettant de désactiver la prise en charge de l'authentification via des fournisseurs d'identité tiers pour le cluster.  Une fois désactivée, l'authentification des utilisateurs par des fournisseurs d'identité tiers les empêche d'accéder au cluster et toutes les sessions authentifiées actives sont invalidées/déconnectées.  Les administrateurs LDAP et de cluster peuvent accéder au cluster via les interfaces utilisateur prises en charge.



== Paramètres

Cette méthode ne requiert aucun paramètre d'entrée.



== Valeurs de retour

Cette méthode ne renvoie aucune valeur.



== Exemple de demande

Les requêtes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
  "method": "DisableIdpAuthentication",
  "params": {}
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
"result": {}
}
----


== Nouveautés depuis la version

12,0
