---
permalink: api/reference_element_api_createbackuptarget.html 
sidebar: sidebar 
keywords: create,creating,backup,target,CreateBackupTarget 
summary: 'Vous pouvez utiliser CreateBackupTarget pour créer et stocker les informations de la cible de sauvegarde afin de ne pas avoir à les saisir à nouveau à chaque création d"une sauvegarde.' 
---
= Créer une cible de sauvegarde
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser `CreateBackupTarget` pour créer et stocker les informations de la cible de sauvegarde afin de ne pas avoir à les saisir à nouveau à chaque création d'une sauvegarde.



== Paramètres

Cette méthode possède les paramètres d'entrée suivants :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
nom
 a| 
Nom de la cible de sauvegarde.
 a| 
chaîne
 a| 
Aucune
 a| 
Oui



 a| 
attributs
 a| 
Liste de paires nom-valeur au format objet JSON.
 a| 
objet JSON
 a| 
Aucune
 a| 
Oui (mais peut être vide)

|===


== valeur de retour

Cette méthode a la valeur de retour suivante :

|===


| Nom | Description | Type 


 a| 
ID cible de sauvegarde
 a| 
Identifiant unique attribué à la nouvelle cible de sauvegarde.
 a| 
entier

|===


== Exemple de demande

Les requêtes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
   "method": "CreateBackupTarget",
   "params": {
      "name": "mytargetbackup"
   },
"id": 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
   "id": 1,
   "result": {
      "backupTargetID": 1
   }
}
----


== Nouveautés depuis la version

9,6
