---
permalink: api/reference_element_api_listsnapmirrorluns.html 
sidebar: sidebar 
keywords: snapmirror,lun,luns,list,listing,listsnapmirrorluns 
summary: 'L"interface utilisateur Web du logiciel Element utilise la méthode ListSnapMirrorLuns pour lister les informations LUN de la relation SnapMirror du cluster ONTAP distant.' 
---
= ListSnapMirrorLuns
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'interface utilisateur Web du logiciel Element utilise `ListSnapMirrorLuns` méthode permettant de lister les informations LUN pour la relation SnapMirror à partir du cluster ONTAP distant.



== Paramètres

Cette méthode possède les paramètres d'entrée suivants :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
snapMirrorEndpointID
 a| 
N'afficher que les informations LUN associées à l'ID de point de terminaison spécifié.
 a| 
entier
 a| 
Aucune
 a| 
Oui



 a| 
destinationVolume
 a| 
Le volume de destination dans la relation SnapMirror .
 a| 
xref:reference_element_api_snapmirrorvolumeinfo.adoc[snapMirrorVolumeInfo]
 a| 
Aucune
 a| 
Oui

|===


== Valeurs de retour

Cette méthode renvoie les valeurs suivantes :

|===
| Nom | Description | Type 


 a| 
snapMirrorLunInfos
 a| 
Liste d'objets contenant des informations sur les LUN SnapMirror .
 a| 
xref:reference_element_api_snapmirrorluninfo.adoc[snapMirrorLunInfo]tableau

|===


== Nouveautés depuis la version

10,1
