---
permalink: api/reference_element_api_testping.html 
sidebar: sidebar 
keywords: ping,test,TestPing 
summary: 'Vous pouvez utiliser la méthode TestPing pour tester la connectivité réseau de tous les nœuds du cluster sur les interfaces 1G et 10G à l"aide de paquets ICMP.  Le test utilise les tailles MTU appropriées pour chaque paquet en fonction des paramètres MTU définis dans la configuration réseau.  TestPing ne crée pas d"interface VLAN temporaire.' 
---
= TestPing
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `TestPing` méthode pour tester la connectivité réseau à tous les nœuds du cluster sur les interfaces 1G et 10G à l'aide de paquets ICMP.  Le test utilise les tailles MTU appropriées pour chaque paquet en fonction des paramètres MTU définis dans la configuration réseau. `TestPing` ne crée pas d'interface VLAN temporaire.



== Paramètres

Cette méthode possède le paramètre d'entrée suivant :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
tentatives
 a| 
Spécifie le nombre de fois où le système doit répéter le test ping.
 a| 
entier
 a| 
5
 a| 
Non



 a| 
hôtes
 a| 
Spécifie une liste d'adresses ou de noms d'hôtes de périphériques à interroger, séparés par des virgules.  Si aucun hôte n'est spécifié, la méthode effectue un ping sur les hôtes du cluster de stockage.
 a| 
chaîne
 a| 
Aucune
 a| 
Non



 a| 
interface
 a| 
L'interface (de base) existante à partir de laquelle les pings doivent être envoyés. Valeurs possibles :

* `Bond10G`: Envoyer des pings depuis l'interface Bond10G.
* `Bond1G`: Envoyer des pings depuis l'interface Bond1G.

 a| 
chaîne
 a| 
Aucune
 a| 
Non



 a| 
taille du paquet
 a| 
Spécifie le nombre d'octets à envoyer dans le paquet ICMP adressé à chaque adresse IP.  Le nombre d'octets doit être inférieur à la MTU maximale spécifiée dans la configuration réseau.
 a| 
entier
 a| 
Aucune
 a| 
Non



 a| 
Délai d'attente (en ms)
 a| 
Spécifie le nombre de millisecondes à attendre pour chaque réponse ping individuelle.
 a| 
entier
 a| 
500 millisecondes
 a| 
Non



 a| 
interdire la fragmentation
 a| 
Active l'indicateur DF (Ne pas fragmenter) pour les paquets ICMP.
 a| 
booléen
 a| 
FAUX
 a| 
Non



 a| 
sourceAddressV4
 a| 
L'adresse IPv4 source à utiliser dans les paquets ping ICMP.
 a| 
chaîne
 a| 
Aucune
 a| 
Non



 a| 
sourceAddressV6
 a| 
L'adresse IPv6 source à utiliser dans les paquets ping ICMP.
 a| 
chaîne
 a| 
Aucune
 a| 
Non



 a| 
totalTimeoutSec
 a| 
Spécifie le délai en secondes pendant lequel le ping doit attendre une réponse du système avant d'effectuer la prochaine tentative de ping ou de mettre fin au processus.
 a| 
entier
 a| 
5
 a| 
Non



 a| 
VirtualNetworkTag
 a| 
L'identifiant VLAN à utiliser lors de l'envoi des paquets ping.
 a| 
entier
 a| 
Aucune
 a| 
Non

|===


== valeur de retour

Cette méthode a la valeur de retour suivante :

|===


| Nom | Description | Type 


 a| 
détails
 a| 
Liste de chaque adresse IP avec laquelle le nœud a pu communiquer et statistiques de réponse au ping.
 a| 
objet JSON

|===


== Exemple de demande

Les requêtes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
    "method": "TestPing",
    "params": {
        "interface": "Bond1G",
        "hosts": "192.168.0.1"
    },
    "id" : 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
  "id": 1,
  "result": {
    "details": {
      "192.168.0.1": {
        "individualResponseCodes": [
          "Success",
          "Success",
          "Success",
          "Success",
          "Success"
        ],
        "individualResponseTimes": [
          "00:00:00.000304",
          "00:00:00.000123",
          "00:00:00.000116",
          "00:00:00.000113",
          "00:00:00.000111"
        ],
        "individualStatus": [
          true,
          true,
          true,
          true,
          true
        ],
        "interface": "Bond1G",
        "responseTime": "00:00:00.000154",
        "sourceAddressV4": "192.168.0.5",
        "successful": true
      }
    },
    "duration": "00:00:00.001747",
    "result": "Passed"
  }
}
----


== Nouveautés depuis la version

5,0
