---
permalink: api/reference_element_api_resetnode.html 
sidebar: sidebar 
keywords:  
summary: 'Vous pouvez utiliser la méthode ResetNode pour réinitialiser un nœud à ses paramètres d"usine.  Toutes les données, les packages (mises à jour logicielles, etc.), les configurations et les fichiers journaux sont supprimés du nœud lorsque vous appelez cette méthode.  Toutefois, les paramètres réseau du nœud sont préservés pendant cette opération.  Les nœuds participant à un cluster ne peuvent pas être réinitialisés aux paramètres d"usine.' 
---
= Réinitialiser le nœud
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `ResetNode` Méthode pour réinitialiser un nœud aux paramètres d'usine.  Lorsque vous appelez cette méthode, toutes les données, les paquets (mises à jour logicielles, etc.), les configurations et les fichiers journaux sont supprimés du nœud.  Toutefois, les paramètres réseau du nœud sont préservés pendant cette opération.  Les nœuds participant à un cluster ne peuvent pas être réinitialisés aux paramètres d'usine.



== Paramètres

L'API ResetNode ne peut être utilisée que sur les nœuds qui sont à l'état « Disponible ».  Il ne peut pas être utilisé sur les nœuds qui sont « actifs » dans un cluster, ni sur ceux qui sont à l’état « en attente ».

PRUDENCE:

Cette méthode efface toutes les données client présentes sur le nœud.

Cette méthode possède les paramètres d'entrée suivants :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
construire
 a| 
Utilisé pour spécifier l'URL d'une image logicielle Element distante vers laquelle le nœud sera réinitialisé.
 a| 
URL
 a| 
Aucune
 a| 
Non



 a| 
forcer
 a| 
Définir sur vrai pour réinitialiser le nœud.
 a| 
booléen
 a| 
Aucune
 a| 
Oui



 a| 
options
 a| 
Utilisé pour saisir les spécifications d'exécution des opérations de réinitialisation.  Des détails supplémentaires seront fournis par le support NetApp , si nécessaire.
 a| 
objet JSON
 a| 
Aucune
 a| 
Non

|===


== Valeurs de retour

Cette méthode ne renvoie aucune valeur.



== Exemple de demande

Les requêtes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
   "method": "ResetNode",
   "params": {
      "build" : "file:///sf/rtfi/image/filesystem.squashfs",
      "force" : true
              },
   "id" : 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
  "id": null,
  "result": {
    "rtfiInfo": {
      "build": "file:///sf/rtfi/image/filesystem.squashfs",
      "generation": "9",
      "options": {
        "edebug": "",
        "sf_auto": "0",
        "sf_bond_mode": "ActivePassive",
        "sf_check_hardware": "0",
        "sf_disable_otpw": "0",
        "sf_fa_host": "",
        "sf_hostname": "SF-FA18",
        "sf_inplace": "1",
        "sf_inplace_die_action": "kexec",
        "sf_inplace_safe": "0",
        "sf_keep_cluster_config": "0",
        "sf_keep_data": "0",
        "sf_keep_hostname": "0",
        "sf_keep_network_config": "0",
        "sf_keep_paths": "\"/var/log/hardware.xml\"",
        "sf_max_archives": "5",
        "sf_nvram_size": "",
        "sf_oldroot": "",
        "sf_postinst_erase_root_drive": "0",
        "sf_root_drive": "",
        "sf_rtfi_cleanup_state": "",
        "sf_secure_erase": "1",
        "sf_secure_erase_retries": "5",
        "sf_slice_size": "",
        "sf_ssh_key": "1",
        "sf_ssh_root": "1",
        "sf_start_rtfi": "1",
        "sf_status_httpserver": "1",
        "sf_status_httpserver_stop_delay": "5m",
        "sf_status_inject_failure": "",
        "sf_status_json": "0",
        "sf_support_host": "sfsupport.solidfire.com",
        "sf_test_hardware": "0",
        "sf_upgrade": "0",
        "sf_upgrade_firmware": "0",
        "sf_upload_logs_url": ""
     },
      "statusUrlAll": "http://192.168.130.20/status/all.json",
      "statusUrlCurrent": "http://192.168.130.20/status/current.json"
    }
  }
}
----


== Nouveautés depuis la version

9,6
