---
permalink: api/reference_element_api_purgedeletedvolume.html 
sidebar: sidebar 
keywords: volume,volumes,purging,purge,deleted,purgedeletedvolume 
summary: 'Vous pouvez utiliser la méthode PurgeDeletedVolume pour purger immédiatement et définitivement un volume qui a été supprimé.  Vous devez supprimer un volume à l"aide de DeleteVolume avant de pouvoir le purger.' 
---
= PurgeDeletedVolume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `PurgeDeletedVolume` méthode permettant de purger immédiatement et définitivement un volume supprimé.  Vous devez supprimer un volume en utilisant `DeleteVolume` avant qu'elle puisse être purgée.

Les volumes sont purgés automatiquement après un certain temps, l'utilisation de cette méthode n'est donc généralement pas nécessaire.



== Paramètre

Cette méthode possède le paramètre d'entrée suivant :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


| volumeID | L'identifiant du volume à purger. | entier | Non | Oui 
|===


== Valeurs de retour

Cette méthode ne renvoie aucune valeur.



== Exemple de demande

Les requêtes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
   "method": "PurgeDeletedVolume",
   "params": {
      "volumeID"  : 5
   },
   "id" : 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
  "id" : 1,
  "result": {}
}
----


== Nouveautés depuis la version

9,6



== Trouver plus d'informations

xref:reference_element_api_deletevolume.adoc[Supprimer le volume]
