---
permalink: api/reference_element_api_updatebulkvolumestatus.html 
sidebar: sidebar 
keywords: updatebulkvolumestatus,update,updating,bulk,volume,status,job 
summary: 'Vous pouvez utiliser la méthode UpdateBulkVolumeStatus pour mettre à jour l"état d"une tâche de traitement de volume en masse que vous avez démarrée avec les méthodes StartBulkVolumeRead ou StartBulkVolumeWrite.' 
---
= Mise à jour de l'état du volume en masse
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `UpdateBulkVolumeStatus` méthode pour mettre à jour l'état d'un travail de traitement par lots que vous avez démarré avec le `StartBulkVolumeRead` ou `StartBulkVolumeWrite` méthodes.



== Paramètres

Cette méthode possède les paramètres d'entrée suivants :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
clé
 a| 
La clé attribuée lors de l'initialisation d'unxref:reference_element_api_startbulkvolumeread.adoc[Démarrer la lecture en masse] ouxref:reference_element_api_startbulkvolumewrite.adoc[Démarrer l'écriture en masse] session.
 a| 
chaîne
 a| 
Aucune
 a| 
Oui



 a| 
statut
 a| 
Le système définit le statut de la tâche de traitement en masse spécifiée. Valeurs possibles :

* En cours d'exécution : Tâches toujours actives.
* Terminé : Tâches accomplies.
* Échecs : Emplois qui ont échoué.

 a| 
chaîne
 a| 
Aucune
 a| 
Oui



 a| 
pour cent terminé
 a| 
Avancement du travail en vrac en pourcentage.
 a| 
chaîne
 a| 
Aucune
 a| 
Non



 a| 
message
 a| 
Renvoie l'état du traitement en masse une fois celui-ci terminé.
 a| 
chaîne
 a| 
Aucune
 a| 
Non



 a| 
attributs
 a| 
Attributs JSON ; met à jour les informations relatives à la tâche de traitement en masse.
 a| 
objet JSON
 a| 
Aucune
 a| 
Non

|===


== Valeurs de retour

Cette méthode renvoie les valeurs suivantes :

|===


| Nom | Description | Type 


 a| 
statut
 a| 
Statut de la session demandée.  Statut retourné :

* se préparer
* actif
* fait
* échoué

 a| 
chaîne



 a| 
attributs
 a| 
Renvoie les attributs spécifiés dans l'appel de méthode.  Les valeurs sont renvoyées, qu'elles aient changé ou non.
 a| 
chaîne



 a| 
URL
 a| 
L'URL permettant d'accéder au serveur web du nœud ; fournie uniquement si la session est toujours active.
 a| 
chaîne

|===


== Exemple de demande

Les requêtes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
   "method": "UpdateBulkVolumeStatus",
   "params": {
          "key": "0b2f532123225febda2625f55dcb0448",
	      "status": "running"
      },
   "id": 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
   "id" : 1,
   "result": {
	  "status" : "running",
	  "url" : "https://10.10.23.47:8443/"
    }
}
----


== Nouveautés depuis la version

9,6



== Trouver plus d'informations

* xref:reference_element_api_startbulkvolumeread.adoc[Démarrer la lecture en masse]
* xref:reference_element_api_startbulkvolumewrite.adoc[Démarrer l'écriture en masse]

