---
permalink: api/reference_element_api_listidpconfigurations.html 
sidebar: sidebar 
keywords: configs configurations,idp configs,list 
summary: 'Vous pouvez utiliser la méthode ListIdpConfigurations pour lister les configurations des fournisseurs d"identité tiers.  Vous pouvez également fournir, si vous le souhaitez, l"indicateur enabledOnly pour récupérer la configuration IdP actuellement activée, ou un UUID de métadonnées IdP ou un nom IdP pour interroger les informations d"une configuration IdP spécifique.' 
---
= ListIdpConfigurations
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `ListIdpConfigurations` Méthode permettant de lister les configurations des fournisseurs d'identité tiers.  Vous pouvez également fournir, si vous le souhaitez : `enabledOnly` Utilisez un indicateur pour récupérer la configuration IdP actuellement activée ou un UUID de métadonnées IdP ou un nom IdP pour interroger des informations sur une configuration IdP spécifique.



== Paramètres

Cette méthode possède les paramètres d'entrée suivants :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
activé uniquement
 a| 
Filtre le résultat pour renvoyer la configuration IdP actuellement activée.
 a| 
booléen
 a| 
Aucune
 a| 
Non



 a| 
ID de configuration idp
 a| 
UUID pour la configuration du fournisseur d'identité tiers.
 a| 
UUID
 a| 
Aucune
 a| 
Non



 a| 
Nom idp
 a| 
Récupère les informations de configuration IdP pour un nom IdP spécifique.
 a| 
chaîne
 a| 
Aucune
 a| 
Non

|===


== Valeurs de retour

Cette méthode a la valeur de retour suivante :

|===


| Nom | Description | Type 


 a| 
idpConfigInfos
 a| 
Informations sur la ou les configurations du fournisseur d'identité tiers.
 a| 
link:reference_element_api_idpconfiginfo.html["idpConfigInfo"]tableau

|===


== Exemple de demande

Les requêtes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
  "method": "ListIdpConfigurations",
  "params": {}
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
    "result": {
        "idpConfigInfo": {
        "enabled": true,
        "idpConfigurationID": "f983c602-12f9-4c67-b214-bf505185cfed",
        "idpMetadata": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\r\n
        <EntityDescriptor xmlns=\"urn:oasis:names:tc:SAML:2.0:metadata\"\r\n
        xmlns:ds=\"http://www.w3.org/2000/09/xmldsig#\"\r\n
        xmlns:shibmd=\"urn:mace:shibboleth:metadata:1.0\"\r\n
        xmlns:xml=\"http://www.w3.org/XML/1998/namespace\"\r\n
        ...</Organization>\r\n
        </EntityDescriptor>",
        "idpName": "https://privider.name.url.com",
        "serviceProviderCertificate": "-----BEGIN CERTIFICATE-----\n
        MI...BHi\n
        -----END CERTIFICATE-----\n",
        "spMetadataUrl": "https://10.193.100.100/auth/ui/saml2"
        }
    }
}
----


== Nouveautés depuis la version

12,0
