---
permalink: api/reference_element_api_removekeyserverfromproviderkmip.html 
sidebar: sidebar 
keywords: KMIP,key server,unassigning,removing,remove,unassign,removekeyserverfromproviderkmip 
summary: 'Vous pouvez utiliser la méthode RemoveKeyServerFromProviderKmip pour désaffecter le serveur de clés KMIP (Key Management Interoperability Protocol) spécifié du fournisseur auquel il était affecté.  Vous pouvez désassigner un serveur de clés de son fournisseur, sauf s"il s"agit du dernier et que son fournisseur est actif (fournissant des clés actuellement utilisées).  Si le serveur de clés spécifié n"est pas attribué à un fournisseur, aucune action n"est entreprise et aucune erreur n"est renvoyée.' 
---
= SupprimerKeyServerFromProviderKmip
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `RemoveKeyServerFromProviderKmip` méthode permettant de désaffecter le serveur de clés KMIP (Key Management Interoperability Protocol) spécifié du fournisseur auquel il a été affecté.  Vous pouvez désassocier un serveur de clés de son fournisseur, sauf s'il s'agit du dernier et que son fournisseur est actif (fournissant des clés actuellement utilisées).  Si le serveur de clés spécifié n'est pas attribué à un fournisseur, aucune action n'est entreprise et aucune erreur n'est renvoyée.



== Paramètres

Cette méthode possède les paramètres d'entrée suivants :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
ID du serveur de clés
 a| 
L'identifiant du serveur de clés KMIP à désattribuer.
 a| 
entier
 a| 
Aucune
 a| 
Oui

|===


== Valeurs de retour

Cette méthode ne renvoie aucune valeur.  La suppression est considérée comme réussie tant qu'aucune erreur n'est renvoyée.



== Exemple de demande

Les requêtes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
  "method": "RemoveKeyServerFromProviderKmip",
  "params": {
    "keyServerID": 1
   },
"id": 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
   "id": 1,
   "result":
      {}
    }
}
----


== Nouveautés depuis la version

11,7
