---
permalink: api/reference_element_api_getclusterstate.html 
sidebar: sidebar 
keywords: cluster,state,getting,get,getclusterstate 
summary: 'Vous pouvez utiliser la méthode d"API GetClusterState pour indiquer si un nœud fait partie d"un cluster ou non.' 
---
= Obtenir l'état du cluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `GetClusterState` Méthode API permettant d'indiquer si un nœud fait partie d'un cluster ou non.



== Paramètres

Cette méthode ne requiert aucun paramètre d'entrée.



== Valeurs de retour

Cette méthode renvoie les valeurs suivantes :

|===
| Nom | Description | Type 


 a| 
grappe
 a| 
Nom du cluster.
 a| 
chaîne



 a| 
État
 a| 
* Disponible : Le nœud n'a pas été configuré avec un nom de cluster.
* En attente : ce nœud est en attente pour un cluster nommé spécifique et peut être ajouté.
* Actif : Ce nœud est un membre actif d’un cluster et ne peut pas être ajouté à un autre cluster.

 a| 
chaîne

|===


== Exemple de demande

Les requêtes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
   "method": "GetClusterState",
   "params": {},
   "id" : 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
   "id" : 1,
   "result" :
      "cluster" :  "Cluster101"
      "state" : "Active"
}
----


== Nouveautés depuis la version

9,6
