---
permalink: api/reference_element_api_groupsnapshot.html 
sidebar: sidebar 
keywords: object,objects,groupSnapshot 
summary: 'L"objet groupSnapshot contient des informations sur un instantané pour un groupe de volumes.  Vous pouvez utiliser la méthode API ListGroupSnapshots pour récupérer les informations d"instantané de groupe.' 
---
= groupSnapshot
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'objet groupSnapshot contient des informations sur un instantané pour un groupe de volumes.  Vous pouvez utiliser le `ListGroupSnapshots` Méthode API permettant de récupérer les informations d'instantané de groupe.



== membres de l'objet

Cet objet contient les membres suivants :

|===
| Nom | Description | Type 


 a| 
attributs
 a| 
Liste de paires nom-valeur au format objet JSON.
 a| 
objet JSON



 a| 
créerTime
 a| 
Le jour et l'heure au format UTC+0 auxquels l'instantané du groupe a été créé.
 a| 
Chaîne de date ISO 8601



 a| 
activer la réplication à distance
 a| 
Indique si la réplication à distance de l'instantané est activée.
 a| 
booléen



 a| 
groupSnapshotID
 a| 
L'identifiant unique de l'instantané du groupe.
 a| 
entier



 a| 
groupSnapshotUUID
 a| 
L'UUID de l'instantané du groupe.
 a| 
chaîne



 a| 
membres
 a| 
Un tableau d'objets contenant des informations sur chaque membre de l'instantané du groupe.
 a| 
xref:reference_element_api_snapshot.adoc[instantané]tableau



 a| 
nom
 a| 
Le nom de l'instantané de groupe ou, si aucun n'a été indiqué, la date et l'heure au format UTC auxquelles l'instantané a été créé.
 a| 
chaîne de caractères ou chaîne de date ISO 8601



 a| 
statuts distants
 a| 
Un tableau contenant l'identifiant universel et l'état de réplication de chaque instantané distant sur le cluster cible, tels qu'ils sont vus depuis le cluster source.
 a| 
xref:reference_element_api_remoteclustersnapshotstatus.adoc[État de l'instantané du cluster distant]tableau



 a| 
statut
 a| 
État actuel de l'instantané. Valeurs possibles :

* Inconnu : Une erreur s’est produite lors de la récupération de l’état de l’instantané.
* Préparation : Cette capture d’écran est en cours de préparation et n’est pas encore modifiable.
* RemoteSynchronisation : cet instantané est répliqué à partir d’un cluster distant.
* Terminé : Cette capture d’écran a terminé sa préparation ou sa réplication et est maintenant utilisable.
* Actif : Cet instantané correspond à la branche active.
* Clonage : cet instantané est impliqué dans une opération CopyVolume.

 a| 
chaîne

|===


== Trouver plus d'informations

xref:reference_element_api_listgroupsnapshots.adoc[Instantanés de groupe de liste]
