---
permalink: api/reference_element_api_protectiondomainresiliency.html 
sidebar: sidebar 
keywords: object,objects,protectionDomainResiliency 
summary: 'L"objet protectionDomainResiliency contient l"état de résilience de ce cluster de stockage.  La résilience indique la capacité du cluster de stockage à se réparer automatiquement après une ou plusieurs pannes, le tout au sein d"un seul domaine de protection de son type de domaine de protection associé.  Un cluster de stockage est considéré comme réparé lorsqu"il peut continuer à lire et à écrire des données malgré la défaillance d"un seul nœud de stockage (un état connu sous le nom de tolérance aux nœuds).' 
---
= protectionDomainRésilience
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'objet protectionDomainResiliency contient l'état de résilience de ce cluster de stockage.  La résilience indique la capacité du cluster de stockage à se réparer automatiquement après une ou plusieurs pannes, le tout au sein d'un seul domaine de protection de son type de domaine de protection associé.  Un cluster de stockage est considéré comme réparé lorsqu'il peut continuer à lire et à écrire des données malgré la défaillance d'un seul nœud de stockage (un état connu sous le nom de tolérance aux nœuds).



== membres de l'objet

Cet objet contient les membres suivants :

|===
| Nom | Description | Type 


 a| 
protectionSchemeRésiliences
 a| 
Une liste d'objets (un pour chaque schéma de protection) contenant des informations sur la résilience aux pannes pour le type de domaine de protection associé.
 a| 
xref:reference_element_api_protectionschemeresiliency.adoc[protectionSchémaRésilience]tableau



 a| 
singleFailureThresholdBytesForBlockData
 a| 
Le nombre maximal d'octets pouvant être stockés sur le cluster de stockage avant de perdre la capacité de se rétablir automatiquement dans un état de tolérance des nœuds.
 a| 
entier



 a| 
Échecs durables pour l'ensemble
 a| 
Le nombre prévu de défaillances simultanées pouvant survenir sans perdre la capacité de se rétablir automatiquement dans un état de tolérance des nœuds pour le quorum de l'ensemble.
 a| 
entier

|===