---
permalink: api/reference_element_api_secureerasedrives.html 
sidebar: sidebar 
keywords: drive,drives,secure,erase,reset,resetting,encryption,key,secureerasedrives 
summary: 'Vous pouvez utiliser la méthode SecureEraseDrives pour supprimer toutes les données résiduelles des disques dont le statut est « disponible ».  Vous pourriez utiliser cette méthode lors du remplacement d"un disque dur arrivant en fin de vie et contenant des données sensibles.  Cette méthode utilise une commande d"effacement de sécurité pour écrire un motif prédéterminé sur le disque et réinitialiser la clé de chiffrement de celui-ci.  Cette méthode asynchrone peut prendre plusieurs minutes.' 
---
= SecureEraseDrives
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `SecureEraseDrives` méthode permettant de supprimer les données résiduelles des disques dont le statut est « disponible ».  Vous pourriez utiliser cette méthode lors du remplacement d'un disque dur arrivant en fin de vie et contenant des données sensibles.  Cette méthode utilise une commande d'effacement de sécurité pour écrire un motif prédéterminé sur le disque et réinitialiser la clé de chiffrement de celui-ci.  Cette méthode asynchrone peut prendre plusieurs minutes.



== Paramètre

Cette méthode possède le paramètre d'entrée suivant :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
lecteurs
 a| 
Liste des identifiants de lecteur à effacer en toute sécurité.
 a| 
tableau d'entiers
 a| 
Aucune
 a| 
Oui

|===


== valeur de retour

Cette méthode a la valeur de retour suivante :

|===
| Nom | Description | Type 


 a| 
asyncHandle
 a| 
Valeur de gestion utilisée pour obtenir le résultat de l'opération.
 a| 
entier

|===


== Exemple de demande

Les requêtes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
   "method": "SecureEraseDrives",
   "params": {
     "drives"  : [3, 4, 5]
   },
   "id" : 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
   "id" : 1
   "result" : {
     "asyncHandle" : 1
   }
}
----


== Nouveautés depuis la version

9,6



== Trouver plus d'informations

* xref:reference_element_api_getasyncresult.adoc[GetAsyncResult]
* xref:reference_element_api_listdrives.adoc[ListDrives]

