---
permalink: api/reference_element_api_network_all_interfaces.html 
sidebar: sidebar 
keywords: object,objects,network 
summary: 'L"objet réseau (toutes les interfaces) collecte des informations sur la configuration de l"interface réseau d"un nœud de stockage.  Vous pouvez utiliser les méthodes GetConfig et GetNetworkConfig pour obtenir ces informations pour un nœud de stockage.' 
---
= réseau (toutes les interfaces)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'objet réseau (toutes les interfaces) collecte des informations sur la configuration des interfaces réseau d'un nœud de stockage.  Vous pouvez utiliser le `GetConfig` et `GetNetworkConfig` méthodes pour obtenir ces informations pour un nœud de stockage.



== membres de l'objet

Cet objet contient les membres suivants :

|===


| Nom | Description | Type 


 a| 
Bond10G
 a| 
Informations de configuration pour l'interface agrégée Bond10G.
 a| 
xref:reference_element_api_network_bonded_interfaces.adoc[réseau (interfaces liées)]



 a| 
Bond1G
 a| 
Informations de configuration pour l'interface liée Bond1G.
 a| 
xref:reference_element_api_network_bonded_interfaces.adoc[réseau (interfaces liées)]



 a| 
eth0-5
 a| 
Un objet pour chaque interface Ethernet du nœud de stockage, décrivant les informations de configuration de l'interface.  Ces objets sont numérotés de 0 à 5 pour correspondre au nom de l'interface.
 a| 
xref:reference_element_api_network_ethernet_interfaces.adoc[réseau (interfaces Ethernet)]



 a| 
lo
 a| 
Informations de configuration pour l'interface de bouclage.
 a| 
xref:reference_element_api_network_local_interfaces.adoc[réseau (interfaces locales)]

|===


== Trouver plus d'informations

* xref:reference_element_api_getconfig.adoc[GetConfig]
* xref:reference_element_api_getnetworkconfig.adoc[Obtenir la configuration réseau]

