---
permalink: api/reference_element_api_modifyvirtualnetwork.html 
sidebar: sidebar 
keywords: virtual,network,modify,modifying,change,changing,edit,editing,modifyvirtualnetwork 
summary: 'Vous pouvez utiliser la méthode ModifyVirtualNetwork pour modifier les attributs d"un réseau virtuel existant.' 
---
= Modifier le réseau virtuel
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `ModifyVirtualNetwork` méthode permettant de modifier les attributs d'un réseau virtuel existant.

Cette méthode vous permet d'ajouter ou de supprimer des blocs d'adresses, de modifier le masque de sous-réseau ou de modifier le nom ou la description du réseau virtuel.  Vous pouvez également l'utiliser pour activer ou désactiver des espaces de noms, ainsi que pour ajouter ou supprimer une passerelle si les espaces de noms sont activés sur le réseau virtuel.


NOTE: Cette méthode requiert soit l'identifiant de réseau virtuel (virtualNetworkID), soit l'étiquette de réseau virtuel (virtualNetworkTag) comme paramètre, mais pas les deux.

PRUDENCE:

L'activation ou la désactivation de la fonctionnalité VLAN de stockage routable pour un réseau virtuel existant en modifiant le paramètre d'espace de noms perturbe tout le trafic géré par le réseau virtuel.  Il est préférable de modifier le paramètre d'espace de noms lors d'une fenêtre de maintenance planifiée.



== Paramètres

Cette méthode possède les paramètres d'entrée suivants :

|===


| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
ID de réseau virtuel
 a| 
Identifiant unique du réseau virtuel à modifier.  Il s'agit de l'identifiant du réseau virtuel attribué par le cluster.
 a| 
entier
 a| 
Aucune
 a| 
Non



 a| 
VirtualNetworkTag
 a| 
L'étiquette réseau qui identifie le réseau virtuel à modifier.
 a| 
entier
 a| 
Aucune
 a| 
Non



 a| 
blocs d'adresses
 a| 
Le nouveau bloc d'adresses à définir pour ce réseau virtuel.  Cela peut inclure l'ajout de nouveaux blocs d'adresses à l'objet existant ou la suppression de blocs d'adresses inutilisés.  Vous pouvez également étendre ou réduire la taille des blocs d'adresses existants.  Vous pouvez uniquement augmenter la taille des blocs d'adresses de départ d'un objet Réseau virtuel ; vous ne pouvez jamais la diminuer.  Membres requis pour cet objet :

* début : Le début de la plage d'adresses IP.  (chaîne)
* taille : le nombre d’adresses IP à inclure dans le bloc.  (entier)

 a| 
objet JSON
 a| 
Aucune
 a| 
Non



 a| 
porte
 a| 
L'adresse IP d'une passerelle du réseau virtuel.  Ce paramètre n'est valide que si le paramètre d'espace de noms est défini sur vrai.
 a| 
chaîne
 a| 
Aucune
 a| 
Non



 a| 
attributs
 a| 
Liste de paires nom-valeur au format objet JSON.
 a| 
objet JSON
 a| 
Aucune
 a| 
Non



 a| 
nom
 a| 
Le nouveau nom du réseau virtuel.
 a| 
chaîne
 a| 
Aucune
 a| 
Non



 a| 
espace de noms
 a| 
Lorsqu'elle est définie sur « true », cette option active la fonctionnalité VLAN de stockage routable en recréant le réseau virtuel et en configurant un espace de noms pour le contenir.  Lorsqu'elle est définie sur « false », la fonctionnalité VRF est désactivée pour le réseau virtuel.  Modifier cette valeur perturbe le trafic transitant par ce réseau virtuel.
 a| 
booléen
 a| 
Aucune
 a| 
Non



 a| 
masque de sous-réseau
 a| 
Nouveau masque de réseau pour ce réseau virtuel.
 a| 
chaîne
 a| 
Aucune
 a| 
Non



 a| 
VIP
 a| 
L'adresse IP virtuelle de stockage pour ce réseau virtuel.  L'adresse SVIP d'un réseau virtuel ne peut pas être modifiée.  Vous devez créer un nouveau réseau virtuel pour utiliser une adresse SVIP différente.
 a| 
chaîne
 a| 
Aucune
 a| 
Non

|===


== Valeurs de retour

Cette méthode ne renvoie aucune valeur.



== Exemple de demande

Les requêtes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
  "method": "ModifyVirtualNetwork",
  "params": {
    "virtualNetworkID": 2,
    "name": "ESX-VLAN-3112",
    "addressBlocks": [
     {
      "start": "10.1.112.1",
      "size": 20
     },
     {
      "start": "10.1.112.100",
      "size": 20
     }
   ],
    "netmask": "255.255.255.0",
    "gateway": "10.0.1.254",
    "svip": "10.1.112.200",
    "attributes": {}
  },
  "id":1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
  "id": 1,
  "result": {
  }
}
----


== Nouveautés depuis la version

9,6
