---
permalink: api/reference_element_api_disableclusterssh.html 
sidebar: sidebar 
keywords: SSH,disable,disabling,cluster,DisableClusterSsh 
summary: 'Vous pouvez utiliser la méthode DisableClusterSsh pour désactiver le service SSH pour l"ensemble du cluster de stockage.  Lorsque vous ajoutez des nœuds au cluster de stockage, les nouveaux nœuds hériteront de ce paramètre global du cluster.' 
---
= Désactiver ClusterSSH
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `DisableClusterSsh` Méthode pour désactiver le service SSH pour l'ensemble du cluster de stockage.  Lorsque vous ajoutez des nœuds au cluster de stockage, les nouveaux nœuds hériteront de ce paramètre global du cluster.



== Paramètre

Cette méthode ne comporte aucun paramètre d'entrée.



== valeur de retour

Cette méthode a la valeur de retour suivante :

|===
| Nom | Description | Type 


 a| 
résultat
 a| 
Un objet JSON contenant l'état du service SSH pour le cluster de stockage, le temps restant avant la désactivation de SSH et l'état du service SSH pour chaque nœud.
 a| 
objet JSON

|===


== Exemple de demande

Les requêtes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
  "method": "DisableClusterSsh",
  "params": {
      },
  "id" : 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
	"id": 1,
	"result" : {
    "enabled": true,
    "timeRemaining": "00:43:21",
    "nodes": [
    {
        "nodeID": 1,
        "enabled": true
    },
    {
        "nodeID": 2,
        "enabled": true
    },
    {
        "nodeID": 3,
        "enabled": false
    },
    {
        "nodeID": 4,
        "enabled": false
    } ]
			}
	}
----


== Nouveautés depuis la version

10,3
