---
permalink: api/reference_element_api_setnodesupplementaltlsciphers.html 
sidebar: sidebar 
keywords: tls,cipher,set,setting,list,supplemental,setnodesupplementaltlsciphers,node 
summary: Vous pouvez utiliser la méthode SetNodeSupplementalTlsCiphers pour spécifier la liste des chiffrements TLS supplémentaires.  Vous pouvez utiliser cette commande sur les nœuds de gestion. 
---
= Définir les chiffrements TLS supplémentaires du nœud
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `SetNodeSupplementalTlsCiphers` méthode permettant de spécifier la liste des chiffrements TLS supplémentaires.  Vous pouvez utiliser cette commande sur les nœuds de gestion.



== Paramètre


NOTE: Vous devez appeler cette méthode sur le nœud de gestion. Par exemple:

[listing]
----
https://<management node IP>:442/json-rpc/10.0
----
Cette méthode possède le paramètre d'entrée suivant :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
Chiffres supplémentaires
 a| 
Les noms des suites de chiffrement supplémentaires utilisent le schéma de dénomination OpenSSL.  L'utilisation des noms de suites de chiffrement est insensible à la casse.
 a| 
chaîne
 a| 
Aucune
 a| 
Oui

|===


== Valeurs de retour

Cette méthode renvoie les valeurs suivantes :

|===
| Nom | Description | Type 


 a| 
Chiffres obligatoires
 a| 
Liste des suites de chiffrement TLS obligatoires pour le nœud.  Ce sont des chiffrements qui sont toujours actifs sur le nœud.
 a| 
chaîne



 a| 
Chiffres supplémentaires
 a| 
Liste des suites de chiffrement TLS supplémentaires pour le nœud.
 a| 
chaîne

|===


== Exemple de demande

Les requêtes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
   "method": "SetNodeSupplementalTlsCiphers",
   "params": {
        "supplementalCiphers": [
            "DHE-RSA-AES128-SHA256",
            "DHE-RSA-AES128-GCM-SHA256",
            "ECDHE-RSA-AES128-SHA256",
            "ECDHE-RSA-AES128-GCM-SHA256"
        ]
   },
   "id": 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
  "id" : 1,
  "result" : {
        "mandatoryCiphers": [
            "DHE-RSA-AES256-SHA256",
            "DHE-RSA-AES256-GCM-SHA384",
            "ECDHE-RSA-AES256-SHA384",
            "ECDHE-RSA-AES256-GCM-SHA384"
        ],
        "supplementalCiphers": [
            "DHE-RSA-AES128-SHA256",
            "DHE-RSA-AES128-GCM-SHA256",
            "ECDHE-RSA-AES128-SHA256",
            "ECDHE-RSA-AES128-GCM-SHA256"
        ]
    }
}
----