---
permalink: api/reference_element_api_modifyvolumepair.html 
sidebar: sidebar 
keywords: volume,pair,pairs,modify,modifying,edit,editing,changing,change,modifyvolumepair,paired 
summary: 'Vous pouvez utiliser la méthode ModifyVolumePair pour suspendre ou redémarrer la réplication entre une paire de volumes.  Cette méthode est définie sur le volume source (le volume avec accès en lecture/écriture).' 
---
= ModifierVolumePair
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `ModifyVolumePair` méthode pour suspendre ou redémarrer la réplication entre deux volumes.  Cette méthode est définie sur le volume source (le volume avec accès en lecture/écriture).



== Paramètres

Cette méthode possède les paramètres d'entrée suivants :

|===


| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
volumeID
 a| 
Numéro d'identification du volume à modifier.
 a| 
entier
 a| 
Aucune
 a| 
Oui



 a| 
manuel en pause
 a| 
La réplication à distance peut être mise en pause ou redémarrée sur le volume source (lecture/écriture). Valeurs possibles :

* true : Mettre en pause la réplication du volume.
* faux : Redémarrer la réplication des volumes.


Si aucune valeur n'est spécifiée, aucune modification de la réplication n'est effectuée.
 a| 
booléen
 a| 
Aucune
 a| 
Non



 a| 
mode
 a| 
Mode de réplication de volume. Valeurs possibles :

* Asynchrone : les écritures sont prises en compte lorsqu’elles sont terminées localement.  Le cluster n'attend pas que les écritures soient répliquées sur le cluster cible.
* Synchronisation : La source accuse réception de l'écriture lorsque les données sont stockées localement et sur le cluster distant.
* SnapshotsOnly : seuls les instantanés créés sur le cluster source sont répliqués.  Les écritures actives provenant du volume source ne sont pas répliquées.

 a| 
chaîne
 a| 
Aucune
 a| 
Non

|===


== valeur de retour

Cette méthode ne renvoie aucune valeur.



== Exemple de demande

Les requêtes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
  "method": "ModifyVolumePair",
  "params": {
    "pausedManual": false,
    "volumeID": 5,
    "mode": "sync"
   },
  "id": 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
   "id" : 1,
   "result" : {}
}
----


== Nouveautés depuis la version

9,6
