---
permalink: api/reference_element_api_liststoragecontainers.html 
sidebar: sidebar 
keywords: virtual,volume,storage,container,containers,list,listing,liststoragecontainers 
summary: Vous pouvez utiliser la méthode ListStorageContainers pour récupérer des informations sur tous les conteneurs de stockage de volumes virtuels connus du système. 
---
= ListStorageContainers
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `ListStorageContainers` méthode permettant de récupérer des informations sur tous les conteneurs de stockage de volumes virtuels connus du système.



== Paramètres

Cette méthode possède le paramètre d'entrée suivant :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
ID des conteneurs de stockage
 a| 
Liste des identifiants des conteneurs de stockage pour lesquels récupérer des informations.  Si vous omettez ce paramètre, la méthode renvoie des informations sur tous les conteneurs de stockage du système.
 a| 
tableau UUID
 a| 
Aucune
 a| 
Non

|===


== valeur de retour

Cette méthode a la valeur de retour suivante :

|===


| Nom | Description | Type 


 a| 
conteneurs de stockage
 a| 
Liste des objets contenant des informations sur tous les conteneurs de stockage du système.
 a| 
xref:reference_element_api_storagecontainer.adoc[conteneur de stockage]tableau

|===


== Exemple de demande

Les requêtes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
   "method": "ListStorageContainers",
   "params": {
      "storageContainerIDs": ["efda8307-b916-4424-979e-658a3f16894d"]
   },
   "id" : 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
  "id": 6395,
  "result": {
    "storageContainers": [
      {
        "accountID": 64,
        "initiatorSecret": "EJ:08An1MyNQmL!7",
        "name": "VvolContainer",
        "protocolEndpointType": "SCSI",
        "status": "active",
        "storageContainerID": "efda8307-b916-4424-979e-658a3f16894d",
        "targetSecret": "g38}zWBK%206jQr~",
        "virtualVolumes": []
      }
    ]
  }
}
----


== Nouveautés depuis la version

9,6
