---
permalink: api/reference_element_api_restartnetworking.html 
sidebar: sidebar 
keywords: node,restarting,restart,networking,network,service,services,restartnetworking 
summary: Vous pouvez utiliser la méthode RestartNetworking pour redémarrer les services réseau sur un nœud. 
---
= Redémarrer le réseau
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `RestartNetworking` méthode pour redémarrer les services réseau sur un nœud.

PRUDENCE:

Cette méthode redémarre tous les services réseau sur un nœud, entraînant une perte temporaire de connectivité réseau.



== Paramètre

Cette méthode possède le paramètre d'entrée suivant :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
forcer
 a| 
Définissez cette valeur sur « true » pour redémarrer les services réseau sur un nœud.
 a| 
booléen
 a| 
Aucune
 a| 
Oui

|===


== Valeurs de retour

Cette méthode ne renvoie aucune valeur.



== Exemple de demande

Les requêtes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
   "method": "RestartNetworking",
   "params": {
              "force" : true
             },
   "id" : 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{ "id" : 1,
  "result" : {}
}
----


== Nouveautés depuis la version

9,6
