---
permalink: api/reference_element_api_getnvraminfo.html 
sidebar: sidebar 
keywords: nvram,info,get,getting,getnvraminfo 
summary: Vous pouvez utiliser la méthode GetNvramInfo pour obtenir des informations sur la carte NVRAM de chaque nœud. 
---
= GetNvramInfo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `GetNvramInfo` méthode pour obtenir des informations de chaque nœud concernant la carte NVRAM .



== Paramètre

Cette méthode possède le paramètre d'entrée suivant :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
forcer
 a| 
Le paramètre de force doit être inclus dans cette méthode pour qu'elle s'exécute correctement sur tous les nœuds du cluster.
 a| 
booléen
 a| 
Aucune
 a| 
Oui

|===


== valeur de retour

Cette méthode a la valeur de retour suivante :

|===
| Nom | Description | Type 


 a| 
nvramInfo
 a| 
Tableaux d'événements et d'erreurs détectés sur la carte NVRAM .
 a| 
objet JSON

|===


== Exemple de demande

Les requêtes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
  "method": "GetNvramInfo",
  "params": {
      "force": true
	  },
  "id" : 1
}
----


== Exemple de réponse

En raison de sa longueur, cet exemple de réponse est documenté dans un sujet supplémentaire.



== Nouveautés depuis la version

9,6



== Trouver plus d'informations

xref:reference_element_api_response_example_getnvraminfo.adoc[GetNvramInfo]
