---
permalink: api/reference_element_api_listsnapshots.html 
sidebar: sidebar 
keywords: snapshot,snapshots,list,listing,attributes,listsnapshots 
summary: Vous pouvez utiliser ListSnapshots pour récupérer les attributs de chaque instantané pris sur le volume. 
---
= Instantanés de la liste
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser `ListSnapshots` pour renvoyer les attributs de chaque instantané pris sur le volume.

Les informations relatives aux instantanés résidant sur le cluster cible seront affichées sur le cluster source lorsque cette méthode sera appelée depuis le cluster source.



== Paramètres

Cette méthode possède les paramètres d'entrée suivants :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
volumeID
 a| 
Récupère les instantanés d'un volume.  Si l'identifiant du volume n'est pas fourni, tous les instantanés de tous les volumes sont renvoyés.
 a| 
entier
 a| 
Aucune
 a| 
Non



 a| 
snapshotID
 a| 
Récupère les informations associées à un identifiant d'instantané individuel.
 a| 
entier
 a| 
Aucune
 a| 
Non

|===


== valeur de retour

Cette méthode a la valeur de retour suivante :

|===
| Nom | Description | Type 


 a| 
instantanés
 a| 
Informations concernant chaque instantané pour chaque volume.  Si l'identifiant du volume n'est pas fourni, tous les instantanés de tous les volumes sont renvoyés.  Les instantanés appartenant à un groupe sont renvoyés avec un identifiant de groupe.
 a| 
xref:reference_element_api_snapshot.adoc[instantané]tableau

|===


== Exemple de demande

Les requêtes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
   "method": "ListSnapshots",
   "params": {
             "volumeID": "1"
       },
   "id" : 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
  "id": 1,
  "result": {
    "snapshots": [
        {
          "attributes": {},
          "checksum": "0x0",
          "createTime": "2015-05-08T13:15:00Z",
          "enableRemoteReplication": true,
          "expirationReason": "None",
          "expirationTime": "2015-05-08T21:15:00Z",
          "groupID": 0,
          "groupSnapshotUUID": "00000000-0000-0000-0000-000000000000",
          "name": "Hourly",
          "remoteStatuses": [
              {
                "remoteStatus": "Present",
                "volumePairUUID": "237e1cf9-fb4a-49de-a089-a6a9a1f0361e"
              }
         ],
          "snapshotID": 572,
          "snapshotUUID": "efa98e40-cb36-4c20-a090-a36c48296c14",
          "status": "done",
          "totalSize": 10000269312,
          "volumeID": 1
        }
      ]
    }
  }
----


== Nouveautés depuis la version

9,6
