---
permalink: api/reference_element_api_addldapclusteradmin.html 
sidebar: sidebar 
keywords: LDAP,cluster,admin,add,adding,addldapclusteradmin 
summary: 'Vous pouvez utiliser AddLdapClusterAdmin pour ajouter un nouvel utilisateur administrateur de cluster LDAP.  Un administrateur de cluster LDAP peut gérer le cluster à l"aide de l"API et des outils de gestion.  Les comptes d"administrateur du cluster LDAP sont totalement distincts et sans lien avec les comptes locataires standard.' 
---
= AjouterLdapClusterAdmin
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `AddLdapClusterAdmin` ajouter un nouvel utilisateur administrateur de cluster LDAP.  Un administrateur de cluster LDAP peut gérer le cluster à l'aide de l'API et des outils de gestion.  Les comptes d'administrateur du cluster LDAP sont totalement distincts et sans lien avec les comptes locataires standard.



== Paramètres

Vous pouvez également utiliser cette méthode pour ajouter un groupe LDAP défini dans Active Directory®.  Le niveau d'accès attribué au groupe est transmis aux utilisateurs individuels du groupe LDAP.

Cette méthode possède les paramètres d'entrée suivants :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
accéder
 a| 
Contrôle les méthodes que cet administrateur de cluster peut utiliser.
 a| 
tableau de chaînes
 a| 
Aucune
 a| 
Oui



 a| 
accepterEula
 a| 
Acceptez le contrat de licence utilisateur final.  Définissez cette valeur sur « true » pour ajouter un compte d'administrateur de cluster au système.  Si cette valeur est omise ou définie sur false, l'appel de méthode échoue.
 a| 
booléen
 a| 
Aucune
 a| 
Oui



 a| 
attributs
 a| 
Liste de paires nom-valeur au format objet JSON.
 a| 
objet JSON
 a| 
Aucune
 a| 
Non



 a| 
nom d'utilisateur
 a| 
Nom d'utilisateur distinctif du nouvel administrateur du cluster LDAP.
 a| 
chaîne
 a| 
Aucune
 a| 
Oui

|===


== Valeurs de retour

Cette méthode ne renvoie aucune valeur.



== Exemple de demande

Les requêtes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
  "method": "AddLdapClusterAdmin",
  "params": {"username":"cn=mike jones,ou=ptusers,dc=prodtest,dc=solidfire,dc=net",
    "access": ["administrator", "read"
    ]
  },
"id": 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
 "id": 1,
 "result": {}
}
----


== Nouveautés depuis la version

9,6



== Trouver plus d'informations

xref:reference_element_api_app_b_access_control.adoc[Contrôle d'accès]
