---
permalink: api/reference_element_api_listvirtualvolumebindings.html 
sidebar: sidebar 
keywords: virtual,volume,vvol,cluster,bound,protocol,endpoint,binding,bindings,list,listing,listvirtualvolumebindings 
summary: Vous pouvez utiliser la méthode ListVirtualVolumeBindings pour obtenir la liste de tous les volumes virtuels du cluster liés à des points de terminaison de protocole. 
---
= ListerVirtualVolumeBindings
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `ListVirtualVolumeBindings` Méthode permettant d'obtenir la liste de tous les volumes virtuels du cluster liés à des points de terminaison de protocole.



== Paramètres

Cette méthode possède le paramètre d'entrée suivant :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
ID de liaison de volume virtuel
 a| 
Liste des identifiants de liaison de volumes virtuels pour lesquels récupérer des informations.  Si vous omettez ce paramètre, la méthode renvoie des informations sur toutes les liaisons de volumes virtuels.
 a| 
tableau d'entiers
 a| 
Aucune
 a| 
Non

|===


== valeur de retour

Cette méthode a la valeur de retour suivante :

|===
| Nom | Description | Type 


 a| 
reliures
 a| 
Une liste d'objets décrivant tous les volumes virtuels du cluster qui sont liés à des points de terminaison de protocole.
 a| 
xref:reference_element_api_binding_vvols.adoc[obligatoire]

|===


== Exemple de demande

Les requêtes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
  "method": "ListVirtualVolumeBindings",
    "params": {
    },
    "id": 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
  "id": 1,
  "result": {
    "bindings": [
      {
        "protocolEndpointID": "5dd53da0-b9b7-43f9-9b7e-b41c2558e92b",
        "protocolEndpointInBandID": "naa.6f47acc2000000016a67746700000000",
        "protocolEndpointType": "SCSI",
        "virtualVolumeBindingID": 177,
        "virtualVolumeHostID": "564de1a4-9a99-da0f-8b7c-3a41dfd64bf1",
        "virtualVolumeID": "269d3378-1ca6-4175-a18f-6d4839e5c746",
        "virtualVolumeSecondaryID": "0xe200000000a6"
      }
    ]
  }
}
----


== Nouveautés depuis la version

9,6
