---
permalink: api/reference_element_api_getbootstrapconfig.html 
sidebar: sidebar 
keywords: cluster,getting,bootstrap,information,node,GetBootstrapConfig 
summary: 'Vous pouvez utiliser la méthode GetBootstrapConfig pour obtenir les informations sur le cluster et les nœuds à partir du fichier de configuration d"amorçage.  Utilisez cette méthode API sur un nœud individuel avant qu"il ne soit intégré à un cluster.  Les informations renvoyées par cette méthode sont utilisées dans l"interface de configuration du cluster lors de la création de celui-ci.' 
---
= GetBootstrapConfig
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `GetBootstrapConfig` méthode pour obtenir les informations sur le cluster et les nœuds à partir du fichier de configuration d'amorçage.  Utilisez cette méthode API sur un nœud individuel avant qu'il ne soit intégré à un cluster.  Les informations renvoyées par cette méthode sont utilisées dans l'interface de configuration du cluster lors de la création de celui-ci.



== Paramètres

Cette méthode ne requiert aucun paramètre d'entrée.



== Valeurs de retour

Cette méthode renvoie les valeurs suivantes :

|===
| Nom | Description | Type 


 a| 
nom du cluster
 a| 
Nom du cluster.
 a| 
chaîne



 a| 
VIP
 a| 
Adresse MVIP du cluster.  Laissez ce champ vide si le nœud ne fait pas partie d'un cluster.
 a| 
chaîne



 a| 
nom_du_node
 a| 
Nom du nœud.
 a| 
chaîne



 a| 
nœuds
 a| 
Liste d'informations concernant chaque nœud qui attend activement de rejoindre le cluster. Valeurs possibles :

* chassisType : (chaîne) Plateforme matérielle du nœud.
* cip : (chaîne) Adresse IP du cluster du nœud.
* compatible : (booléen) Indique si le nœud est compatible avec le nœud sur lequel l’appel API a été exécuté.
* nom_hôte : (chaîne) Nom d'hôte du nœud.
* mip : (chaîne) L'adresse IP de gestion IPv4 du nœud.
* mipV6 : (chaîne) L’adresse IP de gestion IPv6 du nœud.
* nodeType : (chaîne) Nom du modèle du nœud.
* version : (chaîne de caractères)Version du logiciel actuellement installé sur le nœud.

 a| 
tableau d'objets JSON



 a| 
VIP
 a| 
Adresse SVIP du cluster.  Valeur nulle si le nœud ne fait pas partie d'un cluster.
 a| 
chaîne



 a| 
version
 a| 
Version du logiciel Element actuellement installée sur le nœud appelé par cette méthode API.
 a| 
chaîne

|===


== Exemple de demande

Les requêtes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
   "method": "GetBootstrapConfig",
   "params": {},
   "id" : 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
	"id":1,
	"result":{
		"clusterName":"testname",
		"nodeName":"testnode",
		"svip": "10.117.1.5",
		"mvip": "10.117.1.6",
		"nodes":[
			{
				"chassisType":"R630",
				"cip":"10.117.115.16",
				"compatible":true,
				"hostname":"NLABP1132",
				"mip":"10.117.114.16",
				"mipV6":"fd20:8b1e:b256:45a::16",
				"nodeType":"SF2405",
				"role":"Storage",
				"version":"11.0"
			},
			{
				"chassisType":"R630",
				"cip":"10.117.115.17",
				"compatible":true,
				"hostname":"NLABP1133",
				"mip":"10.117.114.17",
				"mipV6":"fd20:8b1e:b256:45a::17",
				"nodeType":"SF2405",
				"role":"Storage",
				"version":"11.0"
			},
			{
				"chassisType":"R630",
				"cip":"10.117.115.18",
				"compatible":true,
				"hostname":"NLABP1134",
				"mip":"10.117.114.18",
				"mipV6":"fd20:8b1e:b256:45a::18",
				"nodeType":"SF2405",
				"role":"Storage",
				"version":"11.0"
			}
		],
		"version":"11.0"
	}
}
----


== Nouveautés depuis la version

9,6



== Trouver plus d'informations

xref:reference_element_api_createcluster.adoc[Créer un cluster]
