---
permalink: api/reference_element_api_listsnapmirrorrelationships.html 
sidebar: sidebar 
keywords: snapmirror,endpoints,endpoint,list,listing,listsnapmirrorrelationships 
summary: 'L"interface utilisateur Web du logiciel Element utilise la méthode ListSnapMirrorRelationships pour lister une ou toutes les relations SnapMirror sur un cluster de stockage Element.' 
---
= ListSnapMirrorRelationships
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'interface utilisateur Web du logiciel Element utilise `ListSnapMirrorRelationships` Méthode permettant de lister une ou toutes les relations SnapMirror sur un cluster de stockage Element.



== Paramètres

Cette méthode possède les paramètres d'entrée suivants :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
snapMirrorEndpointID
 a| 
N'afficher que les relations associées à l'ID de point de terminaison spécifié.  Si aucun identifiant de point de terminaison n'est fourni, le système répertorie les relations de tous les points de terminaison SnapMirror connus.
 a| 
entier
 a| 
Aucune
 a| 
Non



 a| 
destinationVolume
 a| 
Lister les relations associées au volume de destination spécifié.
 a| 
xref:reference_element_api_snapmirrorvolumeinfo.adoc[snapMirrorVolumeInfo]
 a| 
Aucune
 a| 
Non



 a| 
sourceVolume
 a| 
Lister les relations associées au volume source spécifié.
 a| 
xref:reference_element_api_snapmirrorvolumeinfo.adoc[snapMirrorVolumeInfo]
 a| 
Aucune
 a| 
Non



 a| 
serveur virtuel
 a| 
Lister les relations sur le serveur virtuel spécifié.
 a| 
chaîne
 a| 
Aucune
 a| 
Non



 a| 
identifiant de relation
 a| 
Lister les relations associées à l'ID de relation spécifié.
 a| 
chaîne
 a| 
Aucune
 a| 
Non

|===


== valeur de retour

Cette méthode a la valeur de retour suivante :

|===


| Nom | Description | Type 


 a| 
snapMirrorRelationships
 a| 
Une liste d'objets contenant des informations sur les relations SnapMirror .
 a| 
xref:reference_element_api_snapmirrorrelationship.adoc[snapMirrorRelation]tableau

|===


== Nouveautés depuis la version

10,1
