---
permalink: api/reference_element_api_listclusterpairs.html 
sidebar: sidebar 
keywords: cluster,pair,pairs,paired,list,listing,listclusterpairs 
summary: 'Vous pouvez utiliser la méthode ListClusterPairs pour lister tous les clusters associés au cluster actuel.  Cette méthode renvoie des informations sur les appariements de clusters actifs et en attente, telles que des statistiques sur l"appariement actuel ainsi que la connectivité et la latence (en millisecondes) de l"appariement de clusters.' 
---
= ListClusterPairs
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `ListClusterPairs` méthode permettant de lister tous les clusters associés au cluster actuel.  Cette méthode renvoie des informations sur les appariements de clusters actifs et en attente, telles que des statistiques sur l'appariement actuel ainsi que la connectivité et la latence (en millisecondes) de l'appariement de clusters.



== Paramètre

Cette méthode ne comporte aucun paramètre d'entrée :



== valeur de retour

Cette méthode a la valeur de retour suivante :

|===
| Nom | Description | Type 


 a| 
paires de clusters
 a| 
Informations concernant chaque paire de groupes.
 a| 
xref:reference_element_api_clusterpair.adoc[paire de clusters]tableau

|===


== Exemple de demande

Les requêtes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
   "method": "ListClusterPairs",
   "params": {
      },
   "id" : 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
 "id": 1,
 "result": {
   "clusterPairs": [
     {
      "clusterName": "cluster2",
      "clusterPairID": 3,
      "clusterPairUUID": "9866fbeb-c2f8-4df3-beb9-58a5c4e49c9b",
      "clusterUUID": 5487,
      "latency": 1,
      "mvip": "172.1.1.5",
      "status": "Connected"
      "version": "8.0.0.1361"
     },
     {
      "clusterName": "cluster3",
      "clusterPairID": 2,
      "clusterPairUUID": "8132a699-ce82-41e0-b406-fb914f976042",
      "clusterUUID": 1383,
      "latency": 1,
      "mvip": "172.1.1.6",
      "status": "Connected"
      "version": "8.0.0.1361"
     }
   ]
 }
----


== Nouveautés depuis la version

9,6
